// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/age.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializeageCancelRequest")
public inline fun ageCancelRequest(block: com.senbax.senvend.proto.api.v1.AgeCancelRequestKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.AgeCancelRequest =
  com.senbax.senvend.proto.api.v1.AgeCancelRequestKt.Dsl._create(com.senbax.senvend.proto.api.v1.AgeCancelRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Cancels an ongoing age verification process on the SENVEND Terminal.
 * Can be sent at any time, but will result in AGE_API_FAILURE_REASON_UUID_NOT_FOUND
 * if there is nothing to cancel.
 * If sent in an AgeRequest without UUID, will cancel any running age verification or payment process without UUID check.
 * ```
 *
 * Protobuf type `api.v1.AgeCancelRequest`
 */
public object AgeCancelRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.AgeCancelRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.AgeCancelRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.AgeCancelRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.AgeCancelRequest.copy(block: `com.senbax.senvend.proto.api.v1`.AgeCancelRequestKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.AgeCancelRequest =
  `com.senbax.senvend.proto.api.v1`.AgeCancelRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

