// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/age.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializeageResponse")
public inline fun ageResponse(block: com.senbax.senvend.proto.api.v1.AgeResponseKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.AgeResponse =
  com.senbax.senvend.proto.api.v1.AgeResponseKt.Dsl._create(com.senbax.senvend.proto.api.v1.AgeResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Response to an AgeRequest.
 * ```
 *
 * Protobuf type `api.v1.AgeResponse`
 */
public object AgeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.AgeResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.AgeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.AgeResponse = _builder.build()

    /**
     * ```
     * Unique identifier for the age verification request. Mirrors the ID from the AgeRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public var id: com.senbax.senvend.proto.api.v1.Uuid4
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Unique identifier for the age verification request. Mirrors the ID from the AgeRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * ```
     * Unique identifier for the age verification request. Mirrors the ID from the AgeRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    public val AgeResponseKt.Dsl.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
      get() = _builder.idOrNull

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeSuccess success = 2 [json_name = "success"];`
     */
    public var success: com.senbax.senvend.proto.api.v1.AgeSuccess
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeSuccess success = 2 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeSuccess success = 2 [json_name = "success"];`
     * @return Whether the success field is set.
     */
    public fun hasSuccess(): kotlin.Boolean {
      return _builder.hasSuccess()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure failure = 3 [json_name = "failure"];`
     */
    public var failure: com.senbax.senvend.proto.api.v1.AgeFailure
      @kotlin.jvm.JvmName("getFailure")
        get() = _builder.failure
      @kotlin.jvm.JvmName("setFailure")
        set(value) {
        _builder.failure = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure failure = 3 [json_name = "failure"];`
     */
    public fun clearFailure() {
      _builder.clearFailure()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure failure = 3 [json_name = "failure"];`
     * @return Whether the failure field is set.
     */
    public fun hasFailure(): kotlin.Boolean {
      return _builder.hasFailure()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess api_success = 4 [json_name = "apiSuccess"];`
     */
    public var apiSuccess: com.senbax.senvend.proto.api.v1.AgeApiSuccess
      @kotlin.jvm.JvmName("getApiSuccess")
        get() = _builder.apiSuccess
      @kotlin.jvm.JvmName("setApiSuccess")
        set(value) {
        _builder.apiSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess api_success = 4 [json_name = "apiSuccess"];`
     */
    public fun clearApiSuccess() {
      _builder.clearApiSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess api_success = 4 [json_name = "apiSuccess"];`
     * @return Whether the apiSuccess field is set.
     */
    public fun hasApiSuccess(): kotlin.Boolean {
      return _builder.hasApiSuccess()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiFailure api_failure = 5 [json_name = "apiFailure"];`
     */
    public var apiFailure: com.senbax.senvend.proto.api.v1.AgeApiFailure
      @kotlin.jvm.JvmName("getApiFailure")
        get() = _builder.apiFailure
      @kotlin.jvm.JvmName("setApiFailure")
        set(value) {
        _builder.apiFailure = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiFailure api_failure = 5 [json_name = "apiFailure"];`
     */
    public fun clearApiFailure() {
      _builder.clearApiFailure()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiFailure api_failure = 5 [json_name = "apiFailure"];`
     * @return Whether the apiFailure field is set.
     */
    public fun hasApiFailure(): kotlin.Boolean {
      return _builder.hasApiFailure()
    }
    public val resultCase: com.senbax.senvend.proto.api.v1.AgeResponse.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.AgeResponse.copy(block: `com.senbax.senvend.proto.api.v1`.AgeResponseKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.AgeResponse =
  `com.senbax.senvend.proto.api.v1`.AgeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
  get() = if (hasId()) getId() else null

public val com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder.successOrNull: com.senbax.senvend.proto.api.v1.AgeSuccess?
  get() = if (hasSuccess()) getSuccess() else null

public val com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder.failureOrNull: com.senbax.senvend.proto.api.v1.AgeFailure?
  get() = if (hasFailure()) getFailure() else null

public val com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder.apiSuccessOrNull: com.senbax.senvend.proto.api.v1.AgeApiSuccess?
  get() = if (hasApiSuccess()) getApiSuccess() else null

public val com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder.apiFailureOrNull: com.senbax.senvend.proto.api.v1.AgeApiFailure?
  get() = if (hasApiFailure()) getApiFailure() else null

