// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializelineItem")
public inline fun lineItem(block: com.senbax.senvend.proto.api.v1.LineItemKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.LineItem =
  com.senbax.senvend.proto.api.v1.LineItemKt.Dsl._create(com.senbax.senvend.proto.api.v1.LineItem.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Represents a single line item of a complete invoice.
 * ```
 *
 * Protobuf type `api.v1.LineItem`
 */
public object LineItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.LineItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.LineItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.LineItem = _builder.build()

    /**
     * ```
     * Price of a single instance of this product, in cents.
     * ```
     *
     * `optional uint32 price = 1 [json_name = "price"];`
     */
    public var price: kotlin.Int
      @kotlin.jvm.JvmName("getPrice")
        get() = _builder.price
      @kotlin.jvm.JvmName("setPrice")
        set(value) {
        _builder.price = value
      }
    /**
     * ```
     * Price of a single instance of this product, in cents.
     * ```
     *
     * `optional uint32 price = 1 [json_name = "price"];`
     */
    public fun clearPrice() {
      _builder.clearPrice()
    }
    /**
     * ```
     * Price of a single instance of this product, in cents.
     * ```
     *
     * `optional uint32 price = 1 [json_name = "price"];`
     * @return Whether the price field is set.
     */
    public fun hasPrice(): kotlin.Boolean {
      return _builder.hasPrice()
    }

    /**
     * ```
     * The quantity of items to sell.
     * ```
     *
     * `uint32 quantity = 2 [json_name = "quantity"];`
     */
    public var quantity: kotlin.Int
      @kotlin.jvm.JvmName("getQuantity")
        get() = _builder.quantity
      @kotlin.jvm.JvmName("setQuantity")
        set(value) {
        _builder.quantity = value
      }
    /**
     * ```
     * The quantity of items to sell.
     * ```
     *
     * `uint32 quantity = 2 [json_name = "quantity"];`
     */
    public fun clearQuantity() {
      _builder.clearQuantity()
    }

    /**
     * ```
     * The slot this product was sold from.
     * ```
     *
     * `.api.v1.Selection selection = 3 [json_name = "selection"];`
     */
    public var selection: com.senbax.senvend.proto.api.v1.Selection
      @kotlin.jvm.JvmName("getSelection")
        get() = _builder.selection
      @kotlin.jvm.JvmName("setSelection")
        set(value) {
        _builder.selection = value
      }
    /**
     * ```
     * The slot this product was sold from.
     * ```
     *
     * `.api.v1.Selection selection = 3 [json_name = "selection"];`
     */
    public fun clearSelection() {
      _builder.clearSelection()
    }
    /**
     * ```
     * The slot this product was sold from.
     * ```
     *
     * `.api.v1.Selection selection = 3 [json_name = "selection"];`
     * @return Whether the selection field is set.
     */
    public fun hasSelection(): kotlin.Boolean {
      return _builder.hasSelection()
    }
    public val productCase: com.senbax.senvend.proto.api.v1.LineItem.ProductCase
    @kotlin.jvm.JvmName("getProductCase")
      get() = _builder.getProductCase()

    public fun clearProduct() {
      _builder.clearProduct()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.LineItem.copy(block: `com.senbax.senvend.proto.api.v1`.LineItemKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.LineItem =
  `com.senbax.senvend.proto.api.v1`.LineItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.LineItemOrBuilder.selectionOrNull: com.senbax.senvend.proto.api.v1.Selection?
  get() = if (hasSelection()) getSelection() else null

