// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializepayRequest")
public inline fun payRequest(block: com.senbax.senvend.proto.api.v1.PayRequestKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayRequest =
  com.senbax.senvend.proto.api.v1.PayRequestKt.Dsl._create(com.senbax.senvend.proto.api.v1.PayRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * All messages sent from the integrator/VMC to the SENVEND terminal to manage payments.
 * A payment process must be started with the PayStart message.
 * ```
 *
 * Protobuf type `api.v1.PayRequest`
 */
public object PayRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.PayRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.PayRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.PayRequest = _builder.build()

    /**
     * ```
     * Unique identifier for this payment request. Can be used for tracing and correlating requests and responses.
     * Optional field. If not provided, the system will generate a new UUID.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public var id: com.senbax.senvend.proto.api.v1.Uuid4
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Unique identifier for this payment request. Can be used for tracing and correlating requests and responses.
     * Optional field. If not provided, the system will generate a new UUID.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * ```
     * Unique identifier for this payment request. Can be used for tracing and correlating requests and responses.
     * Optional field. If not provided, the system will generate a new UUID.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    public val PayRequestKt.Dsl.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
      get() = _builder.idOrNull

    /**
     * ```
     * Start a new payment process.
     * ```
     *
     * `.api.v1.PayStart start = 2 [json_name = "start"];`
     */
    public var start: com.senbax.senvend.proto.api.v1.PayStart
      @kotlin.jvm.JvmName("getStart")
        get() = _builder.start
      @kotlin.jvm.JvmName("setStart")
        set(value) {
        _builder.start = value
      }
    /**
     * ```
     * Start a new payment process.
     * ```
     *
     * `.api.v1.PayStart start = 2 [json_name = "start"];`
     */
    public fun clearStart() {
      _builder.clearStart()
    }
    /**
     * ```
     * Start a new payment process.
     * ```
     *
     * `.api.v1.PayStart start = 2 [json_name = "start"];`
     * @return Whether the start field is set.
     */
    public fun hasStart(): kotlin.Boolean {
      return _builder.hasStart()
    }

    /**
     * ```
     * Cancel an ongoing payment process (possibly reimbursing the payment).
     * ```
     *
     * `.api.v1.PayCancel cancel = 3 [json_name = "cancel"];`
     */
    public var cancel: com.senbax.senvend.proto.api.v1.PayCancel
      @kotlin.jvm.JvmName("getCancel")
        get() = _builder.cancel
      @kotlin.jvm.JvmName("setCancel")
        set(value) {
        _builder.cancel = value
      }
    /**
     * ```
     * Cancel an ongoing payment process (possibly reimbursing the payment).
     * ```
     *
     * `.api.v1.PayCancel cancel = 3 [json_name = "cancel"];`
     */
    public fun clearCancel() {
      _builder.clearCancel()
    }
    /**
     * ```
     * Cancel an ongoing payment process (possibly reimbursing the payment).
     * ```
     *
     * `.api.v1.PayCancel cancel = 3 [json_name = "cancel"];`
     * @return Whether the cancel field is set.
     */
    public fun hasCancel(): kotlin.Boolean {
      return _builder.hasCancel()
    }

    /**
     * ```
     * Signify that goods were issued (i.e. payment will NOT be reimbursed).
     * ```
     *
     * `.api.v1.PayGoodsIssued goods_issued = 4 [json_name = "goodsIssued"];`
     */
    public var goodsIssued: com.senbax.senvend.proto.api.v1.PayGoodsIssued
      @kotlin.jvm.JvmName("getGoodsIssued")
        get() = _builder.goodsIssued
      @kotlin.jvm.JvmName("setGoodsIssued")
        set(value) {
        _builder.goodsIssued = value
      }
    /**
     * ```
     * Signify that goods were issued (i.e. payment will NOT be reimbursed).
     * ```
     *
     * `.api.v1.PayGoodsIssued goods_issued = 4 [json_name = "goodsIssued"];`
     */
    public fun clearGoodsIssued() {
      _builder.clearGoodsIssued()
    }
    /**
     * ```
     * Signify that goods were issued (i.e. payment will NOT be reimbursed).
     * ```
     *
     * `.api.v1.PayGoodsIssued goods_issued = 4 [json_name = "goodsIssued"];`
     * @return Whether the goodsIssued field is set.
     */
    public fun hasGoodsIssued(): kotlin.Boolean {
      return _builder.hasGoodsIssued()
    }

    /**
     * ```
     * Mark an ongoing age verification process as successful. (Cancel without error)
     * ```
     *
     * `.api.v1.AgeApproveRequest age_approve = 5 [json_name = "ageApprove"];`
     */
    public var ageApprove: com.senbax.senvend.proto.api.v1.AgeApproveRequest
      @kotlin.jvm.JvmName("getAgeApprove")
        get() = _builder.ageApprove
      @kotlin.jvm.JvmName("setAgeApprove")
        set(value) {
        _builder.ageApprove = value
      }
    /**
     * ```
     * Mark an ongoing age verification process as successful. (Cancel without error)
     * ```
     *
     * `.api.v1.AgeApproveRequest age_approve = 5 [json_name = "ageApprove"];`
     */
    public fun clearAgeApprove() {
      _builder.clearAgeApprove()
    }
    /**
     * ```
     * Mark an ongoing age verification process as successful. (Cancel without error)
     * ```
     *
     * `.api.v1.AgeApproveRequest age_approve = 5 [json_name = "ageApprove"];`
     * @return Whether the ageApprove field is set.
     */
    public fun hasAgeApprove(): kotlin.Boolean {
      return _builder.hasAgeApprove()
    }

    /**
     * ```
     * Update payment amounts during an ongoing payment.
     * ```
     *
     * `.api.v1.PayUpdate update = 6 [json_name = "update"];`
     */
    public var update: com.senbax.senvend.proto.api.v1.PayUpdate
      @kotlin.jvm.JvmName("getUpdate")
        get() = _builder.update
      @kotlin.jvm.JvmName("setUpdate")
        set(value) {
        _builder.update = value
      }
    /**
     * ```
     * Update payment amounts during an ongoing payment.
     * ```
     *
     * `.api.v1.PayUpdate update = 6 [json_name = "update"];`
     */
    public fun clearUpdate() {
      _builder.clearUpdate()
    }
    /**
     * ```
     * Update payment amounts during an ongoing payment.
     * ```
     *
     * `.api.v1.PayUpdate update = 6 [json_name = "update"];`
     * @return Whether the update field is set.
     */
    public fun hasUpdate(): kotlin.Boolean {
      return _builder.hasUpdate()
    }

    /**
     * ```
     * Vend items after APPROVED but before GOODS_ISSUED, or when no payment process is running.
     * ```
     *
     * `.api.v1.VendStart vend = 7 [json_name = "vend"];`
     */
    public var vend: com.senbax.senvend.proto.api.v1.VendStart
      @kotlin.jvm.JvmName("getVend")
        get() = _builder.vend
      @kotlin.jvm.JvmName("setVend")
        set(value) {
        _builder.vend = value
      }
    /**
     * ```
     * Vend items after APPROVED but before GOODS_ISSUED, or when no payment process is running.
     * ```
     *
     * `.api.v1.VendStart vend = 7 [json_name = "vend"];`
     */
    public fun clearVend() {
      _builder.clearVend()
    }
    /**
     * ```
     * Vend items after APPROVED but before GOODS_ISSUED, or when no payment process is running.
     * ```
     *
     * `.api.v1.VendStart vend = 7 [json_name = "vend"];`
     * @return Whether the vend field is set.
     */
    public fun hasVend(): kotlin.Boolean {
      return _builder.hasVend()
    }

    /**
     * ```
     * Cancel a previously started vending process.
     * ```
     *
     * `.api.v1.VendCancel vend_cancel = 8 [json_name = "vendCancel"];`
     */
    public var vendCancel: com.senbax.senvend.proto.api.v1.VendCancel
      @kotlin.jvm.JvmName("getVendCancel")
        get() = _builder.vendCancel
      @kotlin.jvm.JvmName("setVendCancel")
        set(value) {
        _builder.vendCancel = value
      }
    /**
     * ```
     * Cancel a previously started vending process.
     * ```
     *
     * `.api.v1.VendCancel vend_cancel = 8 [json_name = "vendCancel"];`
     */
    public fun clearVendCancel() {
      _builder.clearVendCancel()
    }
    /**
     * ```
     * Cancel a previously started vending process.
     * ```
     *
     * `.api.v1.VendCancel vend_cancel = 8 [json_name = "vendCancel"];`
     * @return Whether the vendCancel field is set.
     */
    public fun hasVendCancel(): kotlin.Boolean {
      return _builder.hasVendCancel()
    }
    public val requestCase: com.senbax.senvend.proto.api.v1.PayRequest.RequestCase
    @kotlin.jvm.JvmName("getRequestCase")
      get() = _builder.getRequestCase()

    public fun clearRequest() {
      _builder.clearRequest()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.PayRequest.copy(block: `com.senbax.senvend.proto.api.v1`.PayRequestKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayRequest =
  `com.senbax.senvend.proto.api.v1`.PayRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
  get() = if (hasId()) getId() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.startOrNull: com.senbax.senvend.proto.api.v1.PayStart?
  get() = if (hasStart()) getStart() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.cancelOrNull: com.senbax.senvend.proto.api.v1.PayCancel?
  get() = if (hasCancel()) getCancel() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.goodsIssuedOrNull: com.senbax.senvend.proto.api.v1.PayGoodsIssued?
  get() = if (hasGoodsIssued()) getGoodsIssued() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.ageApproveOrNull: com.senbax.senvend.proto.api.v1.AgeApproveRequest?
  get() = if (hasAgeApprove()) getAgeApprove() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.updateOrNull: com.senbax.senvend.proto.api.v1.PayUpdate?
  get() = if (hasUpdate()) getUpdate() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.vendOrNull: com.senbax.senvend.proto.api.v1.VendStart?
  get() = if (hasVend()) getVend() else null

public val com.senbax.senvend.proto.api.v1.PayRequestOrBuilder.vendCancelOrNull: com.senbax.senvend.proto.api.v1.VendCancel?
  get() = if (hasVendCancel()) getVendCancel() else null

