// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializepayResponse")
public inline fun payResponse(block: com.senbax.senvend.proto.api.v1.PayResponseKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayResponse =
  com.senbax.senvend.proto.api.v1.PayResponseKt.Dsl._create(com.senbax.senvend.proto.api.v1.PayResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Response to a PayRequest.
 * PaySuccess and PayFailure are final states, they indicate the end of the payment process.
 * ```
 *
 * Protobuf type `api.v1.PayResponse`
 */
public object PayResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.PayResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.PayResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.PayResponse = _builder.build()

    /**
     * ```
     * Unique identifier for the payment request. Mirrors the ID from the PayRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public var id: com.senbax.senvend.proto.api.v1.Uuid4
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Unique identifier for the payment request. Mirrors the ID from the PayRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * ```
     * Unique identifier for the payment request. Mirrors the ID from the PayRequest.
     * This field is always populated, either with the provided ID from the request or a newly generated one.
     * ```
     *
     * `.api.v1.Uuid4 id = 1 [json_name = "id"];`
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    public val PayResponseKt.Dsl.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
      get() = _builder.idOrNull

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApproved approved = 2 [json_name = "approved"];`
     */
    public var approved: com.senbax.senvend.proto.api.v1.PayApproved
      @kotlin.jvm.JvmName("getApproved")
        get() = _builder.approved
      @kotlin.jvm.JvmName("setApproved")
        set(value) {
        _builder.approved = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApproved approved = 2 [json_name = "approved"];`
     */
    public fun clearApproved() {
      _builder.clearApproved()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApproved approved = 2 [json_name = "approved"];`
     * @return Whether the approved field is set.
     */
    public fun hasApproved(): kotlin.Boolean {
      return _builder.hasApproved()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PaySuccess success = 3 [json_name = "success"];`
     */
    public var success: com.senbax.senvend.proto.api.v1.PaySuccess
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PaySuccess success = 3 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PaySuccess success = 3 [json_name = "success"];`
     * @return Whether the success field is set.
     */
    public fun hasSuccess(): kotlin.Boolean {
      return _builder.hasSuccess()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayFailure failure = 4 [json_name = "failure"];`
     */
    public var failure: com.senbax.senvend.proto.api.v1.PayFailure
      @kotlin.jvm.JvmName("getFailure")
        get() = _builder.failure
      @kotlin.jvm.JvmName("setFailure")
        set(value) {
        _builder.failure = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayFailure failure = 4 [json_name = "failure"];`
     */
    public fun clearFailure() {
      _builder.clearFailure()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayFailure failure = 4 [json_name = "failure"];`
     * @return Whether the failure field is set.
     */
    public fun hasFailure(): kotlin.Boolean {
      return _builder.hasFailure()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayApiFailure api_failure = 5 [json_name = "apiFailure"];`
     */
    public var apiFailure: com.senbax.senvend.proto.api.v1.PayApiFailure
      @kotlin.jvm.JvmName("getApiFailure")
        get() = _builder.apiFailure
      @kotlin.jvm.JvmName("setApiFailure")
        set(value) {
        _builder.apiFailure = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayApiFailure api_failure = 5 [json_name = "apiFailure"];`
     */
    public fun clearApiFailure() {
      _builder.clearApiFailure()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.PayApiFailure api_failure = 5 [json_name = "apiFailure"];`
     * @return Whether the apiFailure field is set.
     */
    public fun hasApiFailure(): kotlin.Boolean {
      return _builder.hasApiFailure()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApiSuccess api_success = 6 [json_name = "apiSuccess"];`
     */
    public var apiSuccess: com.senbax.senvend.proto.api.v1.PayApiSuccess
      @kotlin.jvm.JvmName("getApiSuccess")
        get() = _builder.apiSuccess
      @kotlin.jvm.JvmName("setApiSuccess")
        set(value) {
        _builder.apiSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApiSuccess api_success = 6 [json_name = "apiSuccess"];`
     */
    public fun clearApiSuccess() {
      _builder.clearApiSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.PayApiSuccess api_success = 6 [json_name = "apiSuccess"];`
     * @return Whether the apiSuccess field is set.
     */
    public fun hasApiSuccess(): kotlin.Boolean {
      return _builder.hasApiSuccess()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeSuccess age_success = 7 [json_name = "ageSuccess"];`
     */
    public var ageSuccess: com.senbax.senvend.proto.api.v1.AgeSuccess
      @kotlin.jvm.JvmName("getAgeSuccess")
        get() = _builder.ageSuccess
      @kotlin.jvm.JvmName("setAgeSuccess")
        set(value) {
        _builder.ageSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeSuccess age_success = 7 [json_name = "ageSuccess"];`
     */
    public fun clearAgeSuccess() {
      _builder.clearAgeSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeSuccess age_success = 7 [json_name = "ageSuccess"];`
     * @return Whether the ageSuccess field is set.
     */
    public fun hasAgeSuccess(): kotlin.Boolean {
      return _builder.hasAgeSuccess()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure age_failure = 8 [json_name = "ageFailure"];`
     */
    public var ageFailure: com.senbax.senvend.proto.api.v1.AgeFailure
      @kotlin.jvm.JvmName("getAgeFailure")
        get() = _builder.ageFailure
      @kotlin.jvm.JvmName("setAgeFailure")
        set(value) {
        _builder.ageFailure = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure age_failure = 8 [json_name = "ageFailure"];`
     */
    public fun clearAgeFailure() {
      _builder.clearAgeFailure()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeFailure age_failure = 8 [json_name = "ageFailure"];`
     * @return Whether the ageFailure field is set.
     */
    public fun hasAgeFailure(): kotlin.Boolean {
      return _builder.hasAgeFailure()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess age_api_success = 9 [json_name = "ageApiSuccess"];`
     */
    public var ageApiSuccess: com.senbax.senvend.proto.api.v1.AgeApiSuccess
      @kotlin.jvm.JvmName("getAgeApiSuccess")
        get() = _builder.ageApiSuccess
      @kotlin.jvm.JvmName("setAgeApiSuccess")
        set(value) {
        _builder.ageApiSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess age_api_success = 9 [json_name = "ageApiSuccess"];`
     */
    public fun clearAgeApiSuccess() {
      _builder.clearAgeApiSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.AgeApiSuccess age_api_success = 9 [json_name = "ageApiSuccess"];`
     * @return Whether the ageApiSuccess field is set.
     */
    public fun hasAgeApiSuccess(): kotlin.Boolean {
      return _builder.hasAgeApiSuccess()
    }

    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeApiFailure age_api_failure = 10 [json_name = "ageApiFailure"];`
     */
    public var ageApiFailure: com.senbax.senvend.proto.api.v1.AgeApiFailure
      @kotlin.jvm.JvmName("getAgeApiFailure")
        get() = _builder.ageApiFailure
      @kotlin.jvm.JvmName("setAgeApiFailure")
        set(value) {
        _builder.ageApiFailure = value
      }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeApiFailure age_api_failure = 10 [json_name = "ageApiFailure"];`
     */
    public fun clearAgeApiFailure() {
      _builder.clearAgeApiFailure()
    }
    /**
     * ```
     * final state
     * ```
     *
     * `.api.v1.AgeApiFailure age_api_failure = 10 [json_name = "ageApiFailure"];`
     * @return Whether the ageApiFailure field is set.
     */
    public fun hasAgeApiFailure(): kotlin.Boolean {
      return _builder.hasAgeApiFailure()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendEvent vend_event = 11 [json_name = "vendEvent"];`
     */
    public var vendEvent: com.senbax.senvend.proto.api.v1.VendEvent
      @kotlin.jvm.JvmName("getVendEvent")
        get() = _builder.vendEvent
      @kotlin.jvm.JvmName("setVendEvent")
        set(value) {
        _builder.vendEvent = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendEvent vend_event = 11 [json_name = "vendEvent"];`
     */
    public fun clearVendEvent() {
      _builder.clearVendEvent()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendEvent vend_event = 11 [json_name = "vendEvent"];`
     * @return Whether the vendEvent field is set.
     */
    public fun hasVendEvent(): kotlin.Boolean {
      return _builder.hasVendEvent()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiSuccess vend_api_success = 12 [json_name = "vendApiSuccess"];`
     */
    public var vendApiSuccess: com.senbax.senvend.proto.api.v1.VendApiSuccess
      @kotlin.jvm.JvmName("getVendApiSuccess")
        get() = _builder.vendApiSuccess
      @kotlin.jvm.JvmName("setVendApiSuccess")
        set(value) {
        _builder.vendApiSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiSuccess vend_api_success = 12 [json_name = "vendApiSuccess"];`
     */
    public fun clearVendApiSuccess() {
      _builder.clearVendApiSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiSuccess vend_api_success = 12 [json_name = "vendApiSuccess"];`
     * @return Whether the vendApiSuccess field is set.
     */
    public fun hasVendApiSuccess(): kotlin.Boolean {
      return _builder.hasVendApiSuccess()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiFailure vend_api_failure = 13 [json_name = "vendApiFailure"];`
     */
    public var vendApiFailure: com.senbax.senvend.proto.api.v1.VendApiFailure
      @kotlin.jvm.JvmName("getVendApiFailure")
        get() = _builder.vendApiFailure
      @kotlin.jvm.JvmName("setVendApiFailure")
        set(value) {
        _builder.vendApiFailure = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiFailure vend_api_failure = 13 [json_name = "vendApiFailure"];`
     */
    public fun clearVendApiFailure() {
      _builder.clearVendApiFailure()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendApiFailure vend_api_failure = 13 [json_name = "vendApiFailure"];`
     * @return Whether the vendApiFailure field is set.
     */
    public fun hasVendApiFailure(): kotlin.Boolean {
      return _builder.hasVendApiFailure()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_success = 14 [json_name = "vendSuccess"];`
     */
    public var vendSuccess: com.senbax.senvend.proto.api.v1.VendResult
      @kotlin.jvm.JvmName("getVendSuccess")
        get() = _builder.vendSuccess
      @kotlin.jvm.JvmName("setVendSuccess")
        set(value) {
        _builder.vendSuccess = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_success = 14 [json_name = "vendSuccess"];`
     */
    public fun clearVendSuccess() {
      _builder.clearVendSuccess()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_success = 14 [json_name = "vendSuccess"];`
     * @return Whether the vendSuccess field is set.
     */
    public fun hasVendSuccess(): kotlin.Boolean {
      return _builder.hasVendSuccess()
    }

    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_failure = 15 [json_name = "vendFailure"];`
     */
    public var vendFailure: com.senbax.senvend.proto.api.v1.VendResult
      @kotlin.jvm.JvmName("getVendFailure")
        get() = _builder.vendFailure
      @kotlin.jvm.JvmName("setVendFailure")
        set(value) {
        _builder.vendFailure = value
      }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_failure = 15 [json_name = "vendFailure"];`
     */
    public fun clearVendFailure() {
      _builder.clearVendFailure()
    }
    /**
     * ```
     * transient state
     * ```
     *
     * `.api.v1.VendResult vend_failure = 15 [json_name = "vendFailure"];`
     * @return Whether the vendFailure field is set.
     */
    public fun hasVendFailure(): kotlin.Boolean {
      return _builder.hasVendFailure()
    }
    public val resultCase: com.senbax.senvend.proto.api.v1.PayResponse.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.PayResponse.copy(block: `com.senbax.senvend.proto.api.v1`.PayResponseKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayResponse =
  `com.senbax.senvend.proto.api.v1`.PayResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.idOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
  get() = if (hasId()) getId() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.approvedOrNull: com.senbax.senvend.proto.api.v1.PayApproved?
  get() = if (hasApproved()) getApproved() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.successOrNull: com.senbax.senvend.proto.api.v1.PaySuccess?
  get() = if (hasSuccess()) getSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.failureOrNull: com.senbax.senvend.proto.api.v1.PayFailure?
  get() = if (hasFailure()) getFailure() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.apiFailureOrNull: com.senbax.senvend.proto.api.v1.PayApiFailure?
  get() = if (hasApiFailure()) getApiFailure() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.apiSuccessOrNull: com.senbax.senvend.proto.api.v1.PayApiSuccess?
  get() = if (hasApiSuccess()) getApiSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.ageSuccessOrNull: com.senbax.senvend.proto.api.v1.AgeSuccess?
  get() = if (hasAgeSuccess()) getAgeSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.ageFailureOrNull: com.senbax.senvend.proto.api.v1.AgeFailure?
  get() = if (hasAgeFailure()) getAgeFailure() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.ageApiSuccessOrNull: com.senbax.senvend.proto.api.v1.AgeApiSuccess?
  get() = if (hasAgeApiSuccess()) getAgeApiSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.ageApiFailureOrNull: com.senbax.senvend.proto.api.v1.AgeApiFailure?
  get() = if (hasAgeApiFailure()) getAgeApiFailure() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.vendEventOrNull: com.senbax.senvend.proto.api.v1.VendEvent?
  get() = if (hasVendEvent()) getVendEvent() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.vendApiSuccessOrNull: com.senbax.senvend.proto.api.v1.VendApiSuccess?
  get() = if (hasVendApiSuccess()) getVendApiSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.vendApiFailureOrNull: com.senbax.senvend.proto.api.v1.VendApiFailure?
  get() = if (hasVendApiFailure()) getVendApiFailure() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.vendSuccessOrNull: com.senbax.senvend.proto.api.v1.VendResult?
  get() = if (hasVendSuccess()) getVendSuccess() else null

public val com.senbax.senvend.proto.api.v1.PayResponseOrBuilder.vendFailureOrNull: com.senbax.senvend.proto.api.v1.VendResult?
  get() = if (hasVendFailure()) getVendFailure() else null

