// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializepayStart")
public inline fun payStart(block: com.senbax.senvend.proto.api.v1.PayStartKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayStart =
  com.senbax.senvend.proto.api.v1.PayStartKt.Dsl._create(com.senbax.senvend.proto.api.v1.PayStart.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Starts a payment process on the SENVEND Terminal.
 * If auto_cancel is given and false, it can only be executed after a previous process finished with either PayFailure or PaySuccess.
 * Will result in a PAY_FAILURE_REASON_PAYMENT_ONGOING or PAY_FAILURE_REASON_INVALID_STATE otherwise.
 * Without auto_cancel or if it is true, will automatically cancel any running request and then try to start this one.
 * ```
 *
 * Protobuf type `api.v1.PayStart`
 */
public object PayStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.PayStart.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.PayStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.PayStart = _builder.build()

    /**
     * ```
     * The amount to be paid, in cents.
     * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
     * ```
     *
     * `uint32 amount = 1 [json_name = "amount"];`
     */
    public var amount: kotlin.Int
      @kotlin.jvm.JvmName("getAmount")
        get() = _builder.amount
      @kotlin.jvm.JvmName("setAmount")
        set(value) {
        _builder.amount = value
      }
    /**
     * ```
     * The amount to be paid, in cents.
     * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
     * ```
     *
     * `uint32 amount = 1 [json_name = "amount"];`
     */
    public fun clearAmount() {
      _builder.clearAmount()
    }

    /**
     * ```
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * ```
     *
     * `.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];`
     */
    public var ageVerification: com.senbax.senvend.proto.api.v1.AgeStartRequest
      @kotlin.jvm.JvmName("getAgeVerification")
        get() = _builder.ageVerification
      @kotlin.jvm.JvmName("setAgeVerification")
        set(value) {
        _builder.ageVerification = value
      }
    /**
     * ```
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * ```
     *
     * `.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];`
     */
    public fun clearAgeVerification() {
      _builder.clearAgeVerification()
    }
    /**
     * ```
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * ```
     *
     * `.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];`
     * @return Whether the ageVerification field is set.
     */
    public fun hasAgeVerification(): kotlin.Boolean {
      return _builder.hasAgeVerification()
    }

    public val PayStartKt.Dsl.ageVerificationOrNull: com.senbax.senvend.proto.api.v1.AgeStartRequest?
      get() = _builder.ageVerificationOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LineItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     */
     public val lineItems: com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.lineItemsList
      )
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     * @param value The lineItems to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addLineItems")
    public fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.add(value: com.senbax.senvend.proto.api.v1.LineItem) {
      _builder.addLineItems(value)
    }
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     * @param value The lineItems to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignLineItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.plusAssign(value: com.senbax.senvend.proto.api.v1.LineItem) {
      add(value)
    }
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     * @param values The lineItems to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllLineItems")
    public fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.addAll(values: kotlin.collections.Iterable<com.senbax.senvend.proto.api.v1.LineItem>) {
      _builder.addAllLineItems(values)
    }
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     * @param values The lineItems to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllLineItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.plusAssign(values: kotlin.collections.Iterable<com.senbax.senvend.proto.api.v1.LineItem>) {
      addAll(values)
    }
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     * @param index The index to set the value at.
     * @param value The lineItems to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLineItems")
    public operator fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.set(index: kotlin.Int, value: com.senbax.senvend.proto.api.v1.LineItem) {
      _builder.setLineItems(index, value)
    }
    /**
     * ```
     * Optional - the list of individual invoice positions this payment is meant for.
     * ```
     *
     * `repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearLineItems")
    public fun com.google.protobuf.kotlin.DslList<com.senbax.senvend.proto.api.v1.LineItem, LineItemsProxy>.clear() {
      _builder.clearLineItems()
    }

    /**
     * ```
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * ```
     *
     * `optional uint32 cash_amount = 4 [json_name = "cashAmount"];`
     */
    public var cashAmount: kotlin.Int
      @kotlin.jvm.JvmName("getCashAmount")
        get() = _builder.cashAmount
      @kotlin.jvm.JvmName("setCashAmount")
        set(value) {
        _builder.cashAmount = value
      }
    /**
     * ```
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * ```
     *
     * `optional uint32 cash_amount = 4 [json_name = "cashAmount"];`
     */
    public fun clearCashAmount() {
      _builder.clearCashAmount()
    }
    /**
     * ```
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * ```
     *
     * `optional uint32 cash_amount = 4 [json_name = "cashAmount"];`
     * @return Whether the cashAmount field is set.
     */
    public fun hasCashAmount(): kotlin.Boolean {
      return _builder.hasCashAmount()
    }

    /**
     * ```
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * ```
     *
     * `optional bool auto_cancel = 5 [json_name = "autoCancel"];`
     */
    public var autoCancel: kotlin.Boolean
      @kotlin.jvm.JvmName("getAutoCancel")
        get() = _builder.autoCancel
      @kotlin.jvm.JvmName("setAutoCancel")
        set(value) {
        _builder.autoCancel = value
      }
    /**
     * ```
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * ```
     *
     * `optional bool auto_cancel = 5 [json_name = "autoCancel"];`
     */
    public fun clearAutoCancel() {
      _builder.clearAutoCancel()
    }
    /**
     * ```
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * ```
     *
     * `optional bool auto_cancel = 5 [json_name = "autoCancel"];`
     * @return Whether the autoCancel field is set.
     */
    public fun hasAutoCancel(): kotlin.Boolean {
      return _builder.hasAutoCancel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.PayStart.copy(block: `com.senbax.senvend.proto.api.v1`.PayStartKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.PayStart =
  `com.senbax.senvend.proto.api.v1`.PayStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.PayStartOrBuilder.ageVerificationOrNull: com.senbax.senvend.proto.api.v1.AgeStartRequest?
  get() = if (hasAgeVerification()) getAgeVerification() else null

