// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializesemanticVersion")
public inline fun semanticVersion(block: com.senbax.senvend.proto.api.v1.SemanticVersionKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.SemanticVersion =
  com.senbax.senvend.proto.api.v1.SemanticVersionKt.Dsl._create(com.senbax.senvend.proto.api.v1.SemanticVersion.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Represents a semantic version.
 * https://semver.org/
 * ```
 *
 * Protobuf type `api.v1.SemanticVersion`
 */
public object SemanticVersionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.SemanticVersion.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.SemanticVersion.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.SemanticVersion = _builder.build()

    /**
     * ```
     * Major version.
     * ```
     *
     * `uint32 major = 1 [json_name = "major"];`
     */
    public var major: kotlin.Int
      @kotlin.jvm.JvmName("getMajor")
        get() = _builder.major
      @kotlin.jvm.JvmName("setMajor")
        set(value) {
        _builder.major = value
      }
    /**
     * ```
     * Major version.
     * ```
     *
     * `uint32 major = 1 [json_name = "major"];`
     */
    public fun clearMajor() {
      _builder.clearMajor()
    }

    /**
     * ```
     * Minor version.
     * ```
     *
     * `uint32 minor = 2 [json_name = "minor"];`
     */
    public var minor: kotlin.Int
      @kotlin.jvm.JvmName("getMinor")
        get() = _builder.minor
      @kotlin.jvm.JvmName("setMinor")
        set(value) {
        _builder.minor = value
      }
    /**
     * ```
     * Minor version.
     * ```
     *
     * `uint32 minor = 2 [json_name = "minor"];`
     */
    public fun clearMinor() {
      _builder.clearMinor()
    }

    /**
     * ```
     * Patch version.
     * ```
     *
     * `uint32 patch = 3 [json_name = "patch"];`
     */
    public var patch: kotlin.Int
      @kotlin.jvm.JvmName("getPatch")
        get() = _builder.patch
      @kotlin.jvm.JvmName("setPatch")
        set(value) {
        _builder.patch = value
      }
    /**
     * ```
     * Patch version.
     * ```
     *
     * `uint32 patch = 3 [json_name = "patch"];`
     */
    public fun clearPatch() {
      _builder.clearPatch()
    }

    /**
     * ```
     * Only set in non-release versions, in release versions it is left empty.
     * ```
     *
     * `optional string branch = 4 [json_name = "branch"];`
     */
    public var branch: kotlin.String
      @kotlin.jvm.JvmName("getBranch")
        get() = _builder.branch
      @kotlin.jvm.JvmName("setBranch")
        set(value) {
        _builder.branch = value
      }
    /**
     * ```
     * Only set in non-release versions, in release versions it is left empty.
     * ```
     *
     * `optional string branch = 4 [json_name = "branch"];`
     */
    public fun clearBranch() {
      _builder.clearBranch()
    }
    /**
     * ```
     * Only set in non-release versions, in release versions it is left empty.
     * ```
     *
     * `optional string branch = 4 [json_name = "branch"];`
     * @return Whether the branch field is set.
     */
    public fun hasBranch(): kotlin.Boolean {
      return _builder.hasBranch()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.SemanticVersion.copy(block: `com.senbax.senvend.proto.api.v1`.SemanticVersionKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.SemanticVersion =
  `com.senbax.senvend.proto.api.v1`.SemanticVersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

