// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializeuuid4")
public inline fun uuid4(block: com.senbax.senvend.proto.api.v1.Uuid4Kt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.Uuid4 =
  com.senbax.senvend.proto.api.v1.Uuid4Kt.Dsl._create(com.senbax.senvend.proto.api.v1.Uuid4.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Represents a UUID version 4.
 * ```
 *
 * Protobuf type `api.v1.Uuid4`
 */
public object Uuid4Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.Uuid4.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.Uuid4.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.Uuid4 = _builder.build()

    /**
     * ```
     * Most significant bits.
     * ```
     *
     * `uint64 msb = 2 [json_name = "msb"];`
     */
    public var msb: kotlin.Long
      @kotlin.jvm.JvmName("getMsb")
        get() = _builder.msb
      @kotlin.jvm.JvmName("setMsb")
        set(value) {
        _builder.msb = value
      }
    /**
     * ```
     * Most significant bits.
     * ```
     *
     * `uint64 msb = 2 [json_name = "msb"];`
     */
    public fun clearMsb() {
      _builder.clearMsb()
    }

    /**
     * ```
     * Least significant bits.
     * ```
     *
     * `uint64 lsb = 3 [json_name = "lsb"];`
     */
    public var lsb: kotlin.Long
      @kotlin.jvm.JvmName("getLsb")
        get() = _builder.lsb
      @kotlin.jvm.JvmName("setLsb")
        set(value) {
        _builder.lsb = value
      }
    /**
     * ```
     * Least significant bits.
     * ```
     *
     * `uint64 lsb = 3 [json_name = "lsb"];`
     */
    public fun clearLsb() {
      _builder.clearLsb()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.Uuid4.copy(block: `com.senbax.senvend.proto.api.v1`.Uuid4Kt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.Uuid4 =
  `com.senbax.senvend.proto.api.v1`.Uuid4Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

