// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializevendSuccess")
public inline fun vendSuccess(block: com.senbax.senvend.proto.api.v1.VendSuccessKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendSuccess =
  com.senbax.senvend.proto.api.v1.VendSuccessKt.Dsl._create(com.senbax.senvend.proto.api.v1.VendSuccess.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Indicates that the items were successfully vended.
 * ```
 *
 * Protobuf type `api.v1.VendSuccess`
 */
public object VendSuccessKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.VendSuccess.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.VendSuccess.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.VendSuccess = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.VendSuccess.copy(block: `com.senbax.senvend.proto.api.v1`.VendSuccessKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendSuccess =
  `com.senbax.senvend.proto.api.v1`.VendSuccessKt.Dsl._create(this.toBuilder()).apply { block() }._build()

