// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializevendCancel")
public inline fun vendCancel(block: com.senbax.senvend.proto.api.v1.VendCancelKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendCancel =
  com.senbax.senvend.proto.api.v1.VendCancelKt.Dsl._create(com.senbax.senvend.proto.api.v1.VendCancel.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Cancels an ongoing vending process on the SENVEND Terminal.
 * Can be sent at any time, but will result in VEND_API_FAILURE_REASON_UUID_NOT_FOUND
 * if there is nothing to cancel.
 * If sent in a VendRequest without UUID, will cancel any running process without UUID check. (Catch all)
 * ```
 *
 * Protobuf type `api.v1.VendCancel`
 */
public object VendCancelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.VendCancel.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.VendCancel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.VendCancel = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.VendCancel.copy(block: `com.senbax.senvend.proto.api.v1`.VendCancelKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendCancel =
  `com.senbax.senvend.proto.api.v1`.VendCancelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

