// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializevendApiSuccess")
public inline fun vendApiSuccess(block: com.senbax.senvend.proto.api.v1.VendApiSuccessKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendApiSuccess =
  com.senbax.senvend.proto.api.v1.VendApiSuccessKt.Dsl._create(com.senbax.senvend.proto.api.v1.VendApiSuccess.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Indicates a successfully executed request.
 * ```
 *
 * Protobuf type `api.v1.VendApiSuccess`
 */
public object VendApiSuccessKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.VendApiSuccess.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.VendApiSuccess.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.VendApiSuccess = _builder.build()

    /**
     * `.api.v1.VendApiSuccessReason reason = 1 [json_name = "reason"];`
     */
    public var reason: com.senbax.senvend.proto.api.v1.VendApiSuccessReason
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    public var reasonValue: kotlin.Int
      @kotlin.jvm.JvmName("getReasonValue")
        get() = _builder.reasonValue
      @kotlin.jvm.JvmName("setReasonValue")
        set(value) {
        _builder.reasonValue = value
      }
    /**
     * `.api.v1.VendApiSuccessReason reason = 1 [json_name = "reason"];`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.VendApiSuccess.copy(block: `com.senbax.senvend.proto.api.v1`.VendApiSuccessKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendApiSuccess =
  `com.senbax.senvend.proto.api.v1`.VendApiSuccessKt.Dsl._create(this.toBuilder()).apply { block() }._build()

