// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.api.v1;

@kotlin.jvm.JvmName("-initializevendEvent")
public inline fun vendEvent(block: com.senbax.senvend.proto.api.v1.VendEventKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendEvent =
  com.senbax.senvend.proto.api.v1.VendEventKt.Dsl._create(com.senbax.senvend.proto.api.v1.VendEvent.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * VendEvent will be sent for each individual item that was vended, indicating failure or success.
 * ```
 *
 * Protobuf type `api.v1.VendEvent`
 */
public object VendEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.api.v1.VendEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.api.v1.VendEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.api.v1.VendEvent = _builder.build()

    /**
     * ```
     * The vending attempt was successful.
     * ```
     *
     * `.api.v1.VendSuccess success = 1 [json_name = "success"];`
     */
    public var success: com.senbax.senvend.proto.api.v1.VendSuccess
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * ```
     * The vending attempt was successful.
     * ```
     *
     * `.api.v1.VendSuccess success = 1 [json_name = "success"];`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
    /**
     * ```
     * The vending attempt was successful.
     * ```
     *
     * `.api.v1.VendSuccess success = 1 [json_name = "success"];`
     * @return Whether the success field is set.
     */
    public fun hasSuccess(): kotlin.Boolean {
      return _builder.hasSuccess()
    }

    /**
     * ```
     * At least one item failed to vend.
     * ```
     *
     * `.api.v1.VendFailure failure = 2 [json_name = "failure"];`
     */
    public var failure: com.senbax.senvend.proto.api.v1.VendFailure
      @kotlin.jvm.JvmName("getFailure")
        get() = _builder.failure
      @kotlin.jvm.JvmName("setFailure")
        set(value) {
        _builder.failure = value
      }
    /**
     * ```
     * At least one item failed to vend.
     * ```
     *
     * `.api.v1.VendFailure failure = 2 [json_name = "failure"];`
     */
    public fun clearFailure() {
      _builder.clearFailure()
    }
    /**
     * ```
     * At least one item failed to vend.
     * ```
     *
     * `.api.v1.VendFailure failure = 2 [json_name = "failure"];`
     * @return Whether the failure field is set.
     */
    public fun hasFailure(): kotlin.Boolean {
      return _builder.hasFailure()
    }

    /**
     * ```
     * The line_item this status is for
     * ```
     *
     * `.api.v1.LineItem line_item = 3 [json_name = "lineItem"];`
     */
    public var lineItem: com.senbax.senvend.proto.api.v1.LineItem
      @kotlin.jvm.JvmName("getLineItem")
        get() = _builder.lineItem
      @kotlin.jvm.JvmName("setLineItem")
        set(value) {
        _builder.lineItem = value
      }
    /**
     * ```
     * The line_item this status is for
     * ```
     *
     * `.api.v1.LineItem line_item = 3 [json_name = "lineItem"];`
     */
    public fun clearLineItem() {
      _builder.clearLineItem()
    }
    /**
     * ```
     * The line_item this status is for
     * ```
     *
     * `.api.v1.LineItem line_item = 3 [json_name = "lineItem"];`
     * @return Whether the lineItem field is set.
     */
    public fun hasLineItem(): kotlin.Boolean {
      return _builder.hasLineItem()
    }

    public val VendEventKt.Dsl.lineItemOrNull: com.senbax.senvend.proto.api.v1.LineItem?
      get() = _builder.lineItemOrNull
    public val resultCase: com.senbax.senvend.proto.api.v1.VendEvent.ResultCase
    @kotlin.jvm.JvmName("getResultCase")
      get() = _builder.getResultCase()

    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.api.v1.VendEvent.copy(block: `com.senbax.senvend.proto.api.v1`.VendEventKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.api.v1.VendEvent =
  `com.senbax.senvend.proto.api.v1`.VendEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.api.v1.VendEventOrBuilder.successOrNull: com.senbax.senvend.proto.api.v1.VendSuccess?
  get() = if (hasSuccess()) getSuccess() else null

public val com.senbax.senvend.proto.api.v1.VendEventOrBuilder.failureOrNull: com.senbax.senvend.proto.api.v1.VendFailure?
  get() = if (hasFailure()) getFailure() else null

public val com.senbax.senvend.proto.api.v1.VendEventOrBuilder.lineItemOrNull: com.senbax.senvend.proto.api.v1.LineItem?
  get() = if (hasLineItem()) getLineItem() else null

