// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/age.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

/**
 * <pre>
 *
 * If age verification failed because of the determined age.
 * Contains the age determined.
 * </pre>
 *
 * Protobuf type {@code api.v1.AgeFailureUnderage}
 */
@com.google.protobuf.Generated
public final class AgeFailureUnderage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.AgeFailureUnderage)
    AgeFailureUnderageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "AgeFailureUnderage");
  }
  // Use AgeFailureUnderage.newBuilder() to construct.
  private AgeFailureUnderage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AgeFailureUnderage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.api.v1.AgeFailureUnderage.class, com.senbax.senvend.proto.api.v1.AgeFailureUnderage.Builder.class);
  }

  private int bitField0_;
  public static final int DETERMINED_AGE_FIELD_NUMBER = 1;
  private int determinedAge_ = 0;
  /**
   * <pre>
   * The age that was determined during the verification process.
   * May be empty since not all verification methods do return an actual value,
   * only if the threshold was met.
   * </pre>
   *
   * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
   * @return Whether the determinedAge field is set.
   */
  @java.lang.Override
  public boolean hasDeterminedAge() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The age that was determined during the verification process.
   * May be empty since not all verification methods do return an actual value,
   * only if the threshold was met.
   * </pre>
   *
   * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
   * @return The determinedAge.
   */
  @java.lang.Override
  public int getDeterminedAge() {
    return determinedAge_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, determinedAge_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, determinedAge_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.api.v1.AgeFailureUnderage)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.api.v1.AgeFailureUnderage other = (com.senbax.senvend.proto.api.v1.AgeFailureUnderage) obj;

    if (hasDeterminedAge() != other.hasDeterminedAge()) return false;
    if (hasDeterminedAge()) {
      if (getDeterminedAge()
          != other.getDeterminedAge()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDeterminedAge()) {
      hash = (37 * hash) + DETERMINED_AGE_FIELD_NUMBER;
      hash = (53 * hash) + getDeterminedAge();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.api.v1.AgeFailureUnderage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   * If age verification failed because of the determined age.
   * Contains the age determined.
   * </pre>
   *
   * Protobuf type {@code api.v1.AgeFailureUnderage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.AgeFailureUnderage)
      com.senbax.senvend.proto.api.v1.AgeFailureUnderageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.api.v1.AgeFailureUnderage.class, com.senbax.senvend.proto.api.v1.AgeFailureUnderage.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.api.v1.AgeFailureUnderage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      determinedAge_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.api.v1.AgeProto.internal_static_api_v1_AgeFailureUnderage_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.AgeFailureUnderage getDefaultInstanceForType() {
      return com.senbax.senvend.proto.api.v1.AgeFailureUnderage.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.AgeFailureUnderage build() {
      com.senbax.senvend.proto.api.v1.AgeFailureUnderage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.AgeFailureUnderage buildPartial() {
      com.senbax.senvend.proto.api.v1.AgeFailureUnderage result = new com.senbax.senvend.proto.api.v1.AgeFailureUnderage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.senbax.senvend.proto.api.v1.AgeFailureUnderage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.determinedAge_ = determinedAge_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.api.v1.AgeFailureUnderage) {
        return mergeFrom((com.senbax.senvend.proto.api.v1.AgeFailureUnderage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.api.v1.AgeFailureUnderage other) {
      if (other == com.senbax.senvend.proto.api.v1.AgeFailureUnderage.getDefaultInstance()) return this;
      if (other.hasDeterminedAge()) {
        setDeterminedAge(other.getDeterminedAge());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              determinedAge_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int determinedAge_ ;
    /**
     * <pre>
     * The age that was determined during the verification process.
     * May be empty since not all verification methods do return an actual value,
     * only if the threshold was met.
     * </pre>
     *
     * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
     * @return Whether the determinedAge field is set.
     */
    @java.lang.Override
    public boolean hasDeterminedAge() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The age that was determined during the verification process.
     * May be empty since not all verification methods do return an actual value,
     * only if the threshold was met.
     * </pre>
     *
     * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
     * @return The determinedAge.
     */
    @java.lang.Override
    public int getDeterminedAge() {
      return determinedAge_;
    }
    /**
     * <pre>
     * The age that was determined during the verification process.
     * May be empty since not all verification methods do return an actual value,
     * only if the threshold was met.
     * </pre>
     *
     * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
     * @param value The determinedAge to set.
     * @return This builder for chaining.
     */
    public Builder setDeterminedAge(int value) {

      determinedAge_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The age that was determined during the verification process.
     * May be empty since not all verification methods do return an actual value,
     * only if the threshold was met.
     * </pre>
     *
     * <code>optional uint32 determined_age = 1 [json_name = "determinedAge"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeterminedAge() {
      bitField0_ = (bitField0_ & ~0x00000001);
      determinedAge_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.AgeFailureUnderage)
  }

  // @@protoc_insertion_point(class_scope:api.v1.AgeFailureUnderage)
  private static final com.senbax.senvend.proto.api.v1.AgeFailureUnderage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.api.v1.AgeFailureUnderage();
  }

  public static com.senbax.senvend.proto.api.v1.AgeFailureUnderage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgeFailureUnderage>
      PARSER = new com.google.protobuf.AbstractParser<AgeFailureUnderage>() {
    @java.lang.Override
    public AgeFailureUnderage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgeFailureUnderage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgeFailureUnderage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.AgeFailureUnderage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

