// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/age.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public final class AgeProto extends com.google.protobuf.GeneratedFile {
  private AgeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "AgeProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeStartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeStartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeCancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeCancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeApproveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeApproveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeFailureUnderage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeFailureUnderage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeFailure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeFailure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeApiFailure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeApiFailure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_AgeApiSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_AgeApiSuccess_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020api/v1/age.proto\022\006api.v1\032\023api/v1/commo" +
      "n.proto\"\322\001\n\nAgeRequest\022\035\n\002id\030\001 \001(\0132\r.api" +
      ".v1.Uuid4R\002id\022/\n\005start\030\002 \001(\0132\027.api.v1.Ag" +
      "eStartRequestH\000R\005start\0222\n\006cancel\030\003 \001(\0132\030" +
      ".api.v1.AgeCancelRequestH\000R\006cancel\0225\n\007ap" +
      "prove\030\004 \001(\0132\031.api.v1.AgeApproveRequestH\000" +
      "R\007approveB\t\n\007request\"`\n\017AgeStartRequest\022" +
      "\027\n\007min_age\030\001 \001(\rR\006minAge\022$\n\013auto_cancel\030" +
      "\002 \001(\010H\000R\nautoCancel\210\001\001B\016\n\014_auto_cancel\"\022" +
      "\n\020AgeCancelRequest\";\n\021AgeApproveRequest\022" +
      "\033\n\006reason\030\001 \001(\tH\000R\006reason\210\001\001B\t\n\007_reason\"" +
      "\212\002\n\013AgeResponse\022\035\n\002id\030\001 \001(\0132\r.api.v1.Uui" +
      "d4R\002id\022.\n\007success\030\002 \001(\0132\022.api.v1.AgeSucc" +
      "essH\000R\007success\022.\n\007failure\030\003 \001(\0132\022.api.v1" +
      ".AgeFailureH\000R\007failure\0228\n\013api_success\030\004 " +
      "\001(\0132\025.api.v1.AgeApiSuccessH\000R\napiSuccess" +
      "\0228\n\013api_failure\030\005 \001(\0132\025.api.v1.AgeApiFai" +
      "lureH\000R\napiFailureB\010\n\006result\"\014\n\nAgeSucce" +
      "ss\"S\n\022AgeFailureUnderage\022*\n\016determined_a" +
      "ge\030\001 \001(\rH\000R\rdeterminedAge\210\001\001B\021\n\017_determi" +
      "ned_age\"\224\001\n\nAgeFailure\022A\n\016failure_reason" +
      "\030\001 \001(\0162\030.api.v1.AgeFailureReasonH\000R\rfail" +
      "ureReason\0229\n\tunder_age\030\002 \001(\0132\032.api.v1.Ag" +
      "eFailureUnderageH\000R\010underAgeB\010\n\006reason\"D" +
      "\n\rAgeApiFailure\0223\n\006reason\030\001 \001(\0162\033.api.v1" +
      ".AgeApiFailureReasonR\006reason\"D\n\rAgeApiSu" +
      "ccess\0223\n\006reason\030\001 \001(\0162\033.api.v1.AgeApiSuc" +
      "cessReasonR\006reason*\312\002\n\020AgeFailureReason\022" +
      "\"\n\036AGE_FAILURE_REASON_UNSPECIFIED\020\000\022%\n!A" +
      "GE_FAILURE_REASON_USER_CANCELLED\020\001\022\036\n\032AG" +
      "E_FAILURE_REASON_TIMEOUT\020\002\022+\n\'AGE_FAILUR" +
      "E_REASON_VERIFICATION_ONGOING\020\003\022$\n AGE_F" +
      "AILURE_REASON_INVALID_STATE\020\004\022$\n AGE_FAI" +
      "LURE_REASON_API_CANCELLED\020\005\022#\n\037AGE_FAILU" +
      "RE_REASON_INVALID_UUID\020\006\022-\n)AGE_FAILURE_" +
      "REASON_NO_APPLICABLE_PROVIDER\020\007*\346\001\n\023AgeA" +
      "piFailureReason\022&\n\"AGE_API_FAILURE_REASO" +
      "N_UNSPECIFIED\020\000\022&\n\"AGE_API_FAILURE_REASO" +
      "N_INVALID_AGE\020\001\022(\n$AGE_API_FAILURE_REASO" +
      "N_CANCEL_FAILED\020\002\022)\n%AGE_API_FAILURE_REA" +
      "SON_UUID_NOT_FOUND\020\003\022*\n&AGE_API_FAILURE_" +
      "REASON_UNKNOWN_COMMAND\020\004*\307\001\n\023AgeApiSucce" +
      "ssReason\022&\n\"AGE_API_SUCCESS_REASON_UNSPE" +
      "CIFIED\020\000\022/\n+AGE_API_SUCCESS_REASON_VERIF" +
      "ICATION_STARTED\020\001\022*\n&AGE_API_SUCCESS_REA" +
      "SON_CANCEL_ACCEPTED\020\002\022+\n\'AGE_API_SUCCESS" +
      "_REASON_APPROVE_ACCEPTED\020\003Bd\n\037com.senbax" +
      ".senvend.proto.api.v1B\010AgeProtoP\001\242\002\003AXX\252" +
      "\002\006Api.V1\312\002\006Api\\V1\342\002\022Api\\V1\\GPBMetadata\352\002" +
      "\007Api::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.senbax.senvend.proto.api.v1.CommonProto.getDescriptor(),
        });
    internal_static_api_v1_AgeRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_api_v1_AgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeRequest_descriptor,
        new java.lang.String[] { "Id", "Start", "Cancel", "Approve", "Request", });
    internal_static_api_v1_AgeStartRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_api_v1_AgeStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeStartRequest_descriptor,
        new java.lang.String[] { "MinAge", "AutoCancel", });
    internal_static_api_v1_AgeCancelRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_api_v1_AgeCancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeCancelRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1_AgeApproveRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_api_v1_AgeApproveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeApproveRequest_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_api_v1_AgeResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_api_v1_AgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeResponse_descriptor,
        new java.lang.String[] { "Id", "Success", "Failure", "ApiSuccess", "ApiFailure", "Result", });
    internal_static_api_v1_AgeSuccess_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_api_v1_AgeSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeSuccess_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1_AgeFailureUnderage_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_api_v1_AgeFailureUnderage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeFailureUnderage_descriptor,
        new java.lang.String[] { "DeterminedAge", });
    internal_static_api_v1_AgeFailure_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_api_v1_AgeFailure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeFailure_descriptor,
        new java.lang.String[] { "FailureReason", "UnderAge", "Reason", });
    internal_static_api_v1_AgeApiFailure_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_api_v1_AgeApiFailure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeApiFailure_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_api_v1_AgeApiSuccess_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_api_v1_AgeApiSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_AgeApiSuccess_descriptor,
        new java.lang.String[] { "Reason", });
    descriptor.resolveAllFeaturesImmutable();
    com.senbax.senvend.proto.api.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
