// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public final class CommonProto extends com.google.protobuf.GeneratedFile {
  private CommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CommonProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Uuid4_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Uuid4_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_SemanticVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_SemanticVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_Selection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_Selection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_LineItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_api_v1_LineItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023api/v1/common.proto\022\006api.v1\"1\n\005Uuid4\022\020" +
      "\n\003msb\030\002 \001(\004R\003msb\022\020\n\003lsb\030\003 \001(\004R\003lsbJ\004\010\001\020\002" +
      "\"{\n\017SemanticVersion\022\024\n\005major\030\001 \001(\rR\005majo" +
      "r\022\024\n\005minor\030\002 \001(\rR\005minor\022\024\n\005patch\030\003 \001(\rR\005" +
      "patch\022\033\n\006branch\030\004 \001(\tH\000R\006branch\210\001\001B\t\n\007_b" +
      "ranch\"\037\n\tSelection\022\022\n\004slot\030\001 \001(\rR\004slot\"\211" +
      "\001\n\010LineItem\022\031\n\005price\030\001 \001(\rH\001R\005price\210\001\001\022\032" +
      "\n\010quantity\030\002 \001(\rR\010quantity\0221\n\tselection\030" +
      "\003 \001(\0132\021.api.v1.SelectionH\000R\tselectionB\t\n" +
      "\007productB\010\n\006_price*\336\006\n\030MdbSelectionDenie" +
      "dReason\022+\n\'MDB_SELECTION_DENIED_REASON_U" +
      "NSPECIFIED\020\000\022:\n6MDB_SELECTION_DENIED_REA" +
      "SON_UNKNOWN_ERROR_OUT_OF_ORDER\020\001\022G\nCMDB_" +
      "SELECTION_DENIED_REASON_SELECTION_DOES_N" +
      "OT_EXIST_NOT_CONFIGURED\020\002\022=\n9MDB_SELECTI" +
      "ON_DENIED_REASON_SELECTION_EMPTY_NOT_DIS" +
      "PENSED\020\003\0223\n/MDB_SELECTION_DENIED_REASON_" +
      "SELECTION_DEFECTIVE\020\004\0222\n.MDB_SELECTION_D" +
      "ENIED_REASON_INGREDIENT_IS_OVER\020\005\0221\n-MDB" +
      "_SELECTION_DENIED_REASON_SELECTION_BLOCK" +
      "ED\020\006\0223\n/MDB_SELECTION_DENIED_REASON_SELE" +
      "CTION_INHIBITED\020\007\022/\n+MDB_SELECTION_DENIE" +
      "D_REASON_PRODUCT_EXPIRED\020\010\022C\n?MDB_SELECT" +
      "ION_DENIED_REASON_TEMPERATURE_CONDITIONS" +
      "_OUT_OF_RANGE\020\t\022:\n6MDB_SELECTION_DENIED_" +
      "REASON_MACHINE_BUSY_OR_WRONG_MODE\020\n\0223\n/M" +
      "DB_SELECTION_DENIED_REASON_INSUFFICIENT_" +
      "CREDIT\020\013\0226\n2MDB_SELECTION_DENIED_REASON_" +
      "MACHINE_TEMPORARY_BUSY\020\014\0222\n.MDB_SELECTIO" +
      "N_DENIED_REASON_MAX_RETRY_EXCEEDED\020\r\022-\n)" +
      "MDB_SELECTION_DENIED_REASON_UNKNOWN_ERRO" +
      "R\020\016*\263\005\n\024MdbVendFailureReason\022\'\n#MDB_VEND" +
      "_FAILURE_REASON_UNSPECIFIED\020\000\0220\n,MDB_VEN" +
      "D_FAILURE_REASON_UNKNOWN_OUT_OF_ORDER\020\001\022" +
      "C\n?MDB_VEND_FAILURE_REASON_SELECTION_DOE" +
      "S_NOT_EXIST_NOT_CONFIGURED\020\002\022A\n=MDB_VEND" +
      "_FAILURE_REASON_SELECTION_EMPTY_PRODUCT_" +
      "NOT_DISPENSED\020\003\022/\n+MDB_VEND_FAILURE_REAS" +
      "ON_SELECTION_DEFECTIVE\020\004\022.\n*MDB_VEND_FAI" +
      "LURE_REASON_INGREDIENT_IS_OVER\020\005\022-\n)MDB_" +
      "VEND_FAILURE_REASON_SELECTION_BLOCKED\020\006\022" +
      "/\n+MDB_VEND_FAILURE_REASON_SELECTION_INH" +
      "IBITED\020\007\022+\n\'MDB_VEND_FAILURE_REASON_PROD" +
      "UCT_EXPIRED\020\010\022?\n;MDB_VEND_FAILURE_REASON" +
      "_TEMPERATURE_CONDITIONS_OUT_OF_RANGE\020\t\0223" +
      "\n/MDB_VEND_FAILURE_REASON_MACHINE_BUSY_W" +
      "RONG_MODE\020\n\022/\n+MDB_VEND_FAILURE_REASON_I" +
      "NSUFFICIENT_CREDIT\020\013\022#\n\037MDB_VEND_FAILURE" +
      "_REASON_UNKNOWN\020\014Bg\n\037com.senbax.senvend." +
      "proto.api.v1B\013CommonProtoP\001\242\002\003AXX\252\002\006Api." +
      "V1\312\002\006Api\\V1\342\002\022Api\\V1\\GPBMetadata\352\002\007Api::" +
      "V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_v1_Uuid4_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_api_v1_Uuid4_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Uuid4_descriptor,
        new java.lang.String[] { "Msb", "Lsb", });
    internal_static_api_v1_SemanticVersion_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_api_v1_SemanticVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_SemanticVersion_descriptor,
        new java.lang.String[] { "Major", "Minor", "Patch", "Branch", });
    internal_static_api_v1_Selection_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_api_v1_Selection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_Selection_descriptor,
        new java.lang.String[] { "Slot", });
    internal_static_api_v1_LineItem_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_api_v1_LineItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_api_v1_LineItem_descriptor,
        new java.lang.String[] { "Price", "Quantity", "Selection", "Product", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
