// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

/**
 * <pre>
 *
 * The actual API usage error.
 * </pre>
 *
 * Protobuf enum {@code api.v1.PayApiFailureReason}
 */
@com.google.protobuf.Generated
public enum PayApiFailureReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Unspecified reason. Protocol reserved, do not use.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UNSPECIFIED = 0;</code>
   */
  PAY_API_FAILURE_REASON_UNSPECIFIED(0),
  /**
   * <pre>
   * The provided payment amount is invalid.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_AMOUNT = 1;</code>
   */
  PAY_API_FAILURE_REASON_INVALID_AMOUNT(1),
  /**
   * <pre>
   * A cancel failed or there was nothing to cancel
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_CANCEL_FAILED = 2;</code>
   */
  PAY_API_FAILURE_REASON_CANCEL_FAILED(2),
  /**
   * <pre>
   * No request for this UUID found (could already be finished or cancelled).
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UUID_NOT_FOUND = 3;</code>
   */
  PAY_API_FAILURE_REASON_UUID_NOT_FOUND(3),
  /**
   * <pre>
   * The command inside PayRequest is unknown to the API (i.e. mismatching proto versions).
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;</code>
   */
  PAY_API_FAILURE_REASON_UNKNOWN_COMMAND(4),
  /**
   * <pre>
   * A PayGoodsIssued request was sent before a payment was started or approved.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT = 5;</code>
   */
  PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT(5),
  /**
   * <pre>
   * If a list of LineItem entries is given, but the sum of their prices (times quantity) does not match the given total or partial amount.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_AMOUNT_MISMATCH = 6;</code>
   */
  PAY_API_FAILURE_REASON_AMOUNT_MISMATCH(6),
  /**
   * <pre>
   * If a given UUID is not a valid v4 UUID
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_UUID = 7;</code>
   */
  PAY_API_FAILURE_REASON_INVALID_UUID(7),
  /**
   * <pre>
   * If a command inside PayRequest was sent during a state in which it cannot be accepted.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_STATE = 8;</code>
   */
  PAY_API_FAILURE_REASON_INVALID_STATE(8),
  /**
   * <pre>
   * The payment is already approved and can no longer be updated.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_ALREADY_APPROVED = 9;</code>
   */
  PAY_API_FAILURE_REASON_ALREADY_APPROVED(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "PayApiFailureReason");
  }
  /**
   * <pre>
   * Unspecified reason. Protocol reserved, do not use.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int PAY_API_FAILURE_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * The provided payment amount is invalid.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_AMOUNT = 1;</code>
   */
  public static final int PAY_API_FAILURE_REASON_INVALID_AMOUNT_VALUE = 1;
  /**
   * <pre>
   * A cancel failed or there was nothing to cancel
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_CANCEL_FAILED = 2;</code>
   */
  public static final int PAY_API_FAILURE_REASON_CANCEL_FAILED_VALUE = 2;
  /**
   * <pre>
   * No request for this UUID found (could already be finished or cancelled).
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UUID_NOT_FOUND = 3;</code>
   */
  public static final int PAY_API_FAILURE_REASON_UUID_NOT_FOUND_VALUE = 3;
  /**
   * <pre>
   * The command inside PayRequest is unknown to the API (i.e. mismatching proto versions).
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;</code>
   */
  public static final int PAY_API_FAILURE_REASON_UNKNOWN_COMMAND_VALUE = 4;
  /**
   * <pre>
   * A PayGoodsIssued request was sent before a payment was started or approved.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT = 5;</code>
   */
  public static final int PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT_VALUE = 5;
  /**
   * <pre>
   * If a list of LineItem entries is given, but the sum of their prices (times quantity) does not match the given total or partial amount.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_AMOUNT_MISMATCH = 6;</code>
   */
  public static final int PAY_API_FAILURE_REASON_AMOUNT_MISMATCH_VALUE = 6;
  /**
   * <pre>
   * If a given UUID is not a valid v4 UUID
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_UUID = 7;</code>
   */
  public static final int PAY_API_FAILURE_REASON_INVALID_UUID_VALUE = 7;
  /**
   * <pre>
   * If a command inside PayRequest was sent during a state in which it cannot be accepted.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_INVALID_STATE = 8;</code>
   */
  public static final int PAY_API_FAILURE_REASON_INVALID_STATE_VALUE = 8;
  /**
   * <pre>
   * The payment is already approved and can no longer be updated.
   * </pre>
   *
   * <code>PAY_API_FAILURE_REASON_ALREADY_APPROVED = 9;</code>
   */
  public static final int PAY_API_FAILURE_REASON_ALREADY_APPROVED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PayApiFailureReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PayApiFailureReason forNumber(int value) {
    switch (value) {
      case 0: return PAY_API_FAILURE_REASON_UNSPECIFIED;
      case 1: return PAY_API_FAILURE_REASON_INVALID_AMOUNT;
      case 2: return PAY_API_FAILURE_REASON_CANCEL_FAILED;
      case 3: return PAY_API_FAILURE_REASON_UUID_NOT_FOUND;
      case 4: return PAY_API_FAILURE_REASON_UNKNOWN_COMMAND;
      case 5: return PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT;
      case 6: return PAY_API_FAILURE_REASON_AMOUNT_MISMATCH;
      case 7: return PAY_API_FAILURE_REASON_INVALID_UUID;
      case 8: return PAY_API_FAILURE_REASON_INVALID_STATE;
      case 9: return PAY_API_FAILURE_REASON_ALREADY_APPROVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PayApiFailureReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PayApiFailureReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PayApiFailureReason>() {
          public PayApiFailureReason findValueByNumber(int number) {
            return PayApiFailureReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.senbax.senvend.proto.api.v1.PayProto.getDescriptor().getEnumType(1);
  }

  private static final PayApiFailureReason[] VALUES = values();

  public static PayApiFailureReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PayApiFailureReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.v1.PayApiFailureReason)
}

