// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public interface PayApiSuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.PayApiSuccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.v1.PayApiSuccessReason reason = 1 [json_name = "reason"];</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.api.v1.PayApiSuccessReason reason = 1 [json_name = "reason"];</code>
   * @return The reason.
   */
  com.senbax.senvend.proto.api.v1.PayApiSuccessReason getReason();
}
