// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public interface PayApprovedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.PayApproved)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The amount that was actually approved.
   * Useful in case of multiple updates, since the approval might not be for the newest request.
   * </pre>
   *
   * <code>uint32 amount = 1 [json_name = "amount"];</code>
   * @return The amount.
   */
  int getAmount();
}
