// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

/**
 * <pre>
 *
 * Indicates that the payment was successfully debited.
 * Ends the payment process.
 * </pre>
 *
 * Protobuf type {@code api.v1.PaySuccess}
 */
@com.google.protobuf.Generated
public final class PaySuccess extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.PaySuccess)
    PaySuccessOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "PaySuccess");
  }
  // Use PaySuccess.newBuilder() to construct.
  private PaySuccess(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PaySuccess() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.api.v1.PaySuccess.class, com.senbax.senvend.proto.api.v1.PaySuccess.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.api.v1.PaySuccess)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.api.v1.PaySuccess other = (com.senbax.senvend.proto.api.v1.PaySuccess) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.api.v1.PaySuccess parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.api.v1.PaySuccess parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.PaySuccess parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.api.v1.PaySuccess prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   * Indicates that the payment was successfully debited.
   * Ends the payment process.
   * </pre>
   *
   * Protobuf type {@code api.v1.PaySuccess}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.PaySuccess)
      com.senbax.senvend.proto.api.v1.PaySuccessOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.api.v1.PaySuccess.class, com.senbax.senvend.proto.api.v1.PaySuccess.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.api.v1.PaySuccess.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PaySuccess_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PaySuccess getDefaultInstanceForType() {
      return com.senbax.senvend.proto.api.v1.PaySuccess.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PaySuccess build() {
      com.senbax.senvend.proto.api.v1.PaySuccess result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PaySuccess buildPartial() {
      com.senbax.senvend.proto.api.v1.PaySuccess result = new com.senbax.senvend.proto.api.v1.PaySuccess(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.api.v1.PaySuccess) {
        return mergeFrom((com.senbax.senvend.proto.api.v1.PaySuccess)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.api.v1.PaySuccess other) {
      if (other == com.senbax.senvend.proto.api.v1.PaySuccess.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.PaySuccess)
  }

  // @@protoc_insertion_point(class_scope:api.v1.PaySuccess)
  private static final com.senbax.senvend.proto.api.v1.PaySuccess DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.api.v1.PaySuccess();
  }

  public static com.senbax.senvend.proto.api.v1.PaySuccess getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaySuccess>
      PARSER = new com.google.protobuf.AbstractParser<PaySuccess>() {
    @java.lang.Override
    public PaySuccess parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaySuccess> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaySuccess> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.PaySuccess getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

