// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/pay.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

/**
 * <pre>
 *
 * Starts a payment process on the SENVEND terminal.
 * If auto_cancel is given and false, it can only be executed after a previous process finished with either PayFailure or PaySuccess.
 * Will result in a PAY_FAILURE_REASON_PAYMENT_ONGOING or PAY_FAILURE_REASON_INVALID_STATE otherwise.
 * Without auto_cancel or if it is true, will automatically cancel any running request and then try to start this one.
 * </pre>
 *
 * Protobuf type {@code api.v1.PayStart}
 */
@com.google.protobuf.Generated
public final class PayStart extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.v1.PayStart)
    PayStartOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "PayStart");
  }
  // Use PayStart.newBuilder() to construct.
  private PayStart(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PayStart() {
    lineItems_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.api.v1.PayStart.class, com.senbax.senvend.proto.api.v1.PayStart.Builder.class);
  }

  private int bitField0_;
  public static final int AMOUNT_FIELD_NUMBER = 1;
  private int amount_ = 0;
  /**
   * <pre>
   * The amount to be paid, in cents.
   * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
   * </pre>
   *
   * <code>uint32 amount = 1 [json_name = "amount"];</code>
   * @return The amount.
   */
  @java.lang.Override
  public int getAmount() {
    return amount_;
  }

  public static final int AGE_VERIFICATION_FIELD_NUMBER = 2;
  private com.senbax.senvend.proto.api.v1.AgeStartRequest ageVerification_;
  /**
   * <pre>
   * Optional - age verification request to be performed before payment.
   * The value of auto_cancel inside this message will be ignored.
   * </pre>
   *
   * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
   * @return Whether the ageVerification field is set.
   */
  @java.lang.Override
  public boolean hasAgeVerification() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional - age verification request to be performed before payment.
   * The value of auto_cancel inside this message will be ignored.
   * </pre>
   *
   * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
   * @return The ageVerification.
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.AgeStartRequest getAgeVerification() {
    return ageVerification_ == null ? com.senbax.senvend.proto.api.v1.AgeStartRequest.getDefaultInstance() : ageVerification_;
  }
  /**
   * <pre>
   * Optional - age verification request to be performed before payment.
   * The value of auto_cancel inside this message will be ignored.
   * </pre>
   *
   * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.AgeStartRequestOrBuilder getAgeVerificationOrBuilder() {
    return ageVerification_ == null ? com.senbax.senvend.proto.api.v1.AgeStartRequest.getDefaultInstance() : ageVerification_;
  }

  public static final int LINE_ITEMS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.senbax.senvend.proto.api.v1.LineItem> lineItems_;
  /**
   * <pre>
   * Optional - the list of individual invoice positions this payment is meant for.
   * </pre>
   *
   * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
   */
  @java.lang.Override
  public java.util.List<com.senbax.senvend.proto.api.v1.LineItem> getLineItemsList() {
    return lineItems_;
  }
  /**
   * <pre>
   * Optional - the list of individual invoice positions this payment is meant for.
   * </pre>
   *
   * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.senbax.senvend.proto.api.v1.LineItemOrBuilder> 
      getLineItemsOrBuilderList() {
    return lineItems_;
  }
  /**
   * <pre>
   * Optional - the list of individual invoice positions this payment is meant for.
   * </pre>
   *
   * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
   */
  @java.lang.Override
  public int getLineItemsCount() {
    return lineItems_.size();
  }
  /**
   * <pre>
   * Optional - the list of individual invoice positions this payment is meant for.
   * </pre>
   *
   * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.LineItem getLineItems(int index) {
    return lineItems_.get(index);
  }
  /**
   * <pre>
   * Optional - the list of individual invoice positions this payment is meant for.
   * </pre>
   *
   * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.LineItemOrBuilder getLineItemsOrBuilder(
      int index) {
    return lineItems_.get(index);
  }

  public static final int CASH_AMOUNT_FIELD_NUMBER = 4;
  private int cashAmount_ = 0;
  /**
   * <pre>
   * Optional - reporting field for partial cash payment.
   * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
   * but will be checked against line_items.
   * </pre>
   *
   * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
   * @return Whether the cashAmount field is set.
   */
  @java.lang.Override
  public boolean hasCashAmount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Optional - reporting field for partial cash payment.
   * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
   * but will be checked against line_items.
   * </pre>
   *
   * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
   * @return The cashAmount.
   */
  @java.lang.Override
  public int getCashAmount() {
    return cashAmount_;
  }

  public static final int AUTO_CANCEL_FIELD_NUMBER = 5;
  private boolean autoCancel_ = false;
  /**
   * <pre>
   * Optional - indicates if any already running request should be canceled.
   * Defaults to true if left out.
   * </pre>
   *
   * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
   * @return Whether the autoCancel field is set.
   */
  @java.lang.Override
  public boolean hasAutoCancel() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Optional - indicates if any already running request should be canceled.
   * Defaults to true if left out.
   * </pre>
   *
   * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
   * @return The autoCancel.
   */
  @java.lang.Override
  public boolean getAutoCancel() {
    return autoCancel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (amount_ != 0) {
      output.writeUInt32(1, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getAgeVerification());
    }
    for (int i = 0; i < lineItems_.size(); i++) {
      output.writeMessage(3, lineItems_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(4, cashAmount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(5, autoCancel_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (amount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, amount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAgeVerification());
    }

        {
          final int count = lineItems_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(lineItems_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, cashAmount_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, autoCancel_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.api.v1.PayStart)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.api.v1.PayStart other = (com.senbax.senvend.proto.api.v1.PayStart) obj;

    if (getAmount()
        != other.getAmount()) return false;
    if (hasAgeVerification() != other.hasAgeVerification()) return false;
    if (hasAgeVerification()) {
      if (!getAgeVerification()
          .equals(other.getAgeVerification())) return false;
    }
    if (!getLineItemsList()
        .equals(other.getLineItemsList())) return false;
    if (hasCashAmount() != other.hasCashAmount()) return false;
    if (hasCashAmount()) {
      if (getCashAmount()
          != other.getCashAmount()) return false;
    }
    if (hasAutoCancel() != other.hasAutoCancel()) return false;
    if (hasAutoCancel()) {
      if (getAutoCancel()
          != other.getAutoCancel()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount();
    if (hasAgeVerification()) {
      hash = (37 * hash) + AGE_VERIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getAgeVerification().hashCode();
    }
    if (getLineItemsCount() > 0) {
      hash = (37 * hash) + LINE_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getLineItemsList().hashCode();
    }
    if (hasCashAmount()) {
      hash = (37 * hash) + CASH_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCashAmount();
    }
    if (hasAutoCancel()) {
      hash = (37 * hash) + AUTO_CANCEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoCancel());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.api.v1.PayStart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.api.v1.PayStart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.api.v1.PayStart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.api.v1.PayStart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   * Starts a payment process on the SENVEND terminal.
   * If auto_cancel is given and false, it can only be executed after a previous process finished with either PayFailure or PaySuccess.
   * Will result in a PAY_FAILURE_REASON_PAYMENT_ONGOING or PAY_FAILURE_REASON_INVALID_STATE otherwise.
   * Without auto_cancel or if it is true, will automatically cancel any running request and then try to start this one.
   * </pre>
   *
   * Protobuf type {@code api.v1.PayStart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.PayStart)
      com.senbax.senvend.proto.api.v1.PayStartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.api.v1.PayStart.class, com.senbax.senvend.proto.api.v1.PayStart.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.api.v1.PayStart.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetAgeVerificationFieldBuilder();
        internalGetLineItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      amount_ = 0;
      ageVerification_ = null;
      if (ageVerificationBuilder_ != null) {
        ageVerificationBuilder_.dispose();
        ageVerificationBuilder_ = null;
      }
      if (lineItemsBuilder_ == null) {
        lineItems_ = java.util.Collections.emptyList();
      } else {
        lineItems_ = null;
        lineItemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      cashAmount_ = 0;
      autoCancel_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.api.v1.PayProto.internal_static_api_v1_PayStart_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PayStart getDefaultInstanceForType() {
      return com.senbax.senvend.proto.api.v1.PayStart.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PayStart build() {
      com.senbax.senvend.proto.api.v1.PayStart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.PayStart buildPartial() {
      com.senbax.senvend.proto.api.v1.PayStart result = new com.senbax.senvend.proto.api.v1.PayStart(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.senbax.senvend.proto.api.v1.PayStart result) {
      if (lineItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          lineItems_ = java.util.Collections.unmodifiableList(lineItems_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.lineItems_ = lineItems_;
      } else {
        result.lineItems_ = lineItemsBuilder_.build();
      }
    }

    private void buildPartial0(com.senbax.senvend.proto.api.v1.PayStart result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.amount_ = amount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ageVerification_ = ageVerificationBuilder_ == null
            ? ageVerification_
            : ageVerificationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cashAmount_ = cashAmount_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.autoCancel_ = autoCancel_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.api.v1.PayStart) {
        return mergeFrom((com.senbax.senvend.proto.api.v1.PayStart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.api.v1.PayStart other) {
      if (other == com.senbax.senvend.proto.api.v1.PayStart.getDefaultInstance()) return this;
      if (other.getAmount() != 0) {
        setAmount(other.getAmount());
      }
      if (other.hasAgeVerification()) {
        mergeAgeVerification(other.getAgeVerification());
      }
      if (lineItemsBuilder_ == null) {
        if (!other.lineItems_.isEmpty()) {
          if (lineItems_.isEmpty()) {
            lineItems_ = other.lineItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLineItemsIsMutable();
            lineItems_.addAll(other.lineItems_);
          }
          onChanged();
        }
      } else {
        if (!other.lineItems_.isEmpty()) {
          if (lineItemsBuilder_.isEmpty()) {
            lineItemsBuilder_.dispose();
            lineItemsBuilder_ = null;
            lineItems_ = other.lineItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
            lineItemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetLineItemsFieldBuilder() : null;
          } else {
            lineItemsBuilder_.addAllMessages(other.lineItems_);
          }
        }
      }
      if (other.hasCashAmount()) {
        setCashAmount(other.getCashAmount());
      }
      if (other.hasAutoCancel()) {
        setAutoCancel(other.getAutoCancel());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              amount_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetAgeVerificationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.senbax.senvend.proto.api.v1.LineItem m =
                  input.readMessage(
                      com.senbax.senvend.proto.api.v1.LineItem.parser(),
                      extensionRegistry);
              if (lineItemsBuilder_ == null) {
                ensureLineItemsIsMutable();
                lineItems_.add(m);
              } else {
                lineItemsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              cashAmount_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              autoCancel_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int amount_ ;
    /**
     * <pre>
     * The amount to be paid, in cents.
     * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
     * </pre>
     *
     * <code>uint32 amount = 1 [json_name = "amount"];</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * The amount to be paid, in cents.
     * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
     * </pre>
     *
     * <code>uint32 amount = 1 [json_name = "amount"];</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(int value) {

      amount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The amount to be paid, in cents.
     * Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
     * </pre>
     *
     * <code>uint32 amount = 1 [json_name = "amount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      amount_ = 0;
      onChanged();
      return this;
    }

    private com.senbax.senvend.proto.api.v1.AgeStartRequest ageVerification_;
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.AgeStartRequest, com.senbax.senvend.proto.api.v1.AgeStartRequest.Builder, com.senbax.senvend.proto.api.v1.AgeStartRequestOrBuilder> ageVerificationBuilder_;
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     * @return Whether the ageVerification field is set.
     */
    public boolean hasAgeVerification() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     * @return The ageVerification.
     */
    public com.senbax.senvend.proto.api.v1.AgeStartRequest getAgeVerification() {
      if (ageVerificationBuilder_ == null) {
        return ageVerification_ == null ? com.senbax.senvend.proto.api.v1.AgeStartRequest.getDefaultInstance() : ageVerification_;
      } else {
        return ageVerificationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public Builder setAgeVerification(com.senbax.senvend.proto.api.v1.AgeStartRequest value) {
      if (ageVerificationBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ageVerification_ = value;
      } else {
        ageVerificationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public Builder setAgeVerification(
        com.senbax.senvend.proto.api.v1.AgeStartRequest.Builder builderForValue) {
      if (ageVerificationBuilder_ == null) {
        ageVerification_ = builderForValue.build();
      } else {
        ageVerificationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public Builder mergeAgeVerification(com.senbax.senvend.proto.api.v1.AgeStartRequest value) {
      if (ageVerificationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          ageVerification_ != null &&
          ageVerification_ != com.senbax.senvend.proto.api.v1.AgeStartRequest.getDefaultInstance()) {
          getAgeVerificationBuilder().mergeFrom(value);
        } else {
          ageVerification_ = value;
        }
      } else {
        ageVerificationBuilder_.mergeFrom(value);
      }
      if (ageVerification_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public Builder clearAgeVerification() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ageVerification_ = null;
      if (ageVerificationBuilder_ != null) {
        ageVerificationBuilder_.dispose();
        ageVerificationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public com.senbax.senvend.proto.api.v1.AgeStartRequest.Builder getAgeVerificationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetAgeVerificationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    public com.senbax.senvend.proto.api.v1.AgeStartRequestOrBuilder getAgeVerificationOrBuilder() {
      if (ageVerificationBuilder_ != null) {
        return ageVerificationBuilder_.getMessageOrBuilder();
      } else {
        return ageVerification_ == null ?
            com.senbax.senvend.proto.api.v1.AgeStartRequest.getDefaultInstance() : ageVerification_;
      }
    }
    /**
     * <pre>
     * Optional - age verification request to be performed before payment.
     * The value of auto_cancel inside this message will be ignored.
     * </pre>
     *
     * <code>.api.v1.AgeStartRequest age_verification = 2 [json_name = "ageVerification"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.AgeStartRequest, com.senbax.senvend.proto.api.v1.AgeStartRequest.Builder, com.senbax.senvend.proto.api.v1.AgeStartRequestOrBuilder> 
        internalGetAgeVerificationFieldBuilder() {
      if (ageVerificationBuilder_ == null) {
        ageVerificationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.senbax.senvend.proto.api.v1.AgeStartRequest, com.senbax.senvend.proto.api.v1.AgeStartRequest.Builder, com.senbax.senvend.proto.api.v1.AgeStartRequestOrBuilder>(
                getAgeVerification(),
                getParentForChildren(),
                isClean());
        ageVerification_ = null;
      }
      return ageVerificationBuilder_;
    }

    private java.util.List<com.senbax.senvend.proto.api.v1.LineItem> lineItems_ =
      java.util.Collections.emptyList();
    private void ensureLineItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        lineItems_ = new java.util.ArrayList<com.senbax.senvend.proto.api.v1.LineItem>(lineItems_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.senbax.senvend.proto.api.v1.LineItem, com.senbax.senvend.proto.api.v1.LineItem.Builder, com.senbax.senvend.proto.api.v1.LineItemOrBuilder> lineItemsBuilder_;

    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public java.util.List<com.senbax.senvend.proto.api.v1.LineItem> getLineItemsList() {
      if (lineItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lineItems_);
      } else {
        return lineItemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public int getLineItemsCount() {
      if (lineItemsBuilder_ == null) {
        return lineItems_.size();
      } else {
        return lineItemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public com.senbax.senvend.proto.api.v1.LineItem getLineItems(int index) {
      if (lineItemsBuilder_ == null) {
        return lineItems_.get(index);
      } else {
        return lineItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder setLineItems(
        int index, com.senbax.senvend.proto.api.v1.LineItem value) {
      if (lineItemsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureLineItemsIsMutable();
        lineItems_.set(index, value);
        onChanged();
      } else {
        lineItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder setLineItems(
        int index, com.senbax.senvend.proto.api.v1.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder addLineItems(com.senbax.senvend.proto.api.v1.LineItem value) {
      if (lineItemsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureLineItemsIsMutable();
        lineItems_.add(value);
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder addLineItems(
        int index, com.senbax.senvend.proto.api.v1.LineItem value) {
      if (lineItemsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensureLineItemsIsMutable();
        lineItems_.add(index, value);
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder addLineItems(
        com.senbax.senvend.proto.api.v1.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.add(builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder addLineItems(
        int index, com.senbax.senvend.proto.api.v1.LineItem.Builder builderForValue) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        lineItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder addAllLineItems(
        java.lang.Iterable<? extends com.senbax.senvend.proto.api.v1.LineItem> values) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lineItems_);
        onChanged();
      } else {
        lineItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder clearLineItems() {
      if (lineItemsBuilder_ == null) {
        lineItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        lineItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public Builder removeLineItems(int index) {
      if (lineItemsBuilder_ == null) {
        ensureLineItemsIsMutable();
        lineItems_.remove(index);
        onChanged();
      } else {
        lineItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public com.senbax.senvend.proto.api.v1.LineItem.Builder getLineItemsBuilder(
        int index) {
      return internalGetLineItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public com.senbax.senvend.proto.api.v1.LineItemOrBuilder getLineItemsOrBuilder(
        int index) {
      if (lineItemsBuilder_ == null) {
        return lineItems_.get(index);  } else {
        return lineItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public java.util.List<? extends com.senbax.senvend.proto.api.v1.LineItemOrBuilder> 
         getLineItemsOrBuilderList() {
      if (lineItemsBuilder_ != null) {
        return lineItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lineItems_);
      }
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public com.senbax.senvend.proto.api.v1.LineItem.Builder addLineItemsBuilder() {
      return internalGetLineItemsFieldBuilder().addBuilder(
          com.senbax.senvend.proto.api.v1.LineItem.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public com.senbax.senvend.proto.api.v1.LineItem.Builder addLineItemsBuilder(
        int index) {
      return internalGetLineItemsFieldBuilder().addBuilder(
          index, com.senbax.senvend.proto.api.v1.LineItem.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional - the list of individual invoice positions this payment is meant for.
     * </pre>
     *
     * <code>repeated .api.v1.LineItem line_items = 3 [json_name = "lineItems"];</code>
     */
    public java.util.List<com.senbax.senvend.proto.api.v1.LineItem.Builder> 
         getLineItemsBuilderList() {
      return internalGetLineItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.senbax.senvend.proto.api.v1.LineItem, com.senbax.senvend.proto.api.v1.LineItem.Builder, com.senbax.senvend.proto.api.v1.LineItemOrBuilder> 
        internalGetLineItemsFieldBuilder() {
      if (lineItemsBuilder_ == null) {
        lineItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.senbax.senvend.proto.api.v1.LineItem, com.senbax.senvend.proto.api.v1.LineItem.Builder, com.senbax.senvend.proto.api.v1.LineItemOrBuilder>(
                lineItems_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        lineItems_ = null;
      }
      return lineItemsBuilder_;
    }

    private int cashAmount_ ;
    /**
     * <pre>
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * </pre>
     *
     * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
     * @return Whether the cashAmount field is set.
     */
    @java.lang.Override
    public boolean hasCashAmount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * </pre>
     *
     * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
     * @return The cashAmount.
     */
    @java.lang.Override
    public int getCashAmount() {
      return cashAmount_;
    }
    /**
     * <pre>
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * </pre>
     *
     * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
     * @param value The cashAmount to set.
     * @return This builder for chaining.
     */
    public Builder setCashAmount(int value) {

      cashAmount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional - reporting field for partial cash payment.
     * Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
     * but will be checked against line_items.
     * </pre>
     *
     * <code>optional uint32 cash_amount = 4 [json_name = "cashAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCashAmount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cashAmount_ = 0;
      onChanged();
      return this;
    }

    private boolean autoCancel_ ;
    /**
     * <pre>
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * </pre>
     *
     * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
     * @return Whether the autoCancel field is set.
     */
    @java.lang.Override
    public boolean hasAutoCancel() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * </pre>
     *
     * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
     * @return The autoCancel.
     */
    @java.lang.Override
    public boolean getAutoCancel() {
      return autoCancel_;
    }
    /**
     * <pre>
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * </pre>
     *
     * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
     * @param value The autoCancel to set.
     * @return This builder for chaining.
     */
    public Builder setAutoCancel(boolean value) {

      autoCancel_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional - indicates if any already running request should be canceled.
     * Defaults to true if left out.
     * </pre>
     *
     * <code>optional bool auto_cancel = 5 [json_name = "autoCancel"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoCancel() {
      bitField0_ = (bitField0_ & ~0x00000010);
      autoCancel_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.v1.PayStart)
  }

  // @@protoc_insertion_point(class_scope:api.v1.PayStart)
  private static final com.senbax.senvend.proto.api.v1.PayStart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.api.v1.PayStart();
  }

  public static com.senbax.senvend.proto.api.v1.PayStart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayStart>
      PARSER = new com.google.protobuf.AbstractParser<PayStart>() {
    @java.lang.Override
    public PayStart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PayStart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayStart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.PayStart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

