// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/common.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public interface SemanticVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.SemanticVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Major version.
   * </pre>
   *
   * <code>uint32 major = 1 [json_name = "major"];</code>
   * @return The major.
   */
  int getMajor();

  /**
   * <pre>
   * Minor version.
   * </pre>
   *
   * <code>uint32 minor = 2 [json_name = "minor"];</code>
   * @return The minor.
   */
  int getMinor();

  /**
   * <pre>
   * Patch version.
   * </pre>
   *
   * <code>uint32 patch = 3 [json_name = "patch"];</code>
   * @return The patch.
   */
  int getPatch();

  /**
   * <pre>
   * Only set in non-release versions, in release versions it is left empty.
   * </pre>
   *
   * <code>optional string branch = 4 [json_name = "branch"];</code>
   * @return Whether the branch field is set.
   */
  boolean hasBranch();
  /**
   * <pre>
   * Only set in non-release versions, in release versions it is left empty.
   * </pre>
   *
   * <code>optional string branch = 4 [json_name = "branch"];</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <pre>
   * Only set in non-release versions, in release versions it is left empty.
   * </pre>
   *
   * <code>optional string branch = 4 [json_name = "branch"];</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();
}
