// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public interface VendResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.VendResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for the vending request. Mirrors the ID from the VendRequest.
   * This field is always populated, either with the provided ID from the request or a newly generated one.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Unique identifier for the vending request. Mirrors the ID from the VendRequest.
   * This field is always populated, either with the provided ID from the request or a newly generated one.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  com.senbax.senvend.proto.api.v1.Uuid4 getId();
  /**
   * <pre>
   * Unique identifier for the vending request. Mirrors the ID from the VendRequest.
   * This field is always populated, either with the provided ID from the request or a newly generated one.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   */
  com.senbax.senvend.proto.api.v1.Uuid4OrBuilder getIdOrBuilder();

  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendEvent event = 2 [json_name = "event"];</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendEvent event = 2 [json_name = "event"];</code>
   * @return The event.
   */
  com.senbax.senvend.proto.api.v1.VendEvent getEvent();
  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendEvent event = 2 [json_name = "event"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendEventOrBuilder getEventOrBuilder();

  /**
   * <pre>
   * transient/final state
   * An API failure is usually transient as it doesn't end the current process.
   * But it is final if it does not result in a new process with that UUID either.
   * Prime examples are VendStart with an invalid quantity or a VendCancel for an unknown UUID.
   * </pre>
   *
   * <code>.api.v1.VendApiFailure api_failure = 3 [json_name = "apiFailure"];</code>
   * @return Whether the apiFailure field is set.
   */
  boolean hasApiFailure();
  /**
   * <pre>
   * transient/final state
   * An API failure is usually transient as it doesn't end the current process.
   * But it is final if it does not result in a new process with that UUID either.
   * Prime examples are VendStart with an invalid quantity or a VendCancel for an unknown UUID.
   * </pre>
   *
   * <code>.api.v1.VendApiFailure api_failure = 3 [json_name = "apiFailure"];</code>
   * @return The apiFailure.
   */
  com.senbax.senvend.proto.api.v1.VendApiFailure getApiFailure();
  /**
   * <pre>
   * transient/final state
   * An API failure is usually transient as it doesn't end the current process.
   * But it is final if it does not result in a new process with that UUID either.
   * Prime examples are VendStart with an invalid quantity or a VendCancel for an unknown UUID.
   * </pre>
   *
   * <code>.api.v1.VendApiFailure api_failure = 3 [json_name = "apiFailure"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendApiFailureOrBuilder getApiFailureOrBuilder();

  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendApiSuccess api_success = 4 [json_name = "apiSuccess"];</code>
   * @return Whether the apiSuccess field is set.
   */
  boolean hasApiSuccess();
  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendApiSuccess api_success = 4 [json_name = "apiSuccess"];</code>
   * @return The apiSuccess.
   */
  com.senbax.senvend.proto.api.v1.VendApiSuccess getApiSuccess();
  /**
   * <pre>
   * transient state
   * </pre>
   *
   * <code>.api.v1.VendApiSuccess api_success = 4 [json_name = "apiSuccess"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendApiSuccessOrBuilder getApiSuccessOrBuilder();

  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult success = 5 [json_name = "success"];</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult success = 5 [json_name = "success"];</code>
   * @return The success.
   */
  com.senbax.senvend.proto.api.v1.VendResult getSuccess();
  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult success = 5 [json_name = "success"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendResultOrBuilder getSuccessOrBuilder();

  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult failure = 6 [json_name = "failure"];</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult failure = 6 [json_name = "failure"];</code>
   * @return The failure.
   */
  com.senbax.senvend.proto.api.v1.VendResult getFailure();
  /**
   * <pre>
   * final state
   * </pre>
   *
   * <code>.api.v1.VendResult failure = 6 [json_name = "failure"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendResultOrBuilder getFailureOrBuilder();

  com.senbax.senvend.proto.api.v1.VendResponse.ResponseCase getResponseCase();
}
