// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

@com.google.protobuf.Generated
public interface VendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.VendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier for this vend request. Can be used for tracing and correlating requests and responses.
   * Optional field. If not provided, the system will generate a new UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Unique identifier for this vend request. Can be used for tracing and correlating requests and responses.
   * Optional field. If not provided, the system will generate a new UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  com.senbax.senvend.proto.api.v1.Uuid4 getId();
  /**
   * <pre>
   * Unique identifier for this vend request. Can be used for tracing and correlating requests and responses.
   * Optional field. If not provided, the system will generate a new UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 id = 1 [json_name = "id"];</code>
   */
  com.senbax.senvend.proto.api.v1.Uuid4OrBuilder getIdOrBuilder();

  /**
   * <pre>
   * Start a new vending process.
   * </pre>
   *
   * <code>.api.v1.VendStart start = 2 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <pre>
   * Start a new vending process.
   * </pre>
   *
   * <code>.api.v1.VendStart start = 2 [json_name = "start"];</code>
   * @return The start.
   */
  com.senbax.senvend.proto.api.v1.VendStart getStart();
  /**
   * <pre>
   * Start a new vending process.
   * </pre>
   *
   * <code>.api.v1.VendStart start = 2 [json_name = "start"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendStartOrBuilder getStartOrBuilder();

  /**
   * <pre>
   * Cancel an ongoing vend process.
   * </pre>
   *
   * <code>.api.v1.VendCancel cancel = 3 [json_name = "cancel"];</code>
   * @return Whether the cancel field is set.
   */
  boolean hasCancel();
  /**
   * <pre>
   * Cancel an ongoing vend process.
   * </pre>
   *
   * <code>.api.v1.VendCancel cancel = 3 [json_name = "cancel"];</code>
   * @return The cancel.
   */
  com.senbax.senvend.proto.api.v1.VendCancel getCancel();
  /**
   * <pre>
   * Cancel an ongoing vend process.
   * </pre>
   *
   * <code>.api.v1.VendCancel cancel = 3 [json_name = "cancel"];</code>
   */
  com.senbax.senvend.proto.api.v1.VendCancelOrBuilder getCancelOrBuilder();

  com.senbax.senvend.proto.api.v1.VendRequest.RequestCase getRequestCase();
}
