// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/v1/vend.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.api.v1;

/**
 * <pre>
 *
 * The actual API usage error.
 * </pre>
 *
 * Protobuf enum {@code api.v1.VendApiFailureReason}
 */
@com.google.protobuf.Generated
public enum VendApiFailureReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Unspecified reason. Protocol reserved, do not use.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UNSPECIFIED = 0;</code>
   */
  VEND_API_FAILURE_REASON_UNSPECIFIED(0),
  /**
   * <pre>
   * The provided vending quantity is invalid (e.g. zero).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_QUANTITY = 1;</code>
   */
  VEND_API_FAILURE_REASON_INVALID_QUANTITY(1),
  /**
   * <pre>
   * A cancel failed or there was nothing to cancel
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_CANCEL_FAILED = 2;</code>
   */
  VEND_API_FAILURE_REASON_CANCEL_FAILED(2),
  /**
   * <pre>
   * No request for this UUID found (could already be finished or cancelled).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UUID_NOT_FOUND = 3;</code>
   */
  VEND_API_FAILURE_REASON_UUID_NOT_FOUND(3),
  /**
   * <pre>
   * The command inside VendRequest is unknown to the API (i.e. mismatching proto versions).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;</code>
   */
  VEND_API_FAILURE_REASON_UNKNOWN_COMMAND(4),
  /**
   * <pre>
   * If a given UUID is not a valid v4 UUID
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_UUID = 5;</code>
   */
  VEND_API_FAILURE_REASON_INVALID_UUID(5),
  /**
   * <pre>
   * If a command inside VendRequest was sent during a state in which it cannot be accepted.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_STATE = 6;</code>
   */
  VEND_API_FAILURE_REASON_INVALID_STATE(6),
  /**
   * <pre>
   * A vending process is already ongoing.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_VENDING_ONGOING = 7;</code>
   */
  VEND_API_FAILURE_REASON_VENDING_ONGOING(7),
  /**
   * <pre>
   * The config is in a state where vending is not possible (i.e. no remote vend, no always idle etc.)
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_CONFIG = 8;</code>
   */
  VEND_API_FAILURE_REASON_INVALID_CONFIG(8),
  /**
   * <pre>
   * A vend via MDB was requested (Selection), but MDB is disabled.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_MDB_DISABLED = 9;</code>
   */
  VEND_API_FAILURE_REASON_MDB_DISABLED(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "VendApiFailureReason");
  }
  /**
   * <pre>
   * Unspecified reason. Protocol reserved, do not use.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int VEND_API_FAILURE_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * The provided vending quantity is invalid (e.g. zero).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_QUANTITY = 1;</code>
   */
  public static final int VEND_API_FAILURE_REASON_INVALID_QUANTITY_VALUE = 1;
  /**
   * <pre>
   * A cancel failed or there was nothing to cancel
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_CANCEL_FAILED = 2;</code>
   */
  public static final int VEND_API_FAILURE_REASON_CANCEL_FAILED_VALUE = 2;
  /**
   * <pre>
   * No request for this UUID found (could already be finished or cancelled).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UUID_NOT_FOUND = 3;</code>
   */
  public static final int VEND_API_FAILURE_REASON_UUID_NOT_FOUND_VALUE = 3;
  /**
   * <pre>
   * The command inside VendRequest is unknown to the API (i.e. mismatching proto versions).
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;</code>
   */
  public static final int VEND_API_FAILURE_REASON_UNKNOWN_COMMAND_VALUE = 4;
  /**
   * <pre>
   * If a given UUID is not a valid v4 UUID
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_UUID = 5;</code>
   */
  public static final int VEND_API_FAILURE_REASON_INVALID_UUID_VALUE = 5;
  /**
   * <pre>
   * If a command inside VendRequest was sent during a state in which it cannot be accepted.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_STATE = 6;</code>
   */
  public static final int VEND_API_FAILURE_REASON_INVALID_STATE_VALUE = 6;
  /**
   * <pre>
   * A vending process is already ongoing.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_VENDING_ONGOING = 7;</code>
   */
  public static final int VEND_API_FAILURE_REASON_VENDING_ONGOING_VALUE = 7;
  /**
   * <pre>
   * The config is in a state where vending is not possible (i.e. no remote vend, no always idle etc.)
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_INVALID_CONFIG = 8;</code>
   */
  public static final int VEND_API_FAILURE_REASON_INVALID_CONFIG_VALUE = 8;
  /**
   * <pre>
   * A vend via MDB was requested (Selection), but MDB is disabled.
   * </pre>
   *
   * <code>VEND_API_FAILURE_REASON_MDB_DISABLED = 9;</code>
   */
  public static final int VEND_API_FAILURE_REASON_MDB_DISABLED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VendApiFailureReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VendApiFailureReason forNumber(int value) {
    switch (value) {
      case 0: return VEND_API_FAILURE_REASON_UNSPECIFIED;
      case 1: return VEND_API_FAILURE_REASON_INVALID_QUANTITY;
      case 2: return VEND_API_FAILURE_REASON_CANCEL_FAILED;
      case 3: return VEND_API_FAILURE_REASON_UUID_NOT_FOUND;
      case 4: return VEND_API_FAILURE_REASON_UNKNOWN_COMMAND;
      case 5: return VEND_API_FAILURE_REASON_INVALID_UUID;
      case 6: return VEND_API_FAILURE_REASON_INVALID_STATE;
      case 7: return VEND_API_FAILURE_REASON_VENDING_ONGOING;
      case 8: return VEND_API_FAILURE_REASON_INVALID_CONFIG;
      case 9: return VEND_API_FAILURE_REASON_MDB_DISABLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VendApiFailureReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VendApiFailureReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VendApiFailureReason>() {
          public VendApiFailureReason findValueByNumber(int number) {
            return VendApiFailureReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.senbax.senvend.proto.api.v1.VendProto.getDescriptor().getEnumType(1);
  }

  private static final VendApiFailureReason[] VALUES = values();

  public static VendApiFailureReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VendApiFailureReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.v1.VendApiFailureReason)
}

