// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

@com.google.protobuf.Generated
public interface CloudPayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud.v1.CloudPayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   * @return Whether the target field is set.
   */
  boolean hasTarget();
  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   * @return The target.
   */
  com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getTarget();
  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   */
  com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder getTargetOrBuilder();

  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   * @return Whether the payRequest field is set.
   */
  boolean hasPayRequest();
  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   * @return The payRequest.
   */
  com.senbax.senvend.proto.api.v1.PayRequest getPayRequest();
  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   */
  com.senbax.senvend.proto.api.v1.PayRequestOrBuilder getPayRequestOrBuilder();
}
