// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

/**
 * <pre>
 * Provides the current software and API version of the SENVEND Terminal.
 * </pre>
 *
 * Protobuf type {@code cloud.v1.CloudVersionResponse}
 */
@com.google.protobuf.Generated
public final class CloudVersionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cloud.v1.CloudVersionResponse)
    CloudVersionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CloudVersionResponse");
  }
  // Use CloudVersionResponse.newBuilder() to construct.
  private CloudVersionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CloudVersionResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.class, com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_RESPONSE_FIELD_NUMBER = 1;
  private com.senbax.senvend.proto.api.v1.VersionResponse versionResponse_;
  /**
   * <pre>
   * Provides the current software and API version of the SENVEND Terminal.
   * </pre>
   *
   * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
   * @return Whether the versionResponse field is set.
   */
  @java.lang.Override
  public boolean hasVersionResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Provides the current software and API version of the SENVEND Terminal.
   * </pre>
   *
   * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
   * @return The versionResponse.
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.VersionResponse getVersionResponse() {
    return versionResponse_ == null ? com.senbax.senvend.proto.api.v1.VersionResponse.getDefaultInstance() : versionResponse_;
  }
  /**
   * <pre>
   * Provides the current software and API version of the SENVEND Terminal.
   * </pre>
   *
   * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.VersionResponseOrBuilder getVersionResponseOrBuilder() {
    return versionResponse_ == null ? com.senbax.senvend.proto.api.v1.VersionResponse.getDefaultInstance() : versionResponse_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getVersionResponse());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersionResponse());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.cloud.v1.CloudVersionResponse)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.cloud.v1.CloudVersionResponse other = (com.senbax.senvend.proto.cloud.v1.CloudVersionResponse) obj;

    if (hasVersionResponse() != other.hasVersionResponse()) return false;
    if (hasVersionResponse()) {
      if (!getVersionResponse()
          .equals(other.getVersionResponse())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersionResponse()) {
      hash = (37 * hash) + VERSION_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getVersionResponse().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.cloud.v1.CloudVersionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Provides the current software and API version of the SENVEND Terminal.
   * </pre>
   *
   * Protobuf type {@code cloud.v1.CloudVersionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud.v1.CloudVersionResponse)
      com.senbax.senvend.proto.cloud.v1.CloudVersionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.class, com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetVersionResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      versionResponse_ = null;
      if (versionResponseBuilder_ != null) {
        versionResponseBuilder_.dispose();
        versionResponseBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudVersionResponse_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudVersionResponse getDefaultInstanceForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudVersionResponse build() {
      com.senbax.senvend.proto.cloud.v1.CloudVersionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudVersionResponse buildPartial() {
      com.senbax.senvend.proto.cloud.v1.CloudVersionResponse result = new com.senbax.senvend.proto.cloud.v1.CloudVersionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.senbax.senvend.proto.cloud.v1.CloudVersionResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.versionResponse_ = versionResponseBuilder_ == null
            ? versionResponse_
            : versionResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.cloud.v1.CloudVersionResponse) {
        return mergeFrom((com.senbax.senvend.proto.cloud.v1.CloudVersionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.cloud.v1.CloudVersionResponse other) {
      if (other == com.senbax.senvend.proto.cloud.v1.CloudVersionResponse.getDefaultInstance()) return this;
      if (other.hasVersionResponse()) {
        mergeVersionResponse(other.getVersionResponse());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetVersionResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.senbax.senvend.proto.api.v1.VersionResponse versionResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.VersionResponse, com.senbax.senvend.proto.api.v1.VersionResponse.Builder, com.senbax.senvend.proto.api.v1.VersionResponseOrBuilder> versionResponseBuilder_;
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     * @return Whether the versionResponse field is set.
     */
    public boolean hasVersionResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     * @return The versionResponse.
     */
    public com.senbax.senvend.proto.api.v1.VersionResponse getVersionResponse() {
      if (versionResponseBuilder_ == null) {
        return versionResponse_ == null ? com.senbax.senvend.proto.api.v1.VersionResponse.getDefaultInstance() : versionResponse_;
      } else {
        return versionResponseBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public Builder setVersionResponse(com.senbax.senvend.proto.api.v1.VersionResponse value) {
      if (versionResponseBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        versionResponse_ = value;
      } else {
        versionResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public Builder setVersionResponse(
        com.senbax.senvend.proto.api.v1.VersionResponse.Builder builderForValue) {
      if (versionResponseBuilder_ == null) {
        versionResponse_ = builderForValue.build();
      } else {
        versionResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public Builder mergeVersionResponse(com.senbax.senvend.proto.api.v1.VersionResponse value) {
      if (versionResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          versionResponse_ != null &&
          versionResponse_ != com.senbax.senvend.proto.api.v1.VersionResponse.getDefaultInstance()) {
          getVersionResponseBuilder().mergeFrom(value);
        } else {
          versionResponse_ = value;
        }
      } else {
        versionResponseBuilder_.mergeFrom(value);
      }
      if (versionResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public Builder clearVersionResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      versionResponse_ = null;
      if (versionResponseBuilder_ != null) {
        versionResponseBuilder_.dispose();
        versionResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public com.senbax.senvend.proto.api.v1.VersionResponse.Builder getVersionResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetVersionResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    public com.senbax.senvend.proto.api.v1.VersionResponseOrBuilder getVersionResponseOrBuilder() {
      if (versionResponseBuilder_ != null) {
        return versionResponseBuilder_.getMessageOrBuilder();
      } else {
        return versionResponse_ == null ?
            com.senbax.senvend.proto.api.v1.VersionResponse.getDefaultInstance() : versionResponse_;
      }
    }
    /**
     * <pre>
     * Provides the current software and API version of the SENVEND Terminal.
     * </pre>
     *
     * <code>.api.v1.VersionResponse version_response = 1 [json_name = "versionResponse"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.VersionResponse, com.senbax.senvend.proto.api.v1.VersionResponse.Builder, com.senbax.senvend.proto.api.v1.VersionResponseOrBuilder> 
        internalGetVersionResponseFieldBuilder() {
      if (versionResponseBuilder_ == null) {
        versionResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.senbax.senvend.proto.api.v1.VersionResponse, com.senbax.senvend.proto.api.v1.VersionResponse.Builder, com.senbax.senvend.proto.api.v1.VersionResponseOrBuilder>(
                getVersionResponse(),
                getParentForChildren(),
                isClean());
        versionResponse_ = null;
      }
      return versionResponseBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:cloud.v1.CloudVersionResponse)
  }

  // @@protoc_insertion_point(class_scope:cloud.v1.CloudVersionResponse)
  private static final com.senbax.senvend.proto.cloud.v1.CloudVersionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.cloud.v1.CloudVersionResponse();
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudVersionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudVersionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CloudVersionResponse>() {
    @java.lang.Override
    public CloudVersionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloudVersionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudVersionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.cloud.v1.CloudVersionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

