// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

@com.google.protobuf.Generated
public interface CloudPayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud.v1.CloudPayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The payment response from the terminal.
   * </pre>
   *
   * <code>.api.v1.PayResponse pay_response = 1 [json_name = "payResponse"];</code>
   * @return Whether the payResponse field is set.
   */
  boolean hasPayResponse();
  /**
   * <pre>
   * The payment response from the terminal.
   * </pre>
   *
   * <code>.api.v1.PayResponse pay_response = 1 [json_name = "payResponse"];</code>
   * @return The payResponse.
   */
  com.senbax.senvend.proto.api.v1.PayResponse getPayResponse();
  /**
   * <pre>
   * The payment response from the terminal.
   * </pre>
   *
   * <code>.api.v1.PayResponse pay_response = 1 [json_name = "payResponse"];</code>
   */
  com.senbax.senvend.proto.api.v1.PayResponseOrBuilder getPayResponseOrBuilder();
}
