// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

@com.google.protobuf.Generated
public final class CloudProto extends com.google.protobuf.GeneratedFile {
  private CloudProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CloudProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudTargetSelector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudTargetSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudAgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudAgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudAgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudAgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudPayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudPayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudPayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudPayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudVersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudVersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_v1_CloudVersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cloud_v1_CloudVersionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024cloud/v1/cloud.proto\022\010cloud.v1\032\020api/v1" +
      "/age.proto\032\023api/v1/common.proto\032\020api/v1/" +
      "pay.proto\032\024api/v1/version.proto\"x\n\023Cloud" +
      "TargetSelector\022.\n\nmachine_id\030\001 \001(\0132\r.api" +
      ".v1.Uuid4H\000R\tmachineId\022%\n\rserial_number\030" +
      "\002 \001(\tH\000R\014serialNumberB\n\n\010selector\"}\n\017Clo" +
      "udAgeRequest\0225\n\006target\030\001 \001(\0132\035.cloud.v1." +
      "CloudTargetSelectorR\006target\0223\n\013age_reque" +
      "st\030\002 \001(\0132\022.api.v1.AgeRequestR\nageRequest" +
      "\"J\n\020CloudAgeResponse\0226\n\014age_response\030\001 \001" +
      "(\0132\023.api.v1.AgeResponseR\013ageResponse\"}\n\017" +
      "CloudPayRequest\0225\n\006target\030\001 \001(\0132\035.cloud." +
      "v1.CloudTargetSelectorR\006target\0223\n\013pay_re" +
      "quest\030\002 \001(\0132\022.api.v1.PayRequestR\npayRequ" +
      "est\"J\n\020CloudPayResponse\0226\n\014pay_response\030" +
      "\001 \001(\0132\023.api.v1.PayResponseR\013payResponse\"" +
      "\215\001\n\023CloudVersionRequest\0225\n\006target\030\001 \001(\0132" +
      "\035.cloud.v1.CloudTargetSelectorR\006target\022?" +
      "\n\017version_request\030\002 \001(\0132\026.api.v1.Version" +
      "RequestR\016versionRequest\"Z\n\024CloudVersionR" +
      "esponse\022B\n\020version_response\030\001 \001(\0132\027.api." +
      "v1.VersionResponseR\017versionResponse2d\n\033C" +
      "loudAgeVerificationService\022E\n\010CloudAge\022\031" +
      ".cloud.v1.CloudAgeRequest\032\032.cloud.v1.Clo" +
      "udAgeResponse(\0010\0012X\n\017CloudPayService\022E\n\010" +
      "CloudPay\022\031.cloud.v1.CloudPayRequest\032\032.cl" +
      "oud.v1.CloudPayResponse(\0010\0012d\n\023CloudVers" +
      "ionService\022M\n\014CloudVersion\022\035.cloud.v1.Cl" +
      "oudVersionRequest\032\036.cloud.v1.CloudVersio" +
      "nResponseBp\n!com.senbax.senvend.proto.cl" +
      "oud.v1B\nCloudProtoP\001\242\002\003CXX\252\002\010Cloud.V1\312\002\010" +
      "Cloud\\V1\342\002\024Cloud\\V1\\GPBMetadata\352\002\tCloud:" +
      ":V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.senbax.senvend.proto.api.v1.AgeProto.getDescriptor(),
          com.senbax.senvend.proto.api.v1.CommonProto.getDescriptor(),
          com.senbax.senvend.proto.api.v1.PayProto.getDescriptor(),
          com.senbax.senvend.proto.api.v1.VersionProto.getDescriptor(),
        });
    internal_static_cloud_v1_CloudTargetSelector_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_cloud_v1_CloudTargetSelector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudTargetSelector_descriptor,
        new java.lang.String[] { "MachineId", "SerialNumber", "Selector", });
    internal_static_cloud_v1_CloudAgeRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_cloud_v1_CloudAgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudAgeRequest_descriptor,
        new java.lang.String[] { "Target", "AgeRequest", });
    internal_static_cloud_v1_CloudAgeResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_cloud_v1_CloudAgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudAgeResponse_descriptor,
        new java.lang.String[] { "AgeResponse", });
    internal_static_cloud_v1_CloudPayRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_cloud_v1_CloudPayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudPayRequest_descriptor,
        new java.lang.String[] { "Target", "PayRequest", });
    internal_static_cloud_v1_CloudPayResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_cloud_v1_CloudPayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudPayResponse_descriptor,
        new java.lang.String[] { "PayResponse", });
    internal_static_cloud_v1_CloudVersionRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_cloud_v1_CloudVersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudVersionRequest_descriptor,
        new java.lang.String[] { "Target", "VersionRequest", });
    internal_static_cloud_v1_CloudVersionResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_cloud_v1_CloudVersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cloud_v1_CloudVersionResponse_descriptor,
        new java.lang.String[] { "VersionResponse", });
    descriptor.resolveAllFeaturesImmutable();
    com.senbax.senvend.proto.api.v1.AgeProto.getDescriptor();
    com.senbax.senvend.proto.api.v1.CommonProto.getDescriptor();
    com.senbax.senvend.proto.api.v1.PayProto.getDescriptor();
    com.senbax.senvend.proto.api.v1.VersionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
