// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

/**
 * <pre>
 * Identifies the terminal to send messages to.
 * </pre>
 *
 * Protobuf type {@code cloud.v1.CloudTargetSelector}
 */
@com.google.protobuf.Generated
public final class CloudTargetSelector extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cloud.v1.CloudTargetSelector)
    CloudTargetSelectorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CloudTargetSelector");
  }
  // Use CloudTargetSelector.newBuilder() to construct.
  private CloudTargetSelector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CloudTargetSelector() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.class, com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder.class);
  }

  private int selectorCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object selector_;
  public enum SelectorCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MACHINE_ID(1),
    SERIAL_NUMBER(2),
    SELECTOR_NOT_SET(0);
    private final int value;
    private SelectorCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SelectorCase valueOf(int value) {
      return forNumber(value);
    }

    public static SelectorCase forNumber(int value) {
      switch (value) {
        case 1: return MACHINE_ID;
        case 2: return SERIAL_NUMBER;
        case 0: return SELECTOR_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SelectorCase
  getSelectorCase() {
    return SelectorCase.forNumber(
        selectorCase_);
  }

  public static final int MACHINE_ID_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Select by my.senvend.com machine UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
   * @return Whether the machineId field is set.
   */
  @java.lang.Override
  public boolean hasMachineId() {
    return selectorCase_ == 1;
  }
  /**
   * <pre>
   * Select by my.senvend.com machine UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
   * @return The machineId.
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.Uuid4 getMachineId() {
    if (selectorCase_ == 1) {
       return (com.senbax.senvend.proto.api.v1.Uuid4) selector_;
    }
    return com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
  }
  /**
   * <pre>
   * Select by my.senvend.com machine UUID.
   * </pre>
   *
   * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.Uuid4OrBuilder getMachineIdOrBuilder() {
    if (selectorCase_ == 1) {
       return (com.senbax.senvend.proto.api.v1.Uuid4) selector_;
    }
    return com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
  }

  public static final int SERIAL_NUMBER_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Select by SENVEND Terminal serial number.
   * </pre>
   *
   * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
   * @return Whether the serialNumber field is set.
   */
  public boolean hasSerialNumber() {
    return selectorCase_ == 2;
  }
  /**
   * <pre>
   * Select by SENVEND Terminal serial number.
   * </pre>
   *
   * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
   * @return The serialNumber.
   */
  public java.lang.String getSerialNumber() {
    if (selectorCase_ != 2) {
      return "";
    }
    java.lang.Object ref = selector_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      selector_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Select by SENVEND Terminal serial number.
   * </pre>
   *
   * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
   * @return The bytes for serialNumber.
   */
  public com.google.protobuf.ByteString
      getSerialNumberBytes() {
    if (selectorCase_ != 2) {
      return com.google.protobuf.ByteString.copyFromUtf8("");
    }
    java.lang.Object ref = selector_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      selector_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (selectorCase_ == 1) {
      output.writeMessage(1, (com.senbax.senvend.proto.api.v1.Uuid4) selector_);
    }
    if (selectorCase_ == 2) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, selector_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (selectorCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.senbax.senvend.proto.api.v1.Uuid4) selector_);
    }
    if (selectorCase_ == 2) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, selector_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.cloud.v1.CloudTargetSelector)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.cloud.v1.CloudTargetSelector other = (com.senbax.senvend.proto.cloud.v1.CloudTargetSelector) obj;

    if (!getSelectorCase().equals(other.getSelectorCase())) return false;
    switch (selectorCase_) {
      case 1:
        if (!getMachineId()
            .equals(other.getMachineId())) return false;
        break;
      case 2:
        if (!getSerialNumber()
            .equals(other.getSerialNumber())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (selectorCase_) {
      case 1:
        hash = (37 * hash) + MACHINE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMachineId().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getSerialNumber().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Identifies the terminal to send messages to.
   * </pre>
   *
   * Protobuf type {@code cloud.v1.CloudTargetSelector}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud.v1.CloudTargetSelector)
      com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.class, com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (machineIdBuilder_ != null) {
        machineIdBuilder_.clear();
      }
      selectorCase_ = 0;
      selector_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudTargetSelector_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getDefaultInstanceForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector build() {
      com.senbax.senvend.proto.cloud.v1.CloudTargetSelector result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector buildPartial() {
      com.senbax.senvend.proto.cloud.v1.CloudTargetSelector result = new com.senbax.senvend.proto.cloud.v1.CloudTargetSelector(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector result) {
      result.selectorCase_ = selectorCase_;
      result.selector_ = this.selector_;
      if (selectorCase_ == 1 &&
          machineIdBuilder_ != null) {
        result.selector_ = machineIdBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.cloud.v1.CloudTargetSelector) {
        return mergeFrom((com.senbax.senvend.proto.cloud.v1.CloudTargetSelector)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector other) {
      if (other == com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance()) return this;
      switch (other.getSelectorCase()) {
        case MACHINE_ID: {
          mergeMachineId(other.getMachineId());
          break;
        }
        case SERIAL_NUMBER: {
          selectorCase_ = 2;
          selector_ = other.selector_;
          onChanged();
          break;
        }
        case SELECTOR_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetMachineIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              selectorCase_ = 1;
              break;
            } // case 10
            case 18: {
              selectorCase_ = 2;
              selector_ = input.readStringRequireUtf8();
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int selectorCase_ = 0;
    private java.lang.Object selector_;
    public SelectorCase
        getSelectorCase() {
      return SelectorCase.forNumber(
          selectorCase_);
    }

    public Builder clearSelector() {
      selectorCase_ = 0;
      selector_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.Uuid4, com.senbax.senvend.proto.api.v1.Uuid4.Builder, com.senbax.senvend.proto.api.v1.Uuid4OrBuilder> machineIdBuilder_;
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     * @return Whether the machineId field is set.
     */
    @java.lang.Override
    public boolean hasMachineId() {
      return selectorCase_ == 1;
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     * @return The machineId.
     */
    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.Uuid4 getMachineId() {
      if (machineIdBuilder_ == null) {
        if (selectorCase_ == 1) {
          return (com.senbax.senvend.proto.api.v1.Uuid4) selector_;
        }
        return com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
      } else {
        if (selectorCase_ == 1) {
          return machineIdBuilder_.getMessage();
        }
        return com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    public Builder setMachineId(com.senbax.senvend.proto.api.v1.Uuid4 value) {
      if (machineIdBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        selector_ = value;
        onChanged();
      } else {
        machineIdBuilder_.setMessage(value);
      }
      selectorCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    public Builder setMachineId(
        com.senbax.senvend.proto.api.v1.Uuid4.Builder builderForValue) {
      if (machineIdBuilder_ == null) {
        selector_ = builderForValue.build();
        onChanged();
      } else {
        machineIdBuilder_.setMessage(builderForValue.build());
      }
      selectorCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    public Builder mergeMachineId(com.senbax.senvend.proto.api.v1.Uuid4 value) {
      if (machineIdBuilder_ == null) {
        if (selectorCase_ == 1 &&
            selector_ != com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance()) {
          selector_ = com.senbax.senvend.proto.api.v1.Uuid4.newBuilder((com.senbax.senvend.proto.api.v1.Uuid4) selector_)
              .mergeFrom(value).buildPartial();
        } else {
          selector_ = value;
        }
        onChanged();
      } else {
        if (selectorCase_ == 1) {
          machineIdBuilder_.mergeFrom(value);
        } else {
          machineIdBuilder_.setMessage(value);
        }
      }
      selectorCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    public Builder clearMachineId() {
      if (machineIdBuilder_ == null) {
        if (selectorCase_ == 1) {
          selectorCase_ = 0;
          selector_ = null;
          onChanged();
        }
      } else {
        if (selectorCase_ == 1) {
          selectorCase_ = 0;
          selector_ = null;
        }
        machineIdBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    public com.senbax.senvend.proto.api.v1.Uuid4.Builder getMachineIdBuilder() {
      return internalGetMachineIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    @java.lang.Override
    public com.senbax.senvend.proto.api.v1.Uuid4OrBuilder getMachineIdOrBuilder() {
      if ((selectorCase_ == 1) && (machineIdBuilder_ != null)) {
        return machineIdBuilder_.getMessageOrBuilder();
      } else {
        if (selectorCase_ == 1) {
          return (com.senbax.senvend.proto.api.v1.Uuid4) selector_;
        }
        return com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Select by my.senvend.com machine UUID.
     * </pre>
     *
     * <code>.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.Uuid4, com.senbax.senvend.proto.api.v1.Uuid4.Builder, com.senbax.senvend.proto.api.v1.Uuid4OrBuilder> 
        internalGetMachineIdFieldBuilder() {
      if (machineIdBuilder_ == null) {
        if (!(selectorCase_ == 1)) {
          selector_ = com.senbax.senvend.proto.api.v1.Uuid4.getDefaultInstance();
        }
        machineIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.senbax.senvend.proto.api.v1.Uuid4, com.senbax.senvend.proto.api.v1.Uuid4.Builder, com.senbax.senvend.proto.api.v1.Uuid4OrBuilder>(
                (com.senbax.senvend.proto.api.v1.Uuid4) selector_,
                getParentForChildren(),
                isClean());
        selector_ = null;
      }
      selectorCase_ = 1;
      onChanged();
      return machineIdBuilder_;
    }

    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @return Whether the serialNumber field is set.
     */
    @java.lang.Override
    public boolean hasSerialNumber() {
      return selectorCase_ == 2;
    }
    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @return The serialNumber.
     */
    @java.lang.Override
    public java.lang.String getSerialNumber() {
      if (selectorCase_ != 2) {
        return "";
      }
      java.lang.Object ref = selector_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
          selector_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @return The bytes for serialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      if (selectorCase_ != 2) {
        return com.google.protobuf.ByteString.copyFromUtf8(        "");
      }
      java.lang.Object ref = selector_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selector_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @param value The serialNumber to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNumber(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      selectorCase_ = 2;
      selector_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialNumber() {
      if (selectorCase_ == 2) {
        selectorCase_ = 0;
        selector_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Select by SENVEND Terminal serial number.
     * </pre>
     *
     * <code>string serial_number = 2 [json_name = "serialNumber"];</code>
     * @param value The bytes for serialNumber to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      selectorCase_ = 2;
      selector_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:cloud.v1.CloudTargetSelector)
  }

  // @@protoc_insertion_point(class_scope:cloud.v1.CloudTargetSelector)
  private static final com.senbax.senvend.proto.cloud.v1.CloudTargetSelector DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.cloud.v1.CloudTargetSelector();
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudTargetSelector>
      PARSER = new com.google.protobuf.AbstractParser<CloudTargetSelector>() {
    @java.lang.Override
    public CloudTargetSelector parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloudTargetSelector> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudTargetSelector> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

