// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

@com.google.protobuf.Generated
public interface CloudAgeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cloud.v1.CloudAgeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The age verification response from the terminal.
   * </pre>
   *
   * <code>.api.v1.AgeResponse age_response = 1 [json_name = "ageResponse"];</code>
   * @return Whether the ageResponse field is set.
   */
  boolean hasAgeResponse();
  /**
   * <pre>
   * The age verification response from the terminal.
   * </pre>
   *
   * <code>.api.v1.AgeResponse age_response = 1 [json_name = "ageResponse"];</code>
   * @return The ageResponse.
   */
  com.senbax.senvend.proto.api.v1.AgeResponse getAgeResponse();
  /**
   * <pre>
   * The age verification response from the terminal.
   * </pre>
   *
   * <code>.api.v1.AgeResponse age_response = 1 [json_name = "ageResponse"];</code>
   */
  com.senbax.senvend.proto.api.v1.AgeResponseOrBuilder getAgeResponseOrBuilder();
}
