// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto
// Protobuf Java Version: 4.36.0

package com.senbax.senvend.proto.cloud.v1;

/**
 * <pre>
 * All messages sent from the integrator/VMC to the SENVEND Terminal to manage payments.
 * </pre>
 *
 * Protobuf type {@code cloud.v1.CloudPayRequest}
 */
@com.google.protobuf.Generated
public final class CloudPayRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cloud.v1.CloudPayRequest)
    CloudPayRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CloudPayRequest");
  }
  // Use CloudPayRequest.newBuilder() to construct.
  private CloudPayRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CloudPayRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.senbax.senvend.proto.cloud.v1.CloudPayRequest.class, com.senbax.senvend.proto.cloud.v1.CloudPayRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TARGET_FIELD_NUMBER = 1;
  private com.senbax.senvend.proto.cloud.v1.CloudTargetSelector target_;
  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   * @return Whether the target field is set.
   */
  @java.lang.Override
  public boolean hasTarget() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   * @return The target.
   */
  @java.lang.Override
  public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getTarget() {
    return target_ == null ? com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance() : target_;
  }
  /**
   * <pre>
   * Selector for the target machine or terminal.
   * Required for the first PayRequest in the stream, subsequent messages may omit this field.
   * </pre>
   *
   * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder getTargetOrBuilder() {
    return target_ == null ? com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance() : target_;
  }

  public static final int PAY_REQUEST_FIELD_NUMBER = 2;
  private com.senbax.senvend.proto.api.v1.PayRequest payRequest_;
  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   * @return Whether the payRequest field is set.
   */
  @java.lang.Override
  public boolean hasPayRequest() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   * @return The payRequest.
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.PayRequest getPayRequest() {
    return payRequest_ == null ? com.senbax.senvend.proto.api.v1.PayRequest.getDefaultInstance() : payRequest_;
  }
  /**
   * <pre>
   * The payment request to be sent to the terminal.
   * </pre>
   *
   * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
   */
  @java.lang.Override
  public com.senbax.senvend.proto.api.v1.PayRequestOrBuilder getPayRequestOrBuilder() {
    return payRequest_ == null ? com.senbax.senvend.proto.api.v1.PayRequest.getDefaultInstance() : payRequest_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTarget());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPayRequest());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTarget());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPayRequest());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.senbax.senvend.proto.cloud.v1.CloudPayRequest)) {
      return super.equals(obj);
    }
    com.senbax.senvend.proto.cloud.v1.CloudPayRequest other = (com.senbax.senvend.proto.cloud.v1.CloudPayRequest) obj;

    if (hasTarget() != other.hasTarget()) return false;
    if (hasTarget()) {
      if (!getTarget()
          .equals(other.getTarget())) return false;
    }
    if (hasPayRequest() != other.hasPayRequest()) return false;
    if (hasPayRequest()) {
      if (!getPayRequest()
          .equals(other.getPayRequest())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTarget()) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
    }
    if (hasPayRequest()) {
      hash = (37 * hash) + PAY_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getPayRequest().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.senbax.senvend.proto.cloud.v1.CloudPayRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * All messages sent from the integrator/VMC to the SENVEND Terminal to manage payments.
   * </pre>
   *
   * Protobuf type {@code cloud.v1.CloudPayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cloud.v1.CloudPayRequest)
      com.senbax.senvend.proto.cloud.v1.CloudPayRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.senbax.senvend.proto.cloud.v1.CloudPayRequest.class, com.senbax.senvend.proto.cloud.v1.CloudPayRequest.Builder.class);
    }

    // Construct using com.senbax.senvend.proto.cloud.v1.CloudPayRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTargetFieldBuilder();
        internalGetPayRequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      target_ = null;
      if (targetBuilder_ != null) {
        targetBuilder_.dispose();
        targetBuilder_ = null;
      }
      payRequest_ = null;
      if (payRequestBuilder_ != null) {
        payRequestBuilder_.dispose();
        payRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudProto.internal_static_cloud_v1_CloudPayRequest_descriptor;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudPayRequest getDefaultInstanceForType() {
      return com.senbax.senvend.proto.cloud.v1.CloudPayRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudPayRequest build() {
      com.senbax.senvend.proto.cloud.v1.CloudPayRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.senbax.senvend.proto.cloud.v1.CloudPayRequest buildPartial() {
      com.senbax.senvend.proto.cloud.v1.CloudPayRequest result = new com.senbax.senvend.proto.cloud.v1.CloudPayRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.senbax.senvend.proto.cloud.v1.CloudPayRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.target_ = targetBuilder_ == null
            ? target_
            : targetBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.payRequest_ = payRequestBuilder_ == null
            ? payRequest_
            : payRequestBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.senbax.senvend.proto.cloud.v1.CloudPayRequest) {
        return mergeFrom((com.senbax.senvend.proto.cloud.v1.CloudPayRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.senbax.senvend.proto.cloud.v1.CloudPayRequest other) {
      if (other == com.senbax.senvend.proto.cloud.v1.CloudPayRequest.getDefaultInstance()) return this;
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      if (other.hasPayRequest()) {
        mergePayRequest(other.getPayRequest());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetTargetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPayRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.senbax.senvend.proto.cloud.v1.CloudTargetSelector target_;
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.cloud.v1.CloudTargetSelector, com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder, com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder> targetBuilder_;
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     * @return Whether the target field is set.
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     * @return The target.
     */
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector getTarget() {
      if (targetBuilder_ == null) {
        return target_ == null ? com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance() : target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public Builder setTarget(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector value) {
      if (targetBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        target_ = value;
      } else {
        targetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public Builder setTarget(
        com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public Builder mergeTarget(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector value) {
      if (targetBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          target_ != null &&
          target_ != com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance()) {
          getTargetBuilder().mergeFrom(value);
        } else {
          target_ = value;
        }
      } else {
        targetBuilder_.mergeFrom(value);
      }
      if (target_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public Builder clearTarget() {
      bitField0_ = (bitField0_ & ~0x00000001);
      target_ = null;
      if (targetBuilder_ != null) {
        targetBuilder_.dispose();
        targetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder getTargetBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetTargetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    public com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_ == null ?
            com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.getDefaultInstance() : target_;
      }
    }
    /**
     * <pre>
     * Selector for the target machine or terminal.
     * Required for the first PayRequest in the stream, subsequent messages may omit this field.
     * </pre>
     *
     * <code>.cloud.v1.CloudTargetSelector target = 1 [json_name = "target"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.cloud.v1.CloudTargetSelector, com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder, com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder> 
        internalGetTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.senbax.senvend.proto.cloud.v1.CloudTargetSelector, com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder, com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder>(
                getTarget(),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    private com.senbax.senvend.proto.api.v1.PayRequest payRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.PayRequest, com.senbax.senvend.proto.api.v1.PayRequest.Builder, com.senbax.senvend.proto.api.v1.PayRequestOrBuilder> payRequestBuilder_;
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     * @return Whether the payRequest field is set.
     */
    public boolean hasPayRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     * @return The payRequest.
     */
    public com.senbax.senvend.proto.api.v1.PayRequest getPayRequest() {
      if (payRequestBuilder_ == null) {
        return payRequest_ == null ? com.senbax.senvend.proto.api.v1.PayRequest.getDefaultInstance() : payRequest_;
      } else {
        return payRequestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public Builder setPayRequest(com.senbax.senvend.proto.api.v1.PayRequest value) {
      if (payRequestBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        payRequest_ = value;
      } else {
        payRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public Builder setPayRequest(
        com.senbax.senvend.proto.api.v1.PayRequest.Builder builderForValue) {
      if (payRequestBuilder_ == null) {
        payRequest_ = builderForValue.build();
      } else {
        payRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public Builder mergePayRequest(com.senbax.senvend.proto.api.v1.PayRequest value) {
      if (payRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          payRequest_ != null &&
          payRequest_ != com.senbax.senvend.proto.api.v1.PayRequest.getDefaultInstance()) {
          getPayRequestBuilder().mergeFrom(value);
        } else {
          payRequest_ = value;
        }
      } else {
        payRequestBuilder_.mergeFrom(value);
      }
      if (payRequest_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public Builder clearPayRequest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      payRequest_ = null;
      if (payRequestBuilder_ != null) {
        payRequestBuilder_.dispose();
        payRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public com.senbax.senvend.proto.api.v1.PayRequest.Builder getPayRequestBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPayRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    public com.senbax.senvend.proto.api.v1.PayRequestOrBuilder getPayRequestOrBuilder() {
      if (payRequestBuilder_ != null) {
        return payRequestBuilder_.getMessageOrBuilder();
      } else {
        return payRequest_ == null ?
            com.senbax.senvend.proto.api.v1.PayRequest.getDefaultInstance() : payRequest_;
      }
    }
    /**
     * <pre>
     * The payment request to be sent to the terminal.
     * </pre>
     *
     * <code>.api.v1.PayRequest pay_request = 2 [json_name = "payRequest"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.senbax.senvend.proto.api.v1.PayRequest, com.senbax.senvend.proto.api.v1.PayRequest.Builder, com.senbax.senvend.proto.api.v1.PayRequestOrBuilder> 
        internalGetPayRequestFieldBuilder() {
      if (payRequestBuilder_ == null) {
        payRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.senbax.senvend.proto.api.v1.PayRequest, com.senbax.senvend.proto.api.v1.PayRequest.Builder, com.senbax.senvend.proto.api.v1.PayRequestOrBuilder>(
                getPayRequest(),
                getParentForChildren(),
                isClean());
        payRequest_ = null;
      }
      return payRequestBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:cloud.v1.CloudPayRequest)
  }

  // @@protoc_insertion_point(class_scope:cloud.v1.CloudPayRequest)
  private static final com.senbax.senvend.proto.cloud.v1.CloudPayRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.senbax.senvend.proto.cloud.v1.CloudPayRequest();
  }

  public static com.senbax.senvend.proto.cloud.v1.CloudPayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloudPayRequest>
      PARSER = new com.google.protobuf.AbstractParser<CloudPayRequest>() {
    @java.lang.Override
    public CloudPayRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloudPayRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CloudPayRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.senbax.senvend.proto.cloud.v1.CloudPayRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

