// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cloud/v1/cloud.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.senbax.senvend.proto.cloud.v1;

@kotlin.jvm.JvmName("-initializecloudTargetSelector")
public inline fun cloudTargetSelector(block: com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.cloud.v1.CloudTargetSelector =
  com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorKt.Dsl._create(com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.newBuilder()).apply { block() }._build()
/**
 * ```
 * Identifies the terminal to send messages to.
 * ```
 *
 * Protobuf type `cloud.v1.CloudTargetSelector`
 */
public object CloudTargetSelectorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.senbax.senvend.proto.cloud.v1.CloudTargetSelector = _builder.build()

    /**
     * ```
     * Select by my.senvend.com machine UUID.
     * ```
     *
     * `.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];`
     */
    public var machineId: com.senbax.senvend.proto.api.v1.Uuid4
      @kotlin.jvm.JvmName("getMachineId")
        get() = _builder.machineId
      @kotlin.jvm.JvmName("setMachineId")
        set(value) {
        _builder.machineId = value
      }
    /**
     * ```
     * Select by my.senvend.com machine UUID.
     * ```
     *
     * `.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];`
     */
    public fun clearMachineId() {
      _builder.clearMachineId()
    }
    /**
     * ```
     * Select by my.senvend.com machine UUID.
     * ```
     *
     * `.api.v1.Uuid4 machine_id = 1 [json_name = "machineId"];`
     * @return Whether the machineId field is set.
     */
    public fun hasMachineId(): kotlin.Boolean {
      return _builder.hasMachineId()
    }

    /**
     * ```
     * Select by SENVEND terminal serial number.
     * ```
     *
     * `string serial_number = 2 [json_name = "serialNumber"];`
     */
    public var serialNumber: kotlin.String
      @kotlin.jvm.JvmName("getSerialNumber")
        get() = _builder.serialNumber
      @kotlin.jvm.JvmName("setSerialNumber")
        set(value) {
        _builder.serialNumber = value
      }
    /**
     * ```
     * Select by SENVEND terminal serial number.
     * ```
     *
     * `string serial_number = 2 [json_name = "serialNumber"];`
     */
    public fun clearSerialNumber() {
      _builder.clearSerialNumber()
    }
    /**
     * ```
     * Select by SENVEND terminal serial number.
     * ```
     *
     * `string serial_number = 2 [json_name = "serialNumber"];`
     * @return Whether the serialNumber field is set.
     */
    public fun hasSerialNumber(): kotlin.Boolean {
      return _builder.hasSerialNumber()
    }
    public val selectorCase: com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.SelectorCase
    @kotlin.jvm.JvmName("getSelectorCase")
      get() = _builder.getSelectorCase()

    public fun clearSelector() {
      _builder.clearSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.senbax.senvend.proto.cloud.v1.CloudTargetSelector.copy(block: `com.senbax.senvend.proto.cloud.v1`.CloudTargetSelectorKt.Dsl.() -> kotlin.Unit): com.senbax.senvend.proto.cloud.v1.CloudTargetSelector =
  `com.senbax.senvend.proto.cloud.v1`.CloudTargetSelectorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.senbax.senvend.proto.cloud.v1.CloudTargetSelectorOrBuilder.machineIdOrNull: com.senbax.senvend.proto.api.v1.Uuid4?
  get() = if (hasMachineId()) getMachineId() else null

