syntax = "proto3";

package api.v1;

import "api/v1/common.proto";

/*
 * All messages sent from the integrator/VMC to the SENVEND Terminal to manage age verification.
 * An age verification process must be started with the AgeStartRequest message.
 */
message AgeRequest {
  // Unique identifier for an age verification request. Can be used for tracing and correlating requests and responses.
  // Optional field. If not provided, the system will generate a new UUID.
  Uuid4 id = 1;
  // Actual command to control a specific age verification process with the given UUID.
  oneof request {
    // Start a new age verification process.
    AgeStartRequest start = 2;
    // Cancel an ongoing age verification process.
    AgeCancelRequest cancel = 3;
    // Mark an ongoing age verification process as successful. (Cancel with success)
    AgeApproveRequest approve = 4;
  }
}

/*
 * Starts an age verification process on the SENVEND Terminal.
 */
message AgeStartRequest {
  // The minimum age required to pass verification. For example, 18 for at least 18 years old.
  // This field is mandatory and should be a positive integer (greater than 0 but smaller or equal 120).
  uint32 min_age = 1;
  // Optional - indicates if any already running request should be canceled.
  // Defaults to true if left out.
  optional bool auto_cancel = 2;
}

/*
 * Cancels an ongoing age verification process on the SENVEND Terminal.
 * Can be sent at any time, but will result in AGE_API_FAILURE_REASON_UUID_NOT_FOUND
 * if there is nothing to cancel.
 * If sent in an AgeRequest without UUID, will cancel any running age verification or payment process without UUID check.
 */
message AgeCancelRequest {}

/*
 * Approves an ongoing age verification process on the SENVEND Terminal.
 * Can be sent instead of a cancel, to end the age request and proceed without an error.
 * Useful if an external age verification is used in addition to the SENVEND Terminal.
 * If sent in an AgeRequest without UUID, will approve any running process without UUID check. (Catch all)
 */
message AgeApproveRequest {
  // Optional - A message detailing the reason for the age approval.
  optional string reason = 1;
}

/*
 * Response to an AgeRequest.
 * AgeSuccess and AgeFailure are final states, they indicate the end of the age verification process.
 *
 * A transient state means the process continues and more responses follow.
 * A final state means this process ended; no further responses for this ID.
 */
message AgeResponse {
  // Unique identifier for the age verification request. Mirrors the ID from the AgeRequest.
  // This field is always populated, either with the provided ID from the request or a newly generated one.
  Uuid4 id = 1;
  // The result of the age verification process.
  oneof result {
    // final state
    AgeSuccess success = 2;
    // final state
    AgeFailure failure = 3;
    // transient state
    AgeApiSuccess api_success = 4;
    // transient/final state
    // An API failure is usually transient as it doesn't end the current process.
    // But it is final if it does not result in a new process with that UUID either.
    // Prime examples are AgeStart with an invalid age or an AgeCancel for an unknown UUID.
    AgeApiFailure api_failure = 5;
  }
}

/*
 * Indicates a successful age verification.
 */
message AgeSuccess {}

/*
 * The actual reason (other than underage) why an age verification process failed.
 */
enum AgeFailureReason {
  // Unspecified reason. Protocol reserved, do not use.
  AGE_FAILURE_REASON_UNSPECIFIED = 0;
  // Verification process was cancelled by the user.
  AGE_FAILURE_REASON_USER_CANCELLED = 1;
  // Verification process ended due to timeout.
  AGE_FAILURE_REASON_TIMEOUT = 2;
  // A verification process with another UUID is already ongoing.
  AGE_FAILURE_REASON_VERIFICATION_ONGOING = 3;
  // The system is in an invalid state to perform age verification.
  // (e.g. a payment is in progress)
  AGE_FAILURE_REASON_INVALID_STATE = 4;
  // The verification process was cancelled by a previous AgeCancelRequest message.
  AGE_FAILURE_REASON_API_CANCELLED = 5;
  // If a given UUID is not a valid v4 UUID
  AGE_FAILURE_REASON_INVALID_UUID = 6;
  // If there is no age provider in the current configuration for the given minimum age
  AGE_FAILURE_REASON_NO_APPLICABLE_PROVIDER = 7;
}

/*
 * If age verification failed because of the determined age.
 * Contains the age determined.
 */
message AgeFailureUnderage {
  // The age that was determined during the verification process.
  // May be empty since not all verification methods do return an actual value,
  // only if the threshold was met.
  optional uint32 determined_age = 1;
}

/*
 * Indicates a failed age verification.
 */
message AgeFailure {
  // The reason for the age verification failure.
  // Either a general failure reason or specific under age details.
  oneof reason {
    AgeFailureReason failure_reason = 1;
    AgeFailureUnderage under_age = 2;
  }
}

/*
 * The actual API usage error.
 */
enum AgeApiFailureReason {
  // Unspecified reason. Protocol reserved, do not use.
  AGE_API_FAILURE_REASON_UNSPECIFIED = 0;
  // The provided minAge is invalid (e.g. zero).
  AGE_API_FAILURE_REASON_INVALID_AGE = 1;
  // A cancel failed or there was nothing to cancel
  AGE_API_FAILURE_REASON_CANCEL_FAILED = 2;
  // No request for this UUID found (could already be finished or cancelled).
  AGE_API_FAILURE_REASON_UUID_NOT_FOUND = 3;
  // The command inside AgeRequest is unknown to the API (i.e. mismatching proto versions).
  AGE_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;
}

/*
 * Indicates a wrong usage/argument in the AgeVerification API.
 * Does not end an already running verification process.
 */
message AgeApiFailure {
  // The reason for the API failure.
  AgeApiFailureReason reason = 1;
}

/*
 * The specific reason for an API success message.
 */
enum AgeApiSuccessReason {
  // Unspecified reason. Protocol reserved, do not use.
  AGE_API_SUCCESS_REASON_UNSPECIFIED = 0;
  // A verification process was successfully started with the given amount.
  AGE_API_SUCCESS_REASON_VERIFICATION_STARTED = 1;
  // A cancel request was successfully executed and cancellation is in progress.
  AGE_API_SUCCESS_REASON_CANCEL_ACCEPTED = 2;
  // An approve request was successfully executed and approval is in progress.
  AGE_API_SUCCESS_REASON_APPROVE_ACCEPTED = 3;
}

/*
 * Indicates a successfully executed request
 */
message AgeApiSuccess {
  AgeApiSuccessReason reason = 1;
}
