syntax = "proto3";

package api.v1;

import "api/v1/age.proto";
import "api/v1/common.proto";
import "api/v1/vend.proto";

/*
 * All messages sent from the integrator/VMC to the SENVEND terminal to manage payments.
 * A payment process must be started with the PayStart message.
 */
message PayRequest {
  // Unique identifier for this payment request. Can be used for tracing and correlating requests and responses.
  // Optional field. If not provided, the system will generate a new UUID.
  Uuid4 id = 1;
  // Actual command to control a specific payment process with the given UUID.
  oneof request {
    // Start a new payment process.
    PayStart start = 2;
    // Cancel an ongoing payment process (possibly reimbursing the payment).
    PayCancel cancel = 3;
    // Signify that goods were issued (i.e. payment will NOT be reimbursed).
    PayGoodsIssued goods_issued = 4;
    // Mark an ongoing age verification process as successful. (Cancel without error)
    AgeApproveRequest age_approve = 5;
    // Update payment amounts during an ongoing payment.
    PayUpdate update = 6;
    // Vend items after APPROVED but before GOODS_ISSUED, or when no payment process is running.
    VendStart vend = 7;
    // Cancel a previously started vending process.
    VendCancel vend_cancel = 8;
  }
}

/*
 * Starts a payment process on the SENVEND terminal.
 * If auto_cancel is given and false, it can only be executed after a previous process finished with either PayFailure or PaySuccess.
 * Will result in a PAY_FAILURE_REASON_PAYMENT_ONGOING or PAY_FAILURE_REASON_INVALID_STATE otherwise.
 * Without auto_cancel or if it is true, will automatically cancel any running request and then try to start this one.
 */
message PayStart {
  // The amount to be paid, in cents.
  // Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
  uint32 amount = 1;
  // Optional - age verification request to be performed before payment.
  // The value of auto_cancel inside this message will be ignored.
  AgeStartRequest age_verification = 2;
  // Optional - the list of individual invoice positions this payment is meant for.
  repeated LineItem line_items = 3;
  // Optional - reporting field for partial cash payment.
  // Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
  // but will be checked against line_items.
  optional uint32 cash_amount = 4;
  // Optional - indicates if any already running request should be canceled.
  // Defaults to true if left out.
  optional bool auto_cancel = 5;
}

/*
 * Updates the payment amount on the SENVEND terminal mid-transaction.
 * Main use case is handling cash payments after `PayStart`,
 * and/or changing individual `LineItems` (e.g. if one item in a Basket was cancelled individually).
 * If age verification was requested as well, this message is only accepted after the age verification was successful.
 * Will result in a PAY_API_FAILURE_REASON_INVALID_STATE otherwise.
 * Can only be accepted if the payment was not approved yet, or will result in a PAY_API_FAILURE_REASON_ALREADY_APPROVED otherwise.
 */
message PayUpdate {
  // The new cashless amount to be paid for this ongoing payment, in cents.
  // If cash amount is 0, a partial_amount of 0 will be replaced with the value from PayStart.amount.
  uint32 partial_amount = 1;
  // Optional - the list of individual invoice positions this payment is meant for.
  repeated LineItem line_items = 2;
  // Optional - reporting field for partial or full cash payment.
  // The sum of cash_amount + partial_amount will be checked against line_items.
  optional uint32 cash_amount = 3;
}

/*
 * Cancels an ongoing payment process on the SENVEND terminal.
 * Can also be used to cancel an approved payment (instead of PayGoodsIssued).
 * Can be sent at any time, but will result in PAY_API_FAILURE_REASON_UUID_NOT_FOUND
 * if there is nothing to cancel.
 * If sent in a PayRequest without UUID, will cancel any running process without UUID check, including vending. (Catch all)
 */
message PayCancel {}

/*
 * An approved payment will not be finalized until this message or a PayCancel is issued.
 * A cancel or timeout will reimburse the payment.
 */
message PayGoodsIssued {
  // Indicates partial issuing of goods, which will result in partial reimbursement.
  // If cash amount is 0, a partial_amount of 0 will be replaced with the value from PayStart.amount or the latest PayUpdate.partial_amount.
  // Cannot be greater than PayStart.amount or the latest PayUpdate.partial_amount.
  uint32 partial_amount = 1;
  // Optional - the list of individual invoice positions that were actually issued to the customer.
  repeated LineItem line_items = 2;
  // Optional - reporting field for partial or full cash payment.
  // The sum of cash_amount + partial_amount will be checked against line_items.
  optional uint32 cash_amount = 3;
}

/*
 * Response to a PayRequest.
 * PaySuccess and PayFailure are final states, they indicate the end of the payment process.
 */
message PayResponse {
  // Unique identifier for the payment request. Mirrors the ID from the PayRequest.
  // This field is always populated, either with the provided ID from the request or a newly generated one.
  Uuid4 id = 1;
  // The result of the payment process.
  oneof result {
    // transient state
    PayApproved approved = 2;
    // final state
    PaySuccess success = 3;
    // final state
    PayFailure failure = 4;
    // final state
    PayApiFailure api_failure = 5;
    // transient state
    PayApiSuccess api_success = 6;
    // transient state
    AgeSuccess age_success = 7;
    // final state
    AgeFailure age_failure = 8;
    // transient state
    AgeApiSuccess age_api_success = 9;
    // final state
    AgeApiFailure age_api_failure = 10;
    // transient state
    VendEvent vend_event = 11;
    // transient state
    VendApiSuccess vend_api_success = 12;
    // transient state
    VendApiFailure vend_api_failure = 13;
    // transient state
    VendResult vend_success = 14;
    // transient state
    VendResult vend_failure = 15;
  }
}

/*
 * Indicates the user has started the payment process successfully (has enough credit).
 * Has to be answered with either a PayCancel or a PayGoodsIssued message.
 * If not answered within 9m30s, the payment will be completed as if PayGoodsIssued was sent.
 */
message PayApproved {
  // The amount that was actually approved.
  // Useful in case of multiple updates, since the approval might not be for the newest request.
  uint32 amount = 1;
}

/*
 * Indicates that the payment was successfully debited.
 * Ends the payment process.
 */
message PaySuccess {}

/*
 * The reason a payment process ended in failure.
 */
enum PayFailureReason {
  // Unspecified reason. Protocol reserved, do not use.
  PAY_FAILURE_REASON_UNSPECIFIED = 0;
  // Payment process was cancelled by the user.
  PAY_FAILURE_REASON_USER_CANCELLED = 1;
  // Payment process ended due to timeout.
  PAY_FAILURE_REASON_TIMEOUT = 2;
  // A payment with another UUID is already ongoing.
  PAY_FAILURE_REASON_PAYMENT_ONGOING = 3;
  // The system is in an invalid state to perform payment.
  // (i.e. app is still in startup or another process is ongoing)
  PAY_FAILURE_REASON_INVALID_STATE = 4;
  // The payment failed (e.g. invalid or broken card, not enough credit etc.)
  PAY_FAILURE_REASON_PAYMENT_FAILED = 5;
  // The payment process was cancelled by a previous PayCancel message.
  PAY_FAILURE_REASON_API_CANCELLED = 6;
  // No GoodsIssued message was received after PaymentApproved. Payment was reimbursed.
  PAY_FAILURE_REASON_APPROVE_TIMEOUT = 7;
}

/*
 * Indicates a payment ending in failure.
 */
message PayFailure {
  // The reason for the payment failure.
  oneof reason {
    PayFailureReason failure_reason = 1;
  }
}

/*
 * The actual API usage error.
 */
enum PayApiFailureReason {
  // Unspecified reason. Protocol reserved, do not use.
  PAY_API_FAILURE_REASON_UNSPECIFIED = 0;
  // The provided payment amount is invalid.
  PAY_API_FAILURE_REASON_INVALID_AMOUNT = 1;
  // A cancel failed or there was nothing to cancel
  PAY_API_FAILURE_REASON_CANCEL_FAILED = 2;
  // No request for this UUID found (could already be finished or cancelled).
  PAY_API_FAILURE_REASON_UUID_NOT_FOUND = 3;
  // The command inside PayRequest is unknown to the API (i.e. mismatching proto versions).
  PAY_API_FAILURE_REASON_UNKNOWN_COMMAND = 4;
  // A PayGoodsIssued request was sent before a payment was started or approved.
  PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT = 5;
  // If a list of LineItems is given but the sum of their prices does not match the given total or partial amount.
  PAY_API_FAILURE_REASON_AMOUNT_MISMATCH = 6;
  // If a given UUID is not a valid v4 UUID
  PAY_API_FAILURE_REASON_INVALID_UUID = 7;
  // If a command inside PayRequest was sent during a state in which it cannot be accepted.
  PAY_API_FAILURE_REASON_INVALID_STATE = 8;
  // The payment is already approved and can no longer be updated.
  PAY_API_FAILURE_REASON_ALREADY_APPROVED = 9;
}

/*
 * Indicates a wrong usage/argument in the Pay API.
 * Does not end an already running payment process.
 */
message PayApiFailure {
  // The reason for the API failure.
  PayApiFailureReason reason = 1;
}

/*
 * The specific reason for an api success message.
 */
enum PayApiSuccessReason {
  // Unspecified reason. Protocol reserved, do not use.
  PAY_API_SUCCESS_REASON_UNSPECIFIED = 0;
  // A payment process was successfully started with the given amount.
  PAY_API_SUCCESS_REASON_PAYMENT_STARTED = 1;
  // A cancel request was successfully executed and cancellation is in progress.
  PAY_API_SUCCESS_REASON_CANCEL_ACCEPTED = 2;
  // A goods issued request was successfully accepted and the payment process is finishing up.
  PAY_API_SUCCESS_REASON_GOODS_ISSUED_ACCEPTED = 3;
  // An age approve request was successfully executed and approval is in progress.
  PAY_API_SUCCESS_REASON_AGE_APPROVE_ACCEPTED = 4;
  // An update request was successfully executed and update is in progress.
  PAY_API_SUCCESS_REASON_UPDATE_ACCEPTED = 5;
}

/*
 * Indicates a successfully executed request.
 */
message PayApiSuccess {
  PayApiSuccessReason reason = 1;
}
