# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: local/v1/local.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AgeVerificationServiceStub",
    "PayServiceStub",
)

from collections.abc import AsyncIterable, AsyncIterator, Iterable
from typing import TYPE_CHECKING

import betterproto2
from betterproto2 import grpclib as betterproto2_grpclib

if TYPE_CHECKING:
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class AgeVerificationServiceStub(betterproto2_grpclib.ServiceStub):
    async def age(
        self,
        messages: "AsyncIterable[__api__v1__.AgeRequest] | Iterable[__api__v1__.AgeRequest]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "__api__v1__.AgeResponse":
        """
        Initiates an age verification process on the SENVEND Terminal
        """

        return await self._stream_unary(
            "/local.v1.AgeVerificationService/Age",
            messages,
            __api__v1__.AgeRequest,
            __api__v1__.AgeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class PayServiceStub(betterproto2_grpclib.ServiceStub):
    async def pay(
        self,
        messages: "AsyncIterable[__api__v1__.PayRequest] | Iterable[__api__v1__.PayRequest]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[__api__v1__.PayResponse]":
        """
        Initiates a payment process on the SENVEND Terminal
        """

        async for response in self._stream_stream(
            "/local.v1.PayService/Pay",
            messages,
            __api__v1__.PayRequest,
            __api__v1__.PayResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


from ...api import v1 as __api__v1__
