[workspace]
resolver = "2"
members = ["senvend_api", "example", "senvend_api_macros", "senvend_api_utils"]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Benedikt Bartscher <bb@senbax.de>"]
license = "Private"
readme = "README.md"
repository = "https://github.com/senvend/api"
categories = ["senbax", "senvend", "api", "payment"]
keywords = ["ecr", "payment", "payment-terminal", "age-verification"]

[workspace.dependencies]
bytes = "1.10.1"
prost = "0.14.1"
pbjson = "0.8.0"
pbjson-types = "0.8.0"
serde = "1.0.228"
tonic = { version = "0.14.2", features = ["gzip"] }
tonic-prost = "0.14.2"

# example
senvend_api = { path = "./senvend_api" }
senvend_api_macros = { path = "./senvend_api_macros" }
senvend_api_utils = { path = "./senvend_api_utils" }
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
quote = "=1.0.42"
syn = { version = "=2.0.111", features = ["parsing"] }
uuid = { version = "=1.17.0", default-features = false }
