# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: api/v1/age.proto, api/v1/common.proto, api/v1/pay.proto, api/v1/vend.proto, api/v1/version.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AgeApiFailure",
    "AgeApiFailureReason",
    "AgeApiSuccess",
    "AgeApiSuccessReason",
    "AgeApproveRequest",
    "AgeCancelRequest",
    "AgeFailure",
    "AgeFailureReason",
    "AgeFailureUnderage",
    "AgeRequest",
    "AgeResponse",
    "AgeStartRequest",
    "AgeSuccess",
    "LineItem",
    "MdbSelectionDeniedReason",
    "MdbVendFailureReason",
    "PayApiFailure",
    "PayApiFailureReason",
    "PayApiSuccess",
    "PayApiSuccessReason",
    "PayApproved",
    "PayCancel",
    "PayFailure",
    "PayFailureReason",
    "PayGoodsIssued",
    "PayRequest",
    "PayResponse",
    "PayStart",
    "PaySuccess",
    "PayUpdate",
    "Selection",
    "SemanticVersion",
    "Uuid4",
    "VendApiFailure",
    "VendApiFailureReason",
    "VendApiSuccess",
    "VendApiSuccessReason",
    "VendCancel",
    "VendEvent",
    "VendFailure",
    "VendFailureReason",
    "VendRequest",
    "VendResponse",
    "VendResult",
    "VendStart",
    "VendSuccess",
    "VersionRequest",
    "VersionResponse",
)

from dataclasses import dataclass

import betterproto2

from ...message_pool import default_message_pool

_COMPILER_VERSION = "0.10.1"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class AgeApiFailureReason(betterproto2.Enum):
    """

    The actual API usage error.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    INVALID_AGE = 1
    """
    The provided minAge is invalid (e.g. zero).
    """

    CANCEL_FAILED = 2
    """
    A cancel failed or there was nothing to cancel
    """

    UUID_NOT_FOUND = 3
    """
    No request for this UUID found (could already be finished or cancelled).
    """

    UNKNOWN_COMMAND = 4
    """
    The command inside AgeRequest is unknown to the API (i.e. mismatching proto versions).
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "AGE_API_FAILURE_REASON_UNSPECIFIED",
            1: "AGE_API_FAILURE_REASON_INVALID_AGE",
            2: "AGE_API_FAILURE_REASON_CANCEL_FAILED",
            3: "AGE_API_FAILURE_REASON_UUID_NOT_FOUND",
            4: "AGE_API_FAILURE_REASON_UNKNOWN_COMMAND",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "AGE_API_FAILURE_REASON_UNSPECIFIED": 0,
            "AGE_API_FAILURE_REASON_INVALID_AGE": 1,
            "AGE_API_FAILURE_REASON_CANCEL_FAILED": 2,
            "AGE_API_FAILURE_REASON_UUID_NOT_FOUND": 3,
            "AGE_API_FAILURE_REASON_UNKNOWN_COMMAND": 4,
        }


class AgeApiSuccessReason(betterproto2.Enum):
    """

    The specific reason for an API success message.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    VERIFICATION_STARTED = 1
    """
    A verification process was successfully started with the given amount.
    """

    CANCEL_ACCEPTED = 2
    """
    A cancel request was successfully executed and cancellation is in progress.
    """

    APPROVE_ACCEPTED = 3
    """
    An approve request was successfully executed and approval is in progress.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "AGE_API_SUCCESS_REASON_UNSPECIFIED",
            1: "AGE_API_SUCCESS_REASON_VERIFICATION_STARTED",
            2: "AGE_API_SUCCESS_REASON_CANCEL_ACCEPTED",
            3: "AGE_API_SUCCESS_REASON_APPROVE_ACCEPTED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "AGE_API_SUCCESS_REASON_UNSPECIFIED": 0,
            "AGE_API_SUCCESS_REASON_VERIFICATION_STARTED": 1,
            "AGE_API_SUCCESS_REASON_CANCEL_ACCEPTED": 2,
            "AGE_API_SUCCESS_REASON_APPROVE_ACCEPTED": 3,
        }


class AgeFailureReason(betterproto2.Enum):
    """

    The actual reason (other than underage) why an age verification process failed.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    USER_CANCELLED = 1
    """
    Verification process was cancelled by the user.
    """

    TIMEOUT = 2
    """
    Verification process ended due to timeout.
    """

    VERIFICATION_ONGOING = 3
    """
    A verification process with another UUID is already ongoing.
    """

    INVALID_STATE = 4
    """
    The system is in an invalid state to perform age verification.
    (e.g. a payment is in progress)
    """

    API_CANCELLED = 5
    """
    The verification process was cancelled by a previous AgeCancelRequest message.
    """

    INVALID_UUID = 6
    """
    If a given UUID is not a valid v4 UUID
    """

    NO_APPLICABLE_PROVIDER = 7
    """
    If there is no age provider in the current configuration for the given minimum age
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "AGE_FAILURE_REASON_UNSPECIFIED",
            1: "AGE_FAILURE_REASON_USER_CANCELLED",
            2: "AGE_FAILURE_REASON_TIMEOUT",
            3: "AGE_FAILURE_REASON_VERIFICATION_ONGOING",
            4: "AGE_FAILURE_REASON_INVALID_STATE",
            5: "AGE_FAILURE_REASON_API_CANCELLED",
            6: "AGE_FAILURE_REASON_INVALID_UUID",
            7: "AGE_FAILURE_REASON_NO_APPLICABLE_PROVIDER",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "AGE_FAILURE_REASON_UNSPECIFIED": 0,
            "AGE_FAILURE_REASON_USER_CANCELLED": 1,
            "AGE_FAILURE_REASON_TIMEOUT": 2,
            "AGE_FAILURE_REASON_VERIFICATION_ONGOING": 3,
            "AGE_FAILURE_REASON_INVALID_STATE": 4,
            "AGE_FAILURE_REASON_API_CANCELLED": 5,
            "AGE_FAILURE_REASON_INVALID_UUID": 6,
            "AGE_FAILURE_REASON_NO_APPLICABLE_PROVIDER": 7,
        }


class MdbSelectionDeniedReason(betterproto2.Enum):
    """

    Reasons why a selection request might be denied
    page 170 (MDB spec 4.3)
    """

    UNSPECIFIED = 0

    UNKNOWN_ERROR_OUT_OF_ORDER = 1

    SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED = 2

    SELECTION_EMPTY_NOT_DISPENSED = 3

    SELECTION_DEFECTIVE = 4

    INGREDIENT_IS_OVER = 5

    SELECTION_BLOCKED = 6

    SELECTION_INHIBITED = 7

    PRODUCT_EXPIRED = 8

    TEMPERATURE_CONDITIONS_OUT_OF_RANGE = 9

    MACHINE_BUSY_OR_WRONG_MODE = 10

    INSUFFICIENT_CREDIT = 11

    MACHINE_TEMPORARY_BUSY = 12

    MAX_RETRY_EXCEEDED = 13

    UNKNOWN_ERROR = 14
    """
    The VMC reported an error code, that is not defined in the MDB spec
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "MDB_SELECTION_DENIED_REASON_UNSPECIFIED",
            1: "MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR_OUT_OF_ORDER",
            2: "MDB_SELECTION_DENIED_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED",
            3: "MDB_SELECTION_DENIED_REASON_SELECTION_EMPTY_NOT_DISPENSED",
            4: "MDB_SELECTION_DENIED_REASON_SELECTION_DEFECTIVE",
            5: "MDB_SELECTION_DENIED_REASON_INGREDIENT_IS_OVER",
            6: "MDB_SELECTION_DENIED_REASON_SELECTION_BLOCKED",
            7: "MDB_SELECTION_DENIED_REASON_SELECTION_INHIBITED",
            8: "MDB_SELECTION_DENIED_REASON_PRODUCT_EXPIRED",
            9: "MDB_SELECTION_DENIED_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE",
            10: "MDB_SELECTION_DENIED_REASON_MACHINE_BUSY_OR_WRONG_MODE",
            11: "MDB_SELECTION_DENIED_REASON_INSUFFICIENT_CREDIT",
            12: "MDB_SELECTION_DENIED_REASON_MACHINE_TEMPORARY_BUSY",
            13: "MDB_SELECTION_DENIED_REASON_MAX_RETRY_EXCEEDED",
            14: "MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "MDB_SELECTION_DENIED_REASON_UNSPECIFIED": 0,
            "MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR_OUT_OF_ORDER": 1,
            "MDB_SELECTION_DENIED_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED": 2,
            "MDB_SELECTION_DENIED_REASON_SELECTION_EMPTY_NOT_DISPENSED": 3,
            "MDB_SELECTION_DENIED_REASON_SELECTION_DEFECTIVE": 4,
            "MDB_SELECTION_DENIED_REASON_INGREDIENT_IS_OVER": 5,
            "MDB_SELECTION_DENIED_REASON_SELECTION_BLOCKED": 6,
            "MDB_SELECTION_DENIED_REASON_SELECTION_INHIBITED": 7,
            "MDB_SELECTION_DENIED_REASON_PRODUCT_EXPIRED": 8,
            "MDB_SELECTION_DENIED_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE": 9,
            "MDB_SELECTION_DENIED_REASON_MACHINE_BUSY_OR_WRONG_MODE": 10,
            "MDB_SELECTION_DENIED_REASON_INSUFFICIENT_CREDIT": 11,
            "MDB_SELECTION_DENIED_REASON_MACHINE_TEMPORARY_BUSY": 12,
            "MDB_SELECTION_DENIED_REASON_MAX_RETRY_EXCEEDED": 13,
            "MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR": 14,
        }


class MdbVendFailureReason(betterproto2.Enum):
    """

    Reasons why a vend failed(only available if basket/partial refund is enabled)
    page 170 (MDB spec 4.3 section 7.4.8)
    """

    UNSPECIFIED = 0

    UNKNOWN_OUT_OF_ORDER = 1

    SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED = 2

    SELECTION_EMPTY_PRODUCT_NOT_DISPENSED = 3

    SELECTION_DEFECTIVE = 4

    INGREDIENT_IS_OVER = 5

    SELECTION_BLOCKED = 6

    SELECTION_INHIBITED = 7

    PRODUCT_EXPIRED = 8

    TEMPERATURE_CONDITIONS_OUT_OF_RANGE = 9

    MACHINE_BUSY_WRONG_MODE = 10

    INSUFFICIENT_CREDIT = 11

    UNKNOWN = 12

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "MDB_VEND_FAILURE_REASON_UNSPECIFIED",
            1: "MDB_VEND_FAILURE_REASON_UNKNOWN_OUT_OF_ORDER",
            2: "MDB_VEND_FAILURE_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED",
            3: "MDB_VEND_FAILURE_REASON_SELECTION_EMPTY_PRODUCT_NOT_DISPENSED",
            4: "MDB_VEND_FAILURE_REASON_SELECTION_DEFECTIVE",
            5: "MDB_VEND_FAILURE_REASON_INGREDIENT_IS_OVER",
            6: "MDB_VEND_FAILURE_REASON_SELECTION_BLOCKED",
            7: "MDB_VEND_FAILURE_REASON_SELECTION_INHIBITED",
            8: "MDB_VEND_FAILURE_REASON_PRODUCT_EXPIRED",
            9: "MDB_VEND_FAILURE_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE",
            10: "MDB_VEND_FAILURE_REASON_MACHINE_BUSY_WRONG_MODE",
            11: "MDB_VEND_FAILURE_REASON_INSUFFICIENT_CREDIT",
            12: "MDB_VEND_FAILURE_REASON_UNKNOWN",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "MDB_VEND_FAILURE_REASON_UNSPECIFIED": 0,
            "MDB_VEND_FAILURE_REASON_UNKNOWN_OUT_OF_ORDER": 1,
            "MDB_VEND_FAILURE_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED": 2,
            "MDB_VEND_FAILURE_REASON_SELECTION_EMPTY_PRODUCT_NOT_DISPENSED": 3,
            "MDB_VEND_FAILURE_REASON_SELECTION_DEFECTIVE": 4,
            "MDB_VEND_FAILURE_REASON_INGREDIENT_IS_OVER": 5,
            "MDB_VEND_FAILURE_REASON_SELECTION_BLOCKED": 6,
            "MDB_VEND_FAILURE_REASON_SELECTION_INHIBITED": 7,
            "MDB_VEND_FAILURE_REASON_PRODUCT_EXPIRED": 8,
            "MDB_VEND_FAILURE_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE": 9,
            "MDB_VEND_FAILURE_REASON_MACHINE_BUSY_WRONG_MODE": 10,
            "MDB_VEND_FAILURE_REASON_INSUFFICIENT_CREDIT": 11,
            "MDB_VEND_FAILURE_REASON_UNKNOWN": 12,
        }


class PayApiFailureReason(betterproto2.Enum):
    """

    The actual API usage error.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    INVALID_AMOUNT = 1
    """
    The provided payment amount is invalid.
    """

    CANCEL_FAILED = 2
    """
    A cancel failed or there was nothing to cancel
    """

    UUID_NOT_FOUND = 3
    """
    No request for this UUID found (could already be finished or cancelled).
    """

    UNKNOWN_COMMAND = 4
    """
    The command inside PayRequest is unknown to the API (i.e. mismatching proto versions).
    """

    NO_APPROVED_PAYMENT = 5
    """
    A PayGoodsIssued request was sent before a payment was started or approved.
    """

    AMOUNT_MISMATCH = 6
    """
    If a list of LineItems is given but the sum of their prices does not match the given total or partial amount.
    """

    INVALID_UUID = 7
    """
    If a given UUID is not a valid v4 UUID
    """

    INVALID_STATE = 8
    """
    If a command inside PayRequest was sent during a state in which it cannot be accepted.
    """

    ALREADY_APPROVED = 9
    """
    The payment is already approved and can no longer be updated.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "PAY_API_FAILURE_REASON_UNSPECIFIED",
            1: "PAY_API_FAILURE_REASON_INVALID_AMOUNT",
            2: "PAY_API_FAILURE_REASON_CANCEL_FAILED",
            3: "PAY_API_FAILURE_REASON_UUID_NOT_FOUND",
            4: "PAY_API_FAILURE_REASON_UNKNOWN_COMMAND",
            5: "PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT",
            6: "PAY_API_FAILURE_REASON_AMOUNT_MISMATCH",
            7: "PAY_API_FAILURE_REASON_INVALID_UUID",
            8: "PAY_API_FAILURE_REASON_INVALID_STATE",
            9: "PAY_API_FAILURE_REASON_ALREADY_APPROVED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "PAY_API_FAILURE_REASON_UNSPECIFIED": 0,
            "PAY_API_FAILURE_REASON_INVALID_AMOUNT": 1,
            "PAY_API_FAILURE_REASON_CANCEL_FAILED": 2,
            "PAY_API_FAILURE_REASON_UUID_NOT_FOUND": 3,
            "PAY_API_FAILURE_REASON_UNKNOWN_COMMAND": 4,
            "PAY_API_FAILURE_REASON_NO_APPROVED_PAYMENT": 5,
            "PAY_API_FAILURE_REASON_AMOUNT_MISMATCH": 6,
            "PAY_API_FAILURE_REASON_INVALID_UUID": 7,
            "PAY_API_FAILURE_REASON_INVALID_STATE": 8,
            "PAY_API_FAILURE_REASON_ALREADY_APPROVED": 9,
        }


class PayApiSuccessReason(betterproto2.Enum):
    """

    The specific reason for an api success message.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    PAYMENT_STARTED = 1
    """
    A payment process was successfully started with the given amount.
    """

    CANCEL_ACCEPTED = 2
    """
    A cancel request was successfully executed and cancellation is in progress.
    """

    GOODS_ISSUED_ACCEPTED = 3
    """
    A goods issued request was successfully accepted and the payment process is finishing up.
    """

    AGE_APPROVE_ACCEPTED = 4
    """
    An age approve request was successfully executed and approval is in progress.
    """

    UPDATE_ACCEPTED = 5
    """
    An update request was successfully executed and update is in progress.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "PAY_API_SUCCESS_REASON_UNSPECIFIED",
            1: "PAY_API_SUCCESS_REASON_PAYMENT_STARTED",
            2: "PAY_API_SUCCESS_REASON_CANCEL_ACCEPTED",
            3: "PAY_API_SUCCESS_REASON_GOODS_ISSUED_ACCEPTED",
            4: "PAY_API_SUCCESS_REASON_AGE_APPROVE_ACCEPTED",
            5: "PAY_API_SUCCESS_REASON_UPDATE_ACCEPTED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "PAY_API_SUCCESS_REASON_UNSPECIFIED": 0,
            "PAY_API_SUCCESS_REASON_PAYMENT_STARTED": 1,
            "PAY_API_SUCCESS_REASON_CANCEL_ACCEPTED": 2,
            "PAY_API_SUCCESS_REASON_GOODS_ISSUED_ACCEPTED": 3,
            "PAY_API_SUCCESS_REASON_AGE_APPROVE_ACCEPTED": 4,
            "PAY_API_SUCCESS_REASON_UPDATE_ACCEPTED": 5,
        }


class PayFailureReason(betterproto2.Enum):
    """

    The reason a payment process ended in failure.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    USER_CANCELLED = 1
    """
    Payment process was cancelled by the user.
    """

    TIMEOUT = 2
    """
    Payment process ended due to timeout.
    """

    PAYMENT_ONGOING = 3
    """
    A payment with another UUID is already ongoing.
    """

    INVALID_STATE = 4
    """
    The system is in an invalid state to perform payment.
    (i.e. app is still in startup or another process is ongoing)
    """

    PAYMENT_FAILED = 5
    """
    The payment failed (e.g. invalid or broken card, not enough credit etc.)
    """

    API_CANCELLED = 6
    """
    The payment process was cancelled by a previous PayCancel message.
    """

    APPROVE_TIMEOUT = 7
    """
    No GoodsIssued message was received after PaymentApproved. Payment was reimbursed.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "PAY_FAILURE_REASON_UNSPECIFIED",
            1: "PAY_FAILURE_REASON_USER_CANCELLED",
            2: "PAY_FAILURE_REASON_TIMEOUT",
            3: "PAY_FAILURE_REASON_PAYMENT_ONGOING",
            4: "PAY_FAILURE_REASON_INVALID_STATE",
            5: "PAY_FAILURE_REASON_PAYMENT_FAILED",
            6: "PAY_FAILURE_REASON_API_CANCELLED",
            7: "PAY_FAILURE_REASON_APPROVE_TIMEOUT",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "PAY_FAILURE_REASON_UNSPECIFIED": 0,
            "PAY_FAILURE_REASON_USER_CANCELLED": 1,
            "PAY_FAILURE_REASON_TIMEOUT": 2,
            "PAY_FAILURE_REASON_PAYMENT_ONGOING": 3,
            "PAY_FAILURE_REASON_INVALID_STATE": 4,
            "PAY_FAILURE_REASON_PAYMENT_FAILED": 5,
            "PAY_FAILURE_REASON_API_CANCELLED": 6,
            "PAY_FAILURE_REASON_APPROVE_TIMEOUT": 7,
        }


class VendApiFailureReason(betterproto2.Enum):
    """

    The actual API usage error.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    INVALID_QUANTITY = 1
    """
    The provided vending quantity is invalid (e.g. zero).
    """

    CANCEL_FAILED = 2
    """
    A cancel failed or there was nothing to cancel
    """

    UUID_NOT_FOUND = 3
    """
    No request for this UUID found (could already be finished or cancelled).
    """

    UNKNOWN_COMMAND = 4
    """
    The command inside VendRequest is unknown to the API (i.e. mismatching proto versions).
    """

    INVALID_UUID = 5
    """
    If a given UUID is not a valid v4 UUID
    """

    INVALID_STATE = 6
    """
    If a command inside VendRequest was sent during a state in which it cannot be accepted.
    """

    VENDING_ONGOING = 7
    """
    A vending process is already ongoing.
    """

    INVALID_CONFIG = 8
    """
    The config is in a state where vending is not possible (i.e. no remote vend, no always idle etc.)
    """

    MDB_DISABLED = 9
    """
    A vend via MDB was requested (Selection), but MDB is disabled.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "VEND_API_FAILURE_REASON_UNSPECIFIED",
            1: "VEND_API_FAILURE_REASON_INVALID_QUANTITY",
            2: "VEND_API_FAILURE_REASON_CANCEL_FAILED",
            3: "VEND_API_FAILURE_REASON_UUID_NOT_FOUND",
            4: "VEND_API_FAILURE_REASON_UNKNOWN_COMMAND",
            5: "VEND_API_FAILURE_REASON_INVALID_UUID",
            6: "VEND_API_FAILURE_REASON_INVALID_STATE",
            7: "VEND_API_FAILURE_REASON_VENDING_ONGOING",
            8: "VEND_API_FAILURE_REASON_INVALID_CONFIG",
            9: "VEND_API_FAILURE_REASON_MDB_DISABLED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "VEND_API_FAILURE_REASON_UNSPECIFIED": 0,
            "VEND_API_FAILURE_REASON_INVALID_QUANTITY": 1,
            "VEND_API_FAILURE_REASON_CANCEL_FAILED": 2,
            "VEND_API_FAILURE_REASON_UUID_NOT_FOUND": 3,
            "VEND_API_FAILURE_REASON_UNKNOWN_COMMAND": 4,
            "VEND_API_FAILURE_REASON_INVALID_UUID": 5,
            "VEND_API_FAILURE_REASON_INVALID_STATE": 6,
            "VEND_API_FAILURE_REASON_VENDING_ONGOING": 7,
            "VEND_API_FAILURE_REASON_INVALID_CONFIG": 8,
            "VEND_API_FAILURE_REASON_MDB_DISABLED": 9,
        }


class VendApiSuccessReason(betterproto2.Enum):
    """

    The specific reason for an API success message.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    VENDING_STARTED = 1
    """
    A vending process was successfully started.
    """

    CANCEL_ACCEPTED = 2
    """
    A cancel request was successfully executed and cancellation is in progress.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "VEND_API_SUCCESS_REASON_UNSPECIFIED",
            1: "VEND_API_SUCCESS_REASON_VENDING_STARTED",
            2: "VEND_API_SUCCESS_REASON_CANCEL_ACCEPTED",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "VEND_API_SUCCESS_REASON_UNSPECIFIED": 0,
            "VEND_API_SUCCESS_REASON_VENDING_STARTED": 1,
            "VEND_API_SUCCESS_REASON_CANCEL_ACCEPTED": 2,
        }


class VendFailureReason(betterproto2.Enum):
    """

    The reason a vending process ended in failure.
    """

    UNSPECIFIED = 0
    """
    Unspecified reason. Protocol reserved, do not use.
    """

    TIMEOUT = 1
    """
    Vending process ended due to timeout.
    """

    VENDING_FAILED = 2
    """
    Vending one of the products failed (see protocol specific error)
    """

    API_CANCELLED = 3
    """
    The vending process was cancelled by a previous VendCancel message.
    """

    INVALID_STATE = 4
    """
    The system entered an invalid state to perform vending.
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "VEND_FAILURE_REASON_UNSPECIFIED",
            1: "VEND_FAILURE_REASON_TIMEOUT",
            2: "VEND_FAILURE_REASON_VENDING_FAILED",
            3: "VEND_FAILURE_REASON_API_CANCELLED",
            4: "VEND_FAILURE_REASON_INVALID_STATE",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "VEND_FAILURE_REASON_UNSPECIFIED": 0,
            "VEND_FAILURE_REASON_TIMEOUT": 1,
            "VEND_FAILURE_REASON_VENDING_FAILED": 2,
            "VEND_FAILURE_REASON_API_CANCELLED": 3,
            "VEND_FAILURE_REASON_INVALID_STATE": 4,
        }


@dataclass(eq=False, repr=False)
class AgeApiFailure(betterproto2.Message):
    """

    Indicates a wrong usage/argument in the AgeVerification API.
    Does not end an already running verification process.
    """

    reason: "AgeApiFailureReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: AgeApiFailureReason(0)
    )
    """
    The reason for the API failure.
    """


default_message_pool.register_message("api.v1", "AgeApiFailure", AgeApiFailure)


@dataclass(eq=False, repr=False)
class AgeApiSuccess(betterproto2.Message):
    """

    Indicates a successfully executed request
    """

    reason: "AgeApiSuccessReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: AgeApiSuccessReason(0)
    )


default_message_pool.register_message("api.v1", "AgeApiSuccess", AgeApiSuccess)


@dataclass(eq=False, repr=False)
class AgeApproveRequest(betterproto2.Message):
    """

    Approves an ongoing age verification process on the SENVEND terminal.
    Can be sent instead of a cancel, to end the age request and proceed without an error.
    Useful if an external age verification is used in addition to the SENVEND terminal.
    If sent in an AgeRequest without UUID, will approve any running process without UUID check. (Catch all)
    """

    reason: "str | None" = betterproto2.field(
        1, betterproto2.TYPE_STRING, optional=True
    )
    """
    Optional - A message detailing the reason for the age approval.
    """


default_message_pool.register_message("api.v1", "AgeApproveRequest", AgeApproveRequest)


@dataclass(eq=False, repr=False)
class AgeCancelRequest(betterproto2.Message):
    """

    Cancels an ongoing age verification process on the SENVEND terminal.
    Can be sent at any time, but will result in AGE_API_FAILURE_REASON_UUID_NOT_FOUND
    if there is nothing to cancel.
    If sent in an AgeRequest without UUID, will cancel any running process without UUID check, including vending. (Catch all)
    """

    pass


default_message_pool.register_message("api.v1", "AgeCancelRequest", AgeCancelRequest)


@dataclass(eq=False, repr=False)
class AgeFailure(betterproto2.Message):
    """

    Indicates a failed age verification.

    Oneofs:
        - reason: The reason for the age verification failure.
            Either a general failure reason or specific under age details.
    """

    failure_reason: "AgeFailureReason | None" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, optional=True, group="reason"
    )

    under_age: "AgeFailureUnderage | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="reason"
    )


default_message_pool.register_message("api.v1", "AgeFailure", AgeFailure)


@dataclass(eq=False, repr=False)
class AgeFailureUnderage(betterproto2.Message):
    """

    If age verification failed because of the determined age.
    Contains the age determined.
    """

    determined_age: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_UINT32, optional=True
    )
    """
    The age that was determined during the verification process.
    May be empty since not all verification methods do return an actual value,
    only if the threshold was met.
    """


default_message_pool.register_message(
    "api.v1", "AgeFailureUnderage", AgeFailureUnderage
)


@dataclass(eq=False, repr=False)
class AgeRequest(betterproto2.Message):
    """

    All messages sent from the integrator/VMC to the SENVEND terminal to manage age verification.
    An age verification process must be started with the AgeStartRequest message.

    Oneofs:
        - request: Actual command to control a specific age verification process with the given UUID.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for an age verification request. Can be used for tracing and correlating requests and responses.
    Optional field. If not provided, the system will generate a new UUID.
    """

    start: "AgeStartRequest | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Start a new age verification process.
    """

    cancel: "AgeCancelRequest | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Cancel an ongoing age verification process.
    """

    approve: "AgeApproveRequest | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Mark an ongoing age verification process as successful. (Cancel with success)
    """


default_message_pool.register_message("api.v1", "AgeRequest", AgeRequest)


@dataclass(eq=False, repr=False)
class AgeResponse(betterproto2.Message):
    """

    Response to an AgeRequest.

    Oneofs:
        - result: The result of the age verification process.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for the age verification request. Mirrors the ID from the AgeRequest.
    This field is always populated, either with the provided ID from the request or a newly generated one.
    """

    success: "AgeSuccess | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    failure: "AgeFailure | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    api_success: "AgeApiSuccess | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    api_failure: "AgeApiFailure | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """


default_message_pool.register_message("api.v1", "AgeResponse", AgeResponse)


@dataclass(eq=False, repr=False)
class AgeStartRequest(betterproto2.Message):
    """

    Starts an age verification process on the SENVEND terminal.
    """

    min_age: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    The minimum age required to pass verification. For example, 18 for at least 18 years old.
    This field is mandatory and should be a positive integer (greater than 0 but smaller or equal 120).
    """

    auto_cancel: "bool | None" = betterproto2.field(
        2, betterproto2.TYPE_BOOL, optional=True
    )
    """
    Optional - indicates if any already running request should be canceled.
    Defaults to true if left out.
    """


default_message_pool.register_message("api.v1", "AgeStartRequest", AgeStartRequest)


@dataclass(eq=False, repr=False)
class AgeSuccess(betterproto2.Message):
    """

    Indicates a successful age verification.
    """

    pass


default_message_pool.register_message("api.v1", "AgeSuccess", AgeSuccess)


@dataclass(eq=False, repr=False)
class LineItem(betterproto2.Message):
    """

    Represents a single line item of a complete invoice.

    Oneofs:
        - product: The identifier for the sold product
    """

    price: "int | None" = betterproto2.field(1, betterproto2.TYPE_UINT32, optional=True)
    """
    Price of a single instance of this product, in cents.
    """

    quantity: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    """
    The quantity of items to sell.
    """

    selection: "Selection | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="product"
    )
    """
    The slot this product was sold from.
    """


default_message_pool.register_message("api.v1", "LineItem", LineItem)


@dataclass(eq=False, repr=False)
class PayApiFailure(betterproto2.Message):
    """

    Indicates a wrong usage/argument in the Pay API.
    Does not end an already running payment process.
    """

    reason: "PayApiFailureReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: PayApiFailureReason(0)
    )
    """
    The reason for the API failure.
    """


default_message_pool.register_message("api.v1", "PayApiFailure", PayApiFailure)


@dataclass(eq=False, repr=False)
class PayApiSuccess(betterproto2.Message):
    """

    Indicates a successfully executed request.
    """

    reason: "PayApiSuccessReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: PayApiSuccessReason(0)
    )


default_message_pool.register_message("api.v1", "PayApiSuccess", PayApiSuccess)


@dataclass(eq=False, repr=False)
class PayApproved(betterproto2.Message):
    """

    Indicates the user has started the payment process successfully (has enough credit).
    Has to be answered with either a PayCancel or a PayGoodsIssued message.
    If not answered within 9m30s, the payment will be completed as if PayGoodsIssued was sent.
    """

    amount: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    The amount that was actually approved.
    Useful in case of multiple updates, since the approval might not be for the newest request.
    """


default_message_pool.register_message("api.v1", "PayApproved", PayApproved)


@dataclass(eq=False, repr=False)
class PayCancel(betterproto2.Message):
    """

    Cancels an ongoing payment process on the SENVEND terminal.
    Can also be used to cancel an approved payment (instead of PayGoodsIssued).
    Can be sent at any time, but will result in PAY_API_FAILURE_REASON_UUID_NOT_FOUND
    if there is nothing to cancel.
    If sent in a PayRequest without UUID, will cancel any running process without UUID check, including vending. (Catch all)
    """

    pass


default_message_pool.register_message("api.v1", "PayCancel", PayCancel)


@dataclass(eq=False, repr=False)
class PayFailure(betterproto2.Message):
    """

    Indicates a payment ending in failure.

    Oneofs:
        - reason: The reason for the payment failure.
    """

    failure_reason: "PayFailureReason | None" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, optional=True, group="reason"
    )


default_message_pool.register_message("api.v1", "PayFailure", PayFailure)


@dataclass(eq=False, repr=False)
class PayGoodsIssued(betterproto2.Message):
    """

    An approved payment will not be finalized until this message or a PayCancel is issued.
    A cancel or timeout will reimburse the payment.
    """

    partial_amount: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    Indicates partial issuing of goods, which will result in partial reimbursement.
    If cash amount is 0, a partial_amount of 0 will be replaced with the value from PayStart.amount or the latest PayUpdate.partial_amount.
    Cannot be greater than PayStart.amount or the latest PayUpdate.partial_amount.
    """

    line_items: "list[LineItem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Optional - the list of individual invoice positions that were actually issued to the customer.
    """

    cash_amount: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )
    """
    Optional - reporting field for partial or full cash payment.
    The sum of cash_amount + partial_amount will be checked against line_items.
    """


default_message_pool.register_message("api.v1", "PayGoodsIssued", PayGoodsIssued)


@dataclass(eq=False, repr=False)
class PayRequest(betterproto2.Message):
    """

    All messages sent from the integrator/VMC to the SENVEND terminal to manage payments.
    A payment process must be started with the PayStart message.

    Oneofs:
        - request: Actual command to control a specific payment process with the given UUID.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for this payment request. Can be used for tracing and correlating requests and responses.
    Optional field. If not provided, the system will generate a new UUID.
    """

    start: "PayStart | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Start a new payment process.
    """

    cancel: "PayCancel | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Cancel an ongoing payment process (possibly reimbursing the payment).
    """

    goods_issued: "PayGoodsIssued | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Signify that goods were issued (i.e. payment will NOT be reimbursed).
    """

    age_approve: "AgeApproveRequest | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Mark an ongoing age verification process as successful. (Cancel without error)
    """

    update: "PayUpdate | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Update payment amounts during an ongoing payment.
    """

    vend: "VendStart | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Vend items after APPROVED but before GOODS_ISSUED, or when no payment process is running.
    """

    vend_cancel: "VendCancel | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Cancel a previously started vending process.
    """


default_message_pool.register_message("api.v1", "PayRequest", PayRequest)


@dataclass(eq=False, repr=False)
class PayResponse(betterproto2.Message):
    """

    Response to a PayRequest.
    PaySuccess and PayFailure are final states, they indicate the end of the payment process.

    Oneofs:
        - result: The result of the payment process.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for the payment request. Mirrors the ID from the PayRequest.
    This field is always populated, either with the provided ID from the request or a newly generated one.
    """

    approved: "PayApproved | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    success: "PaySuccess | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    failure: "PayFailure | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    api_failure: "PayApiFailure | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    api_success: "PayApiSuccess | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    age_success: "AgeSuccess | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    age_failure: "AgeFailure | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    age_api_success: "AgeApiSuccess | None" = betterproto2.field(
        9, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    age_api_failure: "AgeApiFailure | None" = betterproto2.field(
        10, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    final state
    """

    vend_event: "VendEvent | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    vend_api_success: "VendApiSuccess | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    vend_api_failure: "VendApiFailure | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    vend_success: "VendResult | None" = betterproto2.field(
        14, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """

    vend_failure: "VendResult | None" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    transient state
    """


default_message_pool.register_message("api.v1", "PayResponse", PayResponse)


@dataclass(eq=False, repr=False)
class PayStart(betterproto2.Message):
    """

    Starts a payment process on the SENVEND terminal.
    If auto_cancel is given and false, it can only be executed after a previous process finished with either PayFailure or PaySuccess.
    Will result in a PAY_FAILURE_REASON_PAYMENT_ONGOING or PAY_FAILURE_REASON_INVALID_STATE otherwise.
    Without auto_cancel or if it is true, will automatically cancel any running request and then try to start this one.
    """

    amount: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    The amount to be paid, in cents.
    Can be 0 to implement Vending or AgeVerification only with an associated goods_issued message for telemetry purposes.
    """

    age_verification: "AgeStartRequest | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    Optional - age verification request to be performed before payment.
    The value of auto_cancel inside this message will be ignored.
    """

    line_items: "list[LineItem]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Optional - the list of individual invoice positions this payment is meant for.
    """

    cash_amount: "int | None" = betterproto2.field(
        4, betterproto2.TYPE_UINT32, optional=True
    )
    """
    Optional - reporting field for partial cash payment.
    Since PayStart.amount handles only cashless payments, the amount here is only for reporting purposes,
    but will be checked against line_items.
    """

    auto_cancel: "bool | None" = betterproto2.field(
        5, betterproto2.TYPE_BOOL, optional=True
    )
    """
    Optional - indicates if any already running request should be canceled.
    Defaults to true if left out.
    """


default_message_pool.register_message("api.v1", "PayStart", PayStart)


@dataclass(eq=False, repr=False)
class PaySuccess(betterproto2.Message):
    """

    Indicates that the payment was successfully debited.
    Ends the payment process.
    """

    pass


default_message_pool.register_message("api.v1", "PaySuccess", PaySuccess)


@dataclass(eq=False, repr=False)
class PayUpdate(betterproto2.Message):
    """

    Updates the payment amount on the SENVEND terminal mid-transaction.
    Main use case is handling cash payments after `PayStart`,
    and/or changing individual `LineItems` (e.g. if one item in a Basket was cancelled individually).
    If age verification was requested as well, this message is only accepted after the age verification was successful.
    Will result in a PAY_API_FAILURE_REASON_INVALID_STATE otherwise.
    Can only be accepted if the payment was not approved yet, or will result in a PAY_API_FAILURE_REASON_ALREADY_APPROVED otherwise.
    """

    partial_amount: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    The new cashless amount to be paid for this ongoing payment, in cents.
    If cash amount is 0, a partial_amount of 0 will be replaced with the value from PayStart.amount.
    """

    line_items: "list[LineItem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    Optional - the list of individual invoice positions this payment is meant for.
    """

    cash_amount: "int | None" = betterproto2.field(
        3, betterproto2.TYPE_UINT32, optional=True
    )
    """
    Optional - reporting field for partial or full cash payment.
    The sum of cash_amount + partial_amount will be checked against line_items.
    """


default_message_pool.register_message("api.v1", "PayUpdate", PayUpdate)


@dataclass(eq=False, repr=False)
class Selection(betterproto2.Message):
    """

    Represents the slot of an item.
    """

    slot: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    slot number as reported by the machine
    """


default_message_pool.register_message("api.v1", "Selection", Selection)


@dataclass(eq=False, repr=False)
class SemanticVersion(betterproto2.Message):
    """

    Represents a semantic version.
    https://semver.org/
    """

    major: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    Major version.
    """

    minor: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    """
    Minor version.
    """

    patch: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    Patch version.
    """

    branch: "str | None" = betterproto2.field(
        4, betterproto2.TYPE_STRING, optional=True
    )
    """
    Only set in non-release versions, in release versions it is left empty.
    """


default_message_pool.register_message("api.v1", "SemanticVersion", SemanticVersion)


@dataclass(eq=False, repr=False)
class Uuid4(betterproto2.Message):
    """

    Represents a UUID version 4.
    """

    msb: "int" = betterproto2.field(2, betterproto2.TYPE_UINT64)
    """
    Most significant bits.
    """

    lsb: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)
    """
    Least significant bits.
    """


default_message_pool.register_message("api.v1", "Uuid4", Uuid4)


@dataclass(eq=False, repr=False)
class VendApiFailure(betterproto2.Message):
    """

    Indicates a wrong usage/argument in the Vend API.
    Does not end an already running vend process.
    """

    reason: "VendApiFailureReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: VendApiFailureReason(0)
    )
    """
    The reason for the API failure.
    """


default_message_pool.register_message("api.v1", "VendApiFailure", VendApiFailure)


@dataclass(eq=False, repr=False)
class VendApiSuccess(betterproto2.Message):
    """

    Indicates a successfully executed request.
    """

    reason: "VendApiSuccessReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: VendApiSuccessReason(0)
    )


default_message_pool.register_message("api.v1", "VendApiSuccess", VendApiSuccess)


@dataclass(eq=False, repr=False)
class VendCancel(betterproto2.Message):
    """

    Cancels an ongoing vending process on the SENVEND terminal.
    Can be sent at any time, but will result in VEND_API_FAILURE_REASON_UUID_NOT_FOUND
    if there is nothing to cancel.
    If sent in a VendRequest without UUID, will cancel any running process without UUID check. (Catch all)
    """

    pass


default_message_pool.register_message("api.v1", "VendCancel", VendCancel)


@dataclass(eq=False, repr=False)
class VendEvent(betterproto2.Message):
    """

    VendEvent will be sent for each individual item that was vended, indicating failure or success.

    Oneofs:
        - result: The actual result of the vending attempt
    """

    success: "VendSuccess | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    The vending attempt was successful.
    """

    failure: "VendFailure | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )
    """
    At least one item failed to vend.
    """

    line_item: "LineItem | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    The line_item this status is for
    """


default_message_pool.register_message("api.v1", "VendEvent", VendEvent)


@dataclass(eq=False, repr=False)
class VendFailure(betterproto2.Message):
    """

    Indicates a vending process ending in failure.

    Oneofs:
        - protocol_error: Contains the protocol specific error, if there is one
    """

    reason: "VendFailureReason" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: VendFailureReason(0)
    )
    """
    The reason for the vending failure.
    """

    successes: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    """
    The number of successfully vended items, before a failure occurred
    i.e. if line_item.quantity = 2 and the second item failed, successes = 1
    always 0 if quantity is 1
    """

    mdb_selection_denied: "MdbSelectionDeniedReason | None" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, optional=True, group="protocol_error"
    )

    mdb_vend_failure: "MdbVendFailureReason | None" = betterproto2.field(
        4, betterproto2.TYPE_ENUM, optional=True, group="protocol_error"
    )


default_message_pool.register_message("api.v1", "VendFailure", VendFailure)


@dataclass(eq=False, repr=False)
class VendRequest(betterproto2.Message):
    """

    All messages sent from the integrator/VMC to the SENVEND terminal to manage vending.
    A Vending process must be started with the VendStart message.

    Oneofs:
        - request: Actual command to control a specific vend process with the given UUID.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for this vend request. Can be used for tracing and correlating requests and responses.
    Optional field. If not provided, the system will generate a new UUID.
    """

    start: "VendStart | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Start a new vending process.
    """

    cancel: "VendCancel | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="request"
    )
    """
    Cancel an ongoing vend process.
    """


default_message_pool.register_message("api.v1", "VendRequest", VendRequest)


@dataclass(eq=False, repr=False)
class VendResponse(betterproto2.Message):
    """

    Response to a VendRequest.
    success and failure are final states, they indicate the end of the vending process.

    Oneofs:
        - response:
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for the vending request. Mirrors the ID from the VendRequest.
    This field is always populated, either with the provided ID from the request or a newly generated one.
    """

    event: "VendEvent | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="response"
    )
    """
    transient state
    """

    api_failure: "VendApiFailure | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="response"
    )
    """
    transient/final state
    """

    api_success: "VendApiSuccess | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="response"
    )
    """
    transient state
    """

    success: "VendResult | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="response"
    )
    """
    final state
    """

    failure: "VendResult | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="response"
    )
    """
    final state
    """


default_message_pool.register_message("api.v1", "VendResponse", VendResponse)


@dataclass(eq=False, repr=False)
class VendResult(betterproto2.Message):
    """

    The final result of all VendEvents that happened during the vending process.
    Ends the vending process.
    """

    results: "list[VendEvent]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    The list of all vending states that happened during vending execution.
    In the same order as they were given via VendStart.
    """


default_message_pool.register_message("api.v1", "VendResult", VendResult)


@dataclass(eq=False, repr=False)
class VendStart(betterproto2.Message):
    """

    Starts a vending process on the SENVEND terminal.
    It can only be executed after a previous process finished with either VendFailure or VendSuccess.
    Will result in a VEND_API_FAILURE_REASON_VENDING_ONGOING otherwise.
    """

    line_items: "list[LineItem]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    The list of products to vend. Price is ignored currently.
    The terminal will try to vend each product in the list, and will send an individual response per item.
    Quantity will be used to vend the same product multiple times.
    """


default_message_pool.register_message("api.v1", "VendStart", VendStart)


@dataclass(eq=False, repr=False)
class VendSuccess(betterproto2.Message):
    """

    Indicates that the items were successfully vended.
    """

    pass


default_message_pool.register_message("api.v1", "VendSuccess", VendSuccess)


@dataclass(eq=False, repr=False)
class VersionRequest(betterproto2.Message):
    """

    Starts a one-off request for version information of the SENVEND terminal.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for this version request. Can be used for tracing and correlating requests and responses.
    Optional field. If not provided, the system will generate a new UUID.
    """


default_message_pool.register_message("api.v1", "VersionRequest", VersionRequest)


@dataclass(eq=False, repr=False)
class VersionResponse(betterproto2.Message):
    """

    Provides the current software and API version of the SENVEND terminal.
    """

    id: "Uuid4 | None" = betterproto2.field(1, betterproto2.TYPE_MESSAGE, optional=True)
    """
    Unique identifier for the version request. Mirrors the ID from the VersionRequest.
    This field is always populated, either with the provided ID from the request or a newly generated one.
    """

    app_version: "SemanticVersion | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    The version of the software installed on the SENVEND terminal.
    """

    api_version: "SemanticVersion | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    The version of this protocol specification the device is using.
    """


default_message_pool.register_message("api.v1", "VersionResponse", VersionResponse)
