[package]
name = "senvend_api_example"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
senvend_api.workspace = true
senvend_api_utils.workspace = true
senvend_api_macros.workspace = true

uuid = { workspace = true, features = ["v4"] }
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
