[package]
name = "senvend_api_utils"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
uuid.workspace = true

[features]
default = ["std"]
std = []
