// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/v1/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.senbax.senvend.proto.Api.V1 {

  /// <summary>Holder for reflection information generated from api/v1/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for api/v1/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNhcGkvdjEvY29tbW9uLnByb3RvEgZhcGkudjEiMQoFVXVpZDQSEAoDbXNi",
            "GAIgASgEUgNtc2ISEAoDbHNiGAMgASgEUgNsc2JKBAgBEAIiewoPU2VtYW50",
            "aWNWZXJzaW9uEhQKBW1ham9yGAEgASgNUgVtYWpvchIUCgVtaW5vchgCIAEo",
            "DVIFbWlub3ISFAoFcGF0Y2gYAyABKA1SBXBhdGNoEhsKBmJyYW5jaBgEIAEo",
            "CUgAUgZicmFuY2iIAQFCCQoHX2JyYW5jaCIfCglTZWxlY3Rpb24SEgoEc2xv",
            "dBgBIAEoDVIEc2xvdCKJAQoITGluZUl0ZW0SGQoFcHJpY2UYASABKA1IAVIF",
            "cHJpY2WIAQESGgoIcXVhbnRpdHkYAiABKA1SCHF1YW50aXR5EjEKCXNlbGVj",
            "dGlvbhgDIAEoCzIRLmFwaS52MS5TZWxlY3Rpb25IAFIJc2VsZWN0aW9uQgkK",
            "B3Byb2R1Y3RCCAoGX3ByaWNlKt4GChhNZGJTZWxlY3Rpb25EZW5pZWRSZWFz",
            "b24SKwonTURCX1NFTEVDVElPTl9ERU5JRURfUkVBU09OX1VOU1BFQ0lGSUVE",
            "EAASOgo2TURCX1NFTEVDVElPTl9ERU5JRURfUkVBU09OX1VOS05PV05fRVJS",
            "T1JfT1VUX09GX09SREVSEAESRwpDTURCX1NFTEVDVElPTl9ERU5JRURfUkVB",
            "U09OX1NFTEVDVElPTl9ET0VTX05PVF9FWElTVF9OT1RfQ09ORklHVVJFRBAC",
            "Ej0KOU1EQl9TRUxFQ1RJT05fREVOSUVEX1JFQVNPTl9TRUxFQ1RJT05fRU1Q",
            "VFlfTk9UX0RJU1BFTlNFRBADEjMKL01EQl9TRUxFQ1RJT05fREVOSUVEX1JF",
            "QVNPTl9TRUxFQ1RJT05fREVGRUNUSVZFEAQSMgouTURCX1NFTEVDVElPTl9E",
            "RU5JRURfUkVBU09OX0lOR1JFRElFTlRfSVNfT1ZFUhAFEjEKLU1EQl9TRUxF",
            "Q1RJT05fREVOSUVEX1JFQVNPTl9TRUxFQ1RJT05fQkxPQ0tFRBAGEjMKL01E",
            "Ql9TRUxFQ1RJT05fREVOSUVEX1JFQVNPTl9TRUxFQ1RJT05fSU5ISUJJVEVE",
            "EAcSLworTURCX1NFTEVDVElPTl9ERU5JRURfUkVBU09OX1BST0RVQ1RfRVhQ",
            "SVJFRBAIEkMKP01EQl9TRUxFQ1RJT05fREVOSUVEX1JFQVNPTl9URU1QRVJB",
            "VFVSRV9DT05ESVRJT05TX09VVF9PRl9SQU5HRRAJEjoKNk1EQl9TRUxFQ1RJ",
            "T05fREVOSUVEX1JFQVNPTl9NQUNISU5FX0JVU1lfT1JfV1JPTkdfTU9ERRAK",
            "EjMKL01EQl9TRUxFQ1RJT05fREVOSUVEX1JFQVNPTl9JTlNVRkZJQ0lFTlRf",
            "Q1JFRElUEAsSNgoyTURCX1NFTEVDVElPTl9ERU5JRURfUkVBU09OX01BQ0hJ",
            "TkVfVEVNUE9SQVJZX0JVU1kQDBIyCi5NREJfU0VMRUNUSU9OX0RFTklFRF9S",
            "RUFTT05fTUFYX1JFVFJZX0VYQ0VFREVEEA0SLQopTURCX1NFTEVDVElPTl9E",
            "RU5JRURfUkVBU09OX1VOS05PV05fRVJST1IQDiqzBQoUTWRiVmVuZEZhaWx1",
            "cmVSZWFzb24SJwojTURCX1ZFTkRfRkFJTFVSRV9SRUFTT05fVU5TUEVDSUZJ",
            "RUQQABIwCixNREJfVkVORF9GQUlMVVJFX1JFQVNPTl9VTktOT1dOX09VVF9P",
            "Rl9PUkRFUhABEkMKP01EQl9WRU5EX0ZBSUxVUkVfUkVBU09OX1NFTEVDVElP",
            "Tl9ET0VTX05PVF9FWElTVF9OT1RfQ09ORklHVVJFRBACEkEKPU1EQl9WRU5E",
            "X0ZBSUxVUkVfUkVBU09OX1NFTEVDVElPTl9FTVBUWV9QUk9EVUNUX05PVF9E",
            "SVNQRU5TRUQQAxIvCitNREJfVkVORF9GQUlMVVJFX1JFQVNPTl9TRUxFQ1RJ",
            "T05fREVGRUNUSVZFEAQSLgoqTURCX1ZFTkRfRkFJTFVSRV9SRUFTT05fSU5H",
            "UkVESUVOVF9JU19PVkVSEAUSLQopTURCX1ZFTkRfRkFJTFVSRV9SRUFTT05f",
            "U0VMRUNUSU9OX0JMT0NLRUQQBhIvCitNREJfVkVORF9GQUlMVVJFX1JFQVNP",
            "Tl9TRUxFQ1RJT05fSU5ISUJJVEVEEAcSKwonTURCX1ZFTkRfRkFJTFVSRV9S",
            "RUFTT05fUFJPRFVDVF9FWFBJUkVEEAgSPwo7TURCX1ZFTkRfRkFJTFVSRV9S",
            "RUFTT05fVEVNUEVSQVRVUkVfQ09ORElUSU9OU19PVVRfT0ZfUkFOR0UQCRIz",
            "Ci9NREJfVkVORF9GQUlMVVJFX1JFQVNPTl9NQUNISU5FX0JVU1lfV1JPTkdf",
            "TU9ERRAKEi8KK01EQl9WRU5EX0ZBSUxVUkVfUkVBU09OX0lOU1VGRklDSUVO",
            "VF9DUkVESVQQCxIjCh9NREJfVkVORF9GQUlMVVJFX1JFQVNPTl9VTktOT1dO",
            "EAxCawoKY29tLmFwaS52MUILQ29tbW9uUHJvdG9QAaICA0FYWKoCH2NvbS5z",
            "ZW5iYXguc2VudmVuZC5wcm90by5BcGkuVjHKAgZBcGlcVjHiAhJBcGlcVjFc",
            "R1BCTWV0YWRhdGHqAgdBcGk6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::com.senbax.senvend.proto.Api.V1.MdbSelectionDeniedReason), typeof(global::com.senbax.senvend.proto.Api.V1.MdbVendFailureReason), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::com.senbax.senvend.proto.Api.V1.Uuid4), global::com.senbax.senvend.proto.Api.V1.Uuid4.Parser, new[]{ "Msb", "Lsb" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.senbax.senvend.proto.Api.V1.SemanticVersion), global::com.senbax.senvend.proto.Api.V1.SemanticVersion.Parser, new[]{ "Major", "Minor", "Patch", "Branch" }, new[]{ "Branch" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.senbax.senvend.proto.Api.V1.Selection), global::com.senbax.senvend.proto.Api.V1.Selection.Parser, new[]{ "Slot" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.senbax.senvend.proto.Api.V1.LineItem), global::com.senbax.senvend.proto.Api.V1.LineItem.Parser, new[]{ "Price", "Quantity", "Selection" }, new[]{ "Product", "Price" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///
  /// Reasons why a selection request might be denied
  /// page 170 (MDB spec 4.3)
  /// </summary>
  public enum MdbSelectionDeniedReason {
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR_OUT_OF_ORDER")] UnknownErrorOutOfOrder = 1,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED")] SelectionDoesNotExistNotConfigured = 2,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_SELECTION_EMPTY_NOT_DISPENSED")] SelectionEmptyNotDispensed = 3,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_SELECTION_DEFECTIVE")] SelectionDefective = 4,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_INGREDIENT_IS_OVER")] IngredientIsOver = 5,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_SELECTION_BLOCKED")] SelectionBlocked = 6,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_SELECTION_INHIBITED")] SelectionInhibited = 7,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_PRODUCT_EXPIRED")] ProductExpired = 8,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE")] TemperatureConditionsOutOfRange = 9,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_MACHINE_BUSY_OR_WRONG_MODE")] MachineBusyOrWrongMode = 10,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_INSUFFICIENT_CREDIT")] InsufficientCredit = 11,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_MACHINE_TEMPORARY_BUSY")] MachineTemporaryBusy = 12,
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_MAX_RETRY_EXCEEDED")] MaxRetryExceeded = 13,
    /// <summary>
    /// The VMC reported an error code, that is not defined in the MDB spec
    /// </summary>
    [pbr::OriginalName("MDB_SELECTION_DENIED_REASON_UNKNOWN_ERROR")] UnknownError = 14,
  }

  /// <summary>
  ///
  /// Reasons why a vend failed(only available if basket/partial refund is enabled)
  /// page 170 (MDB spec 4.3 section 7.4.8)
  /// </summary>
  public enum MdbVendFailureReason {
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_UNKNOWN_OUT_OF_ORDER")] UnknownOutOfOrder = 1,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_SELECTION_DOES_NOT_EXIST_NOT_CONFIGURED")] SelectionDoesNotExistNotConfigured = 2,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_SELECTION_EMPTY_PRODUCT_NOT_DISPENSED")] SelectionEmptyProductNotDispensed = 3,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_SELECTION_DEFECTIVE")] SelectionDefective = 4,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_INGREDIENT_IS_OVER")] IngredientIsOver = 5,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_SELECTION_BLOCKED")] SelectionBlocked = 6,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_SELECTION_INHIBITED")] SelectionInhibited = 7,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_PRODUCT_EXPIRED")] ProductExpired = 8,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_TEMPERATURE_CONDITIONS_OUT_OF_RANGE")] TemperatureConditionsOutOfRange = 9,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_MACHINE_BUSY_WRONG_MODE")] MachineBusyWrongMode = 10,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_INSUFFICIENT_CREDIT")] InsufficientCredit = 11,
    [pbr::OriginalName("MDB_VEND_FAILURE_REASON_UNKNOWN")] Unknown = 12,
  }

  #endregion

  #region Messages
  /// <summary>
  ///
  /// Represents a UUID version 4.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Uuid4 : pb::IMessage<Uuid4>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Uuid4> _parser = new pb::MessageParser<Uuid4>(() => new Uuid4());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Uuid4> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.senbax.senvend.proto.Api.V1.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Uuid4() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Uuid4(Uuid4 other) : this() {
      msb_ = other.msb_;
      lsb_ = other.lsb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Uuid4 Clone() {
      return new Uuid4(this);
    }

    /// <summary>Field number for the "msb" field.</summary>
    public const int MsbFieldNumber = 2;
    private ulong msb_;
    /// <summary>
    /// Most significant bits.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Msb {
      get { return msb_; }
      set {
        msb_ = value;
      }
    }

    /// <summary>Field number for the "lsb" field.</summary>
    public const int LsbFieldNumber = 3;
    private ulong lsb_;
    /// <summary>
    /// Least significant bits.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Lsb {
      get { return lsb_; }
      set {
        lsb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Uuid4);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Uuid4 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msb != other.Msb) return false;
      if (Lsb != other.Lsb) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Msb != 0UL) hash ^= Msb.GetHashCode();
      if (Lsb != 0UL) hash ^= Lsb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Msb != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Msb);
      }
      if (Lsb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Lsb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Msb != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Msb);
      }
      if (Lsb != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Lsb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Msb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Msb);
      }
      if (Lsb != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Lsb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Uuid4 other) {
      if (other == null) {
        return;
      }
      if (other.Msb != 0UL) {
        Msb = other.Msb;
      }
      if (other.Lsb != 0UL) {
        Lsb = other.Lsb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Msb = input.ReadUInt64();
            break;
          }
          case 24: {
            Lsb = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Msb = input.ReadUInt64();
            break;
          }
          case 24: {
            Lsb = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// Represents a semantic version.
  /// https://semver.org/
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SemanticVersion : pb::IMessage<SemanticVersion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SemanticVersion> _parser = new pb::MessageParser<SemanticVersion>(() => new SemanticVersion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SemanticVersion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.senbax.senvend.proto.Api.V1.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticVersion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticVersion(SemanticVersion other) : this() {
      major_ = other.major_;
      minor_ = other.minor_;
      patch_ = other.patch_;
      branch_ = other.branch_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SemanticVersion Clone() {
      return new SemanticVersion(this);
    }

    /// <summary>Field number for the "major" field.</summary>
    public const int MajorFieldNumber = 1;
    private uint major_;
    /// <summary>
    /// Major version.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Major {
      get { return major_; }
      set {
        major_ = value;
      }
    }

    /// <summary>Field number for the "minor" field.</summary>
    public const int MinorFieldNumber = 2;
    private uint minor_;
    /// <summary>
    /// Minor version.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Minor {
      get { return minor_; }
      set {
        minor_ = value;
      }
    }

    /// <summary>Field number for the "patch" field.</summary>
    public const int PatchFieldNumber = 3;
    private uint patch_;
    /// <summary>
    /// Patch version.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Patch {
      get { return patch_; }
      set {
        patch_ = value;
      }
    }

    /// <summary>Field number for the "branch" field.</summary>
    public const int BranchFieldNumber = 4;
    private readonly static string BranchDefaultValue = "";

    private string branch_;
    /// <summary>
    /// Only set in non-release versions, in release versions it is left empty.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Branch {
      get { return branch_ ?? BranchDefaultValue; }
      set {
        branch_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "branch" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBranch {
      get { return branch_ != null; }
    }
    /// <summary>Clears the value of the "branch" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBranch() {
      branch_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SemanticVersion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SemanticVersion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Major != other.Major) return false;
      if (Minor != other.Minor) return false;
      if (Patch != other.Patch) return false;
      if (Branch != other.Branch) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Major != 0) hash ^= Major.GetHashCode();
      if (Minor != 0) hash ^= Minor.GetHashCode();
      if (Patch != 0) hash ^= Patch.GetHashCode();
      if (HasBranch) hash ^= Branch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Major != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Major);
      }
      if (Minor != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Minor);
      }
      if (Patch != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Patch);
      }
      if (HasBranch) {
        output.WriteRawTag(34);
        output.WriteString(Branch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Major != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Major);
      }
      if (Minor != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Minor);
      }
      if (Patch != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Patch);
      }
      if (HasBranch) {
        output.WriteRawTag(34);
        output.WriteString(Branch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Major != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Major);
      }
      if (Minor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Minor);
      }
      if (Patch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Patch);
      }
      if (HasBranch) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Branch);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SemanticVersion other) {
      if (other == null) {
        return;
      }
      if (other.Major != 0) {
        Major = other.Major;
      }
      if (other.Minor != 0) {
        Minor = other.Minor;
      }
      if (other.Patch != 0) {
        Patch = other.Patch;
      }
      if (other.HasBranch) {
        Branch = other.Branch;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Major = input.ReadUInt32();
            break;
          }
          case 16: {
            Minor = input.ReadUInt32();
            break;
          }
          case 24: {
            Patch = input.ReadUInt32();
            break;
          }
          case 34: {
            Branch = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Major = input.ReadUInt32();
            break;
          }
          case 16: {
            Minor = input.ReadUInt32();
            break;
          }
          case 24: {
            Patch = input.ReadUInt32();
            break;
          }
          case 34: {
            Branch = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// Represents the slot of an item.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Selection : pb::IMessage<Selection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Selection> _parser = new pb::MessageParser<Selection>(() => new Selection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Selection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.senbax.senvend.proto.Api.V1.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Selection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Selection(Selection other) : this() {
      slot_ = other.slot_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Selection Clone() {
      return new Selection(this);
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 1;
    private uint slot_;
    /// <summary>
    /// slot number as reported by the machine
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Selection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Selection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Slot != other.Slot) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Slot != 0) hash ^= Slot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Slot != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Slot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Slot != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Slot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Slot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Selection other) {
      if (other == null) {
        return;
      }
      if (other.Slot != 0) {
        Slot = other.Slot;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Slot = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Slot = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// Represents a single line item of a complete invoice.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LineItem : pb::IMessage<LineItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LineItem> _parser = new pb::MessageParser<LineItem>(() => new LineItem());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LineItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.senbax.senvend.proto.Api.V1.CommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LineItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LineItem(LineItem other) : this() {
      _hasBits0 = other._hasBits0;
      price_ = other.price_;
      quantity_ = other.quantity_;
      switch (other.ProductCase) {
        case ProductOneofCase.Selection:
          Selection = other.Selection.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LineItem Clone() {
      return new LineItem(this);
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 1;
    private readonly static uint PriceDefaultValue = 0;

    private uint price_;
    /// <summary>
    /// Price of a single instance of this product, in cents.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Price {
      get { if ((_hasBits0 & 1) != 0) { return price_; } else { return PriceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        price_ = value;
      }
    }
    /// <summary>Gets whether the "price" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPrice {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "price" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPrice() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private uint quantity_;
    /// <summary>
    /// The quantity of items to sell.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "selection" field.</summary>
    public const int SelectionFieldNumber = 3;
    /// <summary>
    /// The slot this product was sold from.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::com.senbax.senvend.proto.Api.V1.Selection Selection {
      get { return productCase_ == ProductOneofCase.Selection ? (global::com.senbax.senvend.proto.Api.V1.Selection) product_ : null; }
      set {
        product_ = value;
        productCase_ = value == null ? ProductOneofCase.None : ProductOneofCase.Selection;
      }
    }

    private object product_;
    /// <summary>Enum of possible cases for the "product" oneof.</summary>
    public enum ProductOneofCase {
      None = 0,
      Selection = 3,
    }
    private ProductOneofCase productCase_ = ProductOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProductOneofCase ProductCase {
      get { return productCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProduct() {
      productCase_ = ProductOneofCase.None;
      product_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LineItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LineItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Price != other.Price) return false;
      if (Quantity != other.Quantity) return false;
      if (!object.Equals(Selection, other.Selection)) return false;
      if (ProductCase != other.ProductCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPrice) hash ^= Price.GetHashCode();
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (productCase_ == ProductOneofCase.Selection) hash ^= Selection.GetHashCode();
      hash ^= (int) productCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPrice) {
        output.WriteRawTag(8);
        output.WriteUInt32(Price);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Quantity);
      }
      if (productCase_ == ProductOneofCase.Selection) {
        output.WriteRawTag(26);
        output.WriteMessage(Selection);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPrice) {
        output.WriteRawTag(8);
        output.WriteUInt32(Price);
      }
      if (Quantity != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Quantity);
      }
      if (productCase_ == ProductOneofCase.Selection) {
        output.WriteRawTag(26);
        output.WriteMessage(Selection);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPrice) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Price);
      }
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Quantity);
      }
      if (productCase_ == ProductOneofCase.Selection) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Selection);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LineItem other) {
      if (other == null) {
        return;
      }
      if (other.HasPrice) {
        Price = other.Price;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      switch (other.ProductCase) {
        case ProductOneofCase.Selection:
          if (Selection == null) {
            Selection = new global::com.senbax.senvend.proto.Api.V1.Selection();
          }
          Selection.MergeFrom(other.Selection);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Price = input.ReadUInt32();
            break;
          }
          case 16: {
            Quantity = input.ReadUInt32();
            break;
          }
          case 26: {
            global::com.senbax.senvend.proto.Api.V1.Selection subBuilder = new global::com.senbax.senvend.proto.Api.V1.Selection();
            if (productCase_ == ProductOneofCase.Selection) {
              subBuilder.MergeFrom(Selection);
            }
            input.ReadMessage(subBuilder);
            Selection = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Price = input.ReadUInt32();
            break;
          }
          case 16: {
            Quantity = input.ReadUInt32();
            break;
          }
          case 26: {
            global::com.senbax.senvend.proto.Api.V1.Selection subBuilder = new global::com.senbax.senvend.proto.Api.V1.Selection();
            if (productCase_ == ProductOneofCase.Selection) {
              subBuilder.MergeFrom(Selection);
            }
            input.ReadMessage(subBuilder);
            Selection = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
