// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: local/v1/local.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.senbax.senvend.proto.Local.V1 {

  /// <summary>Holder for reflection information generated from local/v1/local.proto</summary>
  public static partial class LocalReflection {

    #region Descriptor
    /// <summary>File descriptor for local/v1/local.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LocalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRsb2NhbC92MS9sb2NhbC5wcm90bxIIbG9jYWwudjEaEGFwaS92MS9hZ2Uu",
            "cHJvdG8aEGFwaS92MS9wYXkucHJvdG8aEWFwaS92MS92ZW5kLnByb3RvGhRh",
            "cGkvdjEvdmVyc2lvbi5wcm90bzJMChZBZ2VWZXJpZmljYXRpb25TZXJ2aWNl",
            "EjIKA0FnZRISLmFwaS52MS5BZ2VSZXF1ZXN0GhMuYXBpLnYxLkFnZVJlc3Bv",
            "bnNlKAEwATJACgpQYXlTZXJ2aWNlEjIKA1BheRISLmFwaS52MS5QYXlSZXF1",
            "ZXN0GhMuYXBpLnYxLlBheVJlc3BvbnNlKAEwATJECgtWZW5kU2VydmljZRI1",
            "CgRWZW5kEhMuYXBpLnYxLlZlbmRSZXF1ZXN0GhQuYXBpLnYxLlZlbmRSZXNw",
            "b25zZSgBMAEyTAoOVmVyc2lvblNlcnZpY2USOgoHVmVyc2lvbhIWLmFwaS52",
            "MS5WZXJzaW9uUmVxdWVzdBoXLmFwaS52MS5WZXJzaW9uUmVzcG9uc2VCdAoM",
            "Y29tLmxvY2FsLnYxQgpMb2NhbFByb3RvUAGiAgNMWFiqAiFjb20uc2VuYmF4",
            "LnNlbnZlbmQucHJvdG8uTG9jYWwuVjHKAghMb2NhbFxWMeICFExvY2FsXFYx",
            "XEdQQk1ldGFkYXRh6gIJTG9jYWw6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::com.senbax.senvend.proto.Api.V1.AgeReflection.Descriptor, global::com.senbax.senvend.proto.Api.V1.PayReflection.Descriptor, global::com.senbax.senvend.proto.Api.V1.VendReflection.Descriptor, global::com.senbax.senvend.proto.Api.V1.VersionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
