# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: local/v1/local.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AgeVerificationServiceStub",
    "PayServiceStub",
)

from collections.abc import Iterable, Iterator

import betterproto2
import grpc

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class AgeVerificationServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def age(
        self, messages: "Iterable[__api__v1__.AgeRequest]"
    ) -> "__api__v1__.AgeResponse":
        """
        Initiates an age verification process on the SENVEND Terminal
        """

        return self._channel.stream_unary(
            "/local.v1.AgeVerificationService/Age",
            __api__v1__.AgeRequest.SerializeToString,
            __api__v1__.AgeResponse.FromString,
        )(iter(messages))


class PayServiceStub:
    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def pay(
        self, messages: "Iterable[__api__v1__.PayRequest]"
    ) -> "Iterator[__api__v1__.PayResponse]":
        """
        Initiates a payment process on the SENVEND Terminal
        """

        yield from self._channel.stream_stream(
            "/local.v1.PayService/Pay",
            __api__v1__.PayRequest.SerializeToString,
            __api__v1__.PayResponse.FromString,
        )(iter(messages))


from ...api import v1 as __api__v1__
